// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var q=function(p,m){q=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,h){e.__proto__=h}||function(e,h){for(var l in h)h.hasOwnProperty(l)&&(e[l]=h[l])};return q(p,m)};return function(p,m){function e(){this.constructor=p}q(p,m);p.prototype=null===m?Object.create(m):(e.prototype=m.prototype,new e)}}();
define("esri/arcade/featureset/actions/AttributeFilter","require exports ../support/FeatureSet ../support/IdSet ../support/shared ../support/WhereClause ../../polyfill/promiseUtils".split(" "),function(q,p,m,e,h,l,n){var t=function(u){function c(b){var a=u.call(this,b)||this;a.declaredClass="esri.arcade.featureset.actions.AttributeFilter";a._maxProcessing=1E3;a._parent=b.parentfeatureset;b.whereclause instanceof l?(a._whereclause=b.whereclause,a._whereClauseFunction=null,b=a._whereclause.getFunctions(),
a._whereclauseDoesGeometry=!1,0<=b.indexOf("area")?a._whereclauseDoesGeometry=!0:0<=b.indexOf("length")&&(a._whereclauseDoesGeometry=!0)):(a._whereClauseFunction=b.whereclause,a._whereclause=null);return a}__extends(c,u);c.prototype._getSet=function(b){var a=this;return null===this._wset?this._ensureLoaded().then(function(){return a._parent._getFilteredSet("",null,!1===a._whereclauseDoesGeometry?a._whereclause:null,null,b)}).then(function(d){a._checkCancelled(b);a._wset=!0===a._whereclauseDoesGeometry||
null!==a._whereClauseFunction?new e(d._candidates.slice(0).concat(d._known.slice(0)),[],d._ordered,a._clonePageDefinition(d.pagesDefinition)):new e(d._candidates.slice(0),d._known.slice(0),d._ordered,a._clonePageDefinition(d.pagesDefinition));return a._wset}):n.resolve(this._wset)};c.prototype._isInFeatureSet=function(b){var a=this._parent._isInFeatureSet(b);if(a===h.IdState.NotInFeatureSet)return a;a=this._idstates[b];return void 0===a?h.IdState.Unknown:a};c.prototype._getFeature=function(b,a,d){return this._parent._getFeature(b,
a,d)};c.prototype._getFeatures=function(b,a,d,f){return this._parent._getFeatures(b,a,d,f)};c.prototype._featureFromCache=function(b){return this._parent._featureFromCache(b)};c.prototype.executeWhereClause=function(b){return this._whereclause.testFeature(b)};c.prototype.executeWhereClauseDeferred=function(b){if(null!==this._whereClauseFunction)try{var a=this._whereClauseFunction(b);return n.isThenable(a)?a:n.resolve(a)}catch(d){return n.reject(d)}return this._whereclause.testFeatureDeferred(b)};
c.prototype._fetchAndRefineFeatures=function(b,a,d){var f=this,c=new e([],b,!1,null),r=Math.min(a,b.length);return this._parent._getFeatures(c,-1,r,d).then(function(){f._checkCancelled(d);if(!1===f._whereclauseDoesGeometry&&null==f._whereClauseFunction){for(var k=0;k<r;k++){var c=f._parent._featureFromCache(b[k]);!0===f.executeWhereClause(c)?f._idstates[b[k]]=h.IdState.InFeatureSet:f._idstates[b[k]]=h.IdState.NotInFeatureSet}return"success"}for(var g=[],k=0;k<r;k++)c=f._parent._featureFromCache(b[k]),
g.push(f.executeWhereClauseDeferred(c));return n.all(g).then(function(d){for(var c=0;c<a;c++)f._idstates[b[c]]=!0===d[c]?h.IdState.InFeatureSet:h.IdState.NotInFeatureSet;return"success"})})};c.prototype._getFilteredSet=function(b,a,d,c,g){var f=this;!0!==this._whereclauseDoesGeometry&&null===this._whereClauseFunction&&(null!==d?null!==this._whereclause&&(d=l.combine(this._whereclause,d)):d=this._whereclause);return this._ensureLoaded().then(function(){return f._parent._getFilteredSet(b,a,d,c,g)}).then(function(a){f._checkCancelled(g);
return!0===f._whereclauseDoesGeometry||null!==f._whereClauseFunction?new e(a._candidates.slice(0).concat(a._known.slice(0)),[],a._ordered,f._clonePageDefinition(a.pagesDefinition)):new e(a._candidates.slice(0),a._known.slice(0),a._ordered,f._clonePageDefinition(a.pagesDefinition))})};c.prototype._stat=function(b,a,d,c,g,h,k){var f=this;if(!0===this._whereclauseDoesGeometry||null!==this._whereClauseFunction)return null===g&&""===d&&null===c?this._manualStat(b,a,h,k):n.resolve({calculated:!1});var e=
this._whereclause;null!==g&&null!==this._whereclause&&(e=l.combine(this._whereclause,g));return this._parent._stat(b,a,d,c,e,h,k).then(function(e){return!1===e.calculated?null===g&&""===d&&null===c?f._manualStat(b,a,h,k):{calculated:!1}:e})};c.prototype._canDoAggregates=function(b,a,c,f,g){if(!0===this._whereclauseDoesGeometry||null!==this._whereClauseFunction)return n.resolve(!1);null!==g?null!==this._whereclause&&(g=l.combine(this._whereclause,g)):g=this._whereclause;return null===this._parent?
n.resolve(!1):this._parent._canDoAggregates(b,a,c,f,g)};c.prototype._getAggregatePagesDataSourceDefinition=function(b,a,c,f,g,e,h){if(null===this._parent)return n.reject(Error("Should never be called"));null!==g?null!==this._whereclause&&(g=l.combine(this._whereclause,g)):g=this._whereclause;return this._parent._getAggregatePagesDataSourceDefinition(b,a,c,f,g,e,h)};c.prototype.arcadeScriptStep=function(b,a,c){b=this.arcadeAssignNextScriptStepIdentifiers(c);a=this._whereclause.toWhereClause(h.FeatureServiceDatabaseType.Standardised);
return"var "+b.newFeatureSet+" \x3d "+this.bigDataCachePipeline("filter( "+b.currentFeatureSet+',"'+a+'")')+";"};return c}(m);m._featuresetFunctions.filter=function(e,c){void 0===c&&(c=null);if("function"===typeof e)return new t({parentfeatureset:this,whereclause:e});if(""===e)return this;e=l.create(e);if(null!==c){var b={},a;for(a in c)b[a.toLowerCase()]=c[a];e.setVariablesDictionary(b)}return new t({parentfeatureset:this,whereclause:e})};return t});