// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/query/_SectionJsonCollector",["dojo/_base/lang","esri/dijit/geoenrichment/utils/MathUtil","esri/dijit/geoenrichment/ReportPlayer/core/grid/coreUtils/GridDataUtil","../../tableJson/TableJsonUtil"],function(t,u,q,v){var h={},w={provideParentInfo:function(a,b,c,d,e,g){k.collectStatistics(b);var f;a:{switch(e){case "floating":f=b.style.left+g.left;break a;case "page":f=k.calcX(b,c,d)+g.left;break a}f=void 0}a:{switch(e){case "floating":e=
b.style.spaceBefore+g.top;break a;case "page":e=k.calcY(b,c,d)+g.top;break a}e=void 0}a._parentBox={x:f,y:e,w:k.calcFullWidth(b,c,d),h:k.calcFullHeight(b,c,d)};b=d.field;c.style.fields=c.style.fields||{};c=(c.style.fields[b]=c.style.fields[b]||{}).backgroundColor;a._parentStyle={backgroundColor:c}},sanitize:function(a){k.sanitize(a)}},k={collectStatistics:function(a){if(!a._measureInfo){var b={},c={},d;a.data.columns.forEach(function(a){d&&(c[d.field]=a);d=a;b[a.field]=a});var e={},g={},f={},h={},
x={},n={};a.data.data.forEach(function(b,c){a.data.columns.forEach(function(a,d){var m=x[d]||0,r=n[c]||0,l=k._getDataHeight(b,a.field);a=k._getFieldWidth(b,a);m+=l;r+=a;x[d]=m;n[c]=r;l=d+"_"+c;g[l]=m;e[l]=r;f[l]=e[d-1+"_"+c]||0;h[l]=g[d+"_"+(c-1)]||0})});a._measureInfo={xPositions:f,yPositions:h,columnsHash:b,nextColumnHash:c}}},calcX:function(a,b,c){c=a.data.columns.indexOf(c);b=a.data.data.indexOf(b);return a._measureInfo.xPositions[c+"_"+b]||0},calcY:function(a,b,c){c=a.data.columns.indexOf(c);
b=a.data.data.indexOf(b);return a._measureInfo.yPositions[c+"_"+b]||0},calcFullWidth:function(a,b,c){c=c.field;var d=k._getFieldWidth(b,a._measureInfo.columnsHash[c]),e=b.columnSpans&&b.columnSpans[c]||1;if(1<e)for(var g,f=0;f<e-1;f++)g=a._measureInfo.nextColumnHash[g?g.field:c],d+=k._getFieldWidth(b,g);return d},_getFieldWidth:function(a,b){a.style.fields=a.style.fields||{};return(a.style.fields[b.field]=a.style.fields[b.field]||{}).width||b.style.width},calcFullHeight:function(a,b,c){c=c.field;
var d=a.data.data.indexOf(b),e=k._getDataHeight(b,c);b=b.rowSpans&&b.rowSpans[c]||1;if(1<b)for(var g=d+1,f=0;f<b-1;f++)d=a.data.data[g++],e+=k._getDataHeight(d,c);return e},_getDataHeight:function(a,b){a.style.fields=a.style.fields||{};return(a.style.fields[b]=a.style.fields[b]||{}).height||a.style.height},sanitize:function(a){delete a._measureInfo}},y={getIntersectingTableJsonsBehind:function(a,b,c,d,e){function g(a){var d=a.data.data[0].fieldInfos[a.data.columns[0].field];return q.isTextLikeCell(d)||
q.isShapeCell(d)||q.isImageCell(d)?u.checkRectsIntersect([c,{x:a.style.left+b.left,y:a.style.spaceBefore+b.top,w:v.getTableWidth(a),h:v.getTableHeight(a)}]):!1}function f(a){return u.checkRectsIntersect([c,{x:a.style.left+b.left,y:a.style.spaceBefore+b.top,w:a.style.width,h:a.style.height}])}var k=[],h=[];a.backgroundFloatingTablesSectionJson&&a.backgroundFloatingTablesSectionJson.stack.forEach(function(a,b){if(-1===d||e||d!==b)if("table"===a.id&&g(a)||"img"===a.id&&f(a))-1===d||e||d>b?k.push(a):
h.push(a)});a.foregroundFloatingTablesSectionJson&&a.foregroundFloatingTablesSectionJson.stack.forEach(function(a,b){if(e&&d===b)return!0;if("table"===a.id&&g(a)||"img"===a.id&&f(a))e&&d>b?k.push(a):h.push(a)});return{elementJsonsBehind:k,elementJsonsAbove:h}}};h.collectSectionJsons=function(a,b){b=b||{};var c=[];if(!a)return[];if(a.sections)return a.sections;if(!a.sectionsTables)return[];a.sectionsTables.forEach(function(d){!1!==b.backgroundForeground&&d.foregroundSectionJson&&d.foregroundSectionJson.stack&&
c.push(d.foregroundSectionJson);var e=[];!1!==b.floatingTables&&d.foregroundFloatingTablesSectionJson&&d.foregroundFloatingTablesSectionJson.stack.forEach(function(c,f){"table"===c.id&&h._processTableJson(c,e,"floating",a.documentOptions,b,d,f,!0)});e.reverse();c=c.concat(e);h._processTableJson(d,c,"page",a.documentOptions,b,d);e.length=0;!1!==b.floatingTables&&d.backgroundFloatingTablesSectionJson&&d.backgroundFloatingTablesSectionJson.stack.forEach(function(c,f){"table"===c.id&&h._processTableJson(c,
e,"floating",a.documentOptions,b,d,f,!1)});e.reverse();c=c.concat(e);!1!==b.backgroundForeground&&d.backgroundSectionJson&&d.backgroundSectionJson.stack&&c.push(d.backgroundSectionJson)});return c};h._processTableJson=function(a,b,c,d,e,g,f,k){a.data.data.forEach(function(h){h.fieldInfos&&a.data.columns.forEach(function(n){var m=h.fieldInfos[n.field];if(m&&m.sectionJson&&m.sectionJson.stack)if(e.processFieldInfoFunc&&e.processFieldInfoFunc(m),(!1!==e.saveParentInfo||e.populateWithFloatingElementsBehind)&&
w.provideParentInfo(m.sectionJson,a,h,n,c,d),e.populateWithFloatingElementsBehind){n=function(a){a=t.clone(a);a.isContextFloatingElement=!0;a.style.left=a.style.left+d.left-l._parentBox.x;"table"===a.id?a.style.spaceBefore=a.style.spaceBefore+d.top-l._parentBox.y:"img"===a.id&&(a.style.top=a.style.top+d.top-l._parentBox.y);return a};var l=t.clone(m.sectionJson),p;"page"===c?p=y.getIntersectingTableJsonsBehind(g,d,l._parentBox,-1,void 0):"floating"===c&&(p=y.getIntersectingTableJsonsBehind(g,d,l._parentBox,
f,k));m=p.elementJsonsBehind.map(n);p=p.elementJsonsAbove.map(n);l.stack=m.concat(l.stack);l.stack=l.stack.concat(p);b.push(l)}else b.push(m.sectionJson)})});w.sanitize(a)};h.getParentBox=function(a){return a&&a._parentBox};h.getParentStyle=function(a){return a&&a._parentStyle};return h});