// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/arcade/functions/geometry","require exports ../Dictionary ../Feature ../ImmutablePointArray ../languageUtils ../../geometry/Extent ../../geometry/Geometry ../../geometry/Multipoint ../../geometry/Point ../../geometry/Polygon ../../geometry/Polyline ../../geometry/jsonUtils".split(" "),function(y,u,k,h,w,d,v,q,r,n,p,t,m){Object.defineProperty(u,"__esModule",{value:!0});u.registerFunctions=function(g,l){g.ringisclockwise=function(c,e){return l(c,e,function(b,f,a){d.pcCheck(a,1,1);b=[];
if(null===a[0])return!1;if(d.isArray(a[0])){var c=0;for(a=a[0];c<a.length;c++)if(f=a[c],f instanceof n)b.push([f.x,f.y]);else throw Error("Invalid Argument");}else if(a[0]instanceof w)b=a[0]._elements;else if(d.isImmutableArray(a[0])){for(var c=0,e=a[0].toArray();c<e.length;c++)if(f=e[c],f instanceof n)b.push([f.x,f.y]);else throw Error("Invalid Argument");0<b.length&&(a[0].get(0),a[0].get(0))}else throw Error("Invalid Argument");return 3>b.length?!1:(new p({rings:[],spatialReference:{wkid:4326}})).isClockwise(b)})};
g.polygon=function(c,e){return l(c,e,function(b,f,a){d.pcCheck(a,1,1);b=null;if(a[0]instanceof k){if(b=d.fixSpatialReference(h.parseGeometryFromDictionary(a[0]),c.spatialReference),!1===b instanceof p)throw Error("Illegal Parameter");}else b=a[0]instanceof p?m.fromJson(a[0].toJson()):d.fixSpatialReference(new p(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");
return d.fixNullGeometry(b)})};g.polyline=function(c,e){return l(c,e,function(b,f,a){d.pcCheck(a,1,1);b=null;if(a[0]instanceof k){if(b=d.fixSpatialReference(h.parseGeometryFromDictionary(a[0]),c.spatialReference),!1===b instanceof t)throw Error("Illegal Parameter");}else b=a[0]instanceof t?m.fromJson(a[0].toJson()):d.fixSpatialReference(new t(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");
return d.fixNullGeometry(b)})};g.point=function(c,e){return l(c,e,function(b,f,a){d.pcCheck(a,1,1);b=null;if(a[0]instanceof k){if(b=d.fixSpatialReference(h.parseGeometryFromDictionary(a[0]),c.spatialReference),!1===b instanceof n)throw Error("Illegal Parameter");}else b=a[0]instanceof n?m.fromJson(a[0].toJson()):d.fixSpatialReference(new n(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");
return d.fixNullGeometry(b)})};g.multipoint=function(c,e){return l(c,e,function(b,f,a){d.pcCheck(a,1,1);b=null;if(a[0]instanceof k){if(b=d.fixSpatialReference(h.parseGeometryFromDictionary(a[0]),c.spatialReference),!1===b instanceof r)throw Error("Illegal Parameter");}else b=a[0]instanceof r?m.fromJson(a[0].toJson()):d.fixSpatialReference(new r(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");
return d.fixNullGeometry(b)})};g.extent=function(c,e){return l(c,e,function(b,f,a){a=d.autoCastFeatureToGeometry(a);d.pcCheck(a,1,1);b=null;a[0]instanceof k?b=d.fixSpatialReference(h.parseGeometryFromDictionary(a[0]),c.spatialReference):a[0]instanceof n?(b={xmin:a[0].x,ymin:a[0].y,xmax:a[0].x,ymax:a[0].y,spatialReference:a[0].spatialReference.toJson()},a[0].hasZ?(b.zmin=a[0].z,b.zmax=a[0].z):a[0].hasM&&(b.mmin=a[0].m,b.mmax=a[0].m),b=m.fromJson(b)):b=a[0]instanceof p?m.fromJson(a[0].getExtent().toJson()):
a[0]instanceof t?m.fromJson(a[0].getExtent().toJson()):a[0]instanceof r?m.fromJson(a[0].getExtent().toJson()):a[0]instanceof v?m.fromJson(a[0].toJson()):d.fixSpatialReference(new v(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return d.fixNullGeometry(b)})};g.geometry=function(c,e){return l(c,e,function(b,f,a){d.pcCheck(a,1,1);b=null;
b=a[0]instanceof h?d.fixSpatialReference(a[0].geometry(),c.spatialReference):a[0]instanceof k?d.fixSpatialReference(h.parseGeometryFromDictionary(a[0]),c.spatialReference):d.fixSpatialReference(m.fromJson(JSON.parse(a[0])),c.spatialReference);if(null!==b&&!1===b.spatialReference.equals(c.spatialReference))throw Error("Cannot create Geometry in this SpatialReference. Engine is using a different spatial reference.");return d.fixNullGeometry(b)})};g.setgeometry=function(c,e){return l(c,e,function(b,
c,a){d.pcCheck(a,2,2);if(a[0]instanceof h){if(!0===a[0].immutable)throw Error("Feature is Immutable");if(a[1]instanceof q||null===a[1])a[0]._geometry=a[1];else throw Error("Illegal Argument");}else throw Error("Illegal Argument");return d.voidOperation})};g.feature=function(c,e){return l(c,e,function(b,f,a){if(0===a.length)throw Error("Missing Parameters");b=null;if(1===a.length)if(d.isString(a[0]))b=h.fromJson(JSON.parse(a[0]));else if(a[0]instanceof h)b=h.createFromArcadeFeature(a[0]);else if(a[0]instanceof
q)b=h.createFromGraphicLikeObject(a[0],null,null);else if(a[0]instanceof k)b=a[0].hasField("geometry")?a[0].field("geometry"):null,f=a[0].hasField("attributes")?a[0].field("attributes"):null,null!==b&&b instanceof k&&(b=h.parseGeometryFromDictionary(b)),null!==f&&(f=h.parseAttributesFromDictionary(f)),b=h.createFromGraphicLikeObject(b,f,null);else throw Error("Illegal Argument");else{if(2===a.length){f=b=null;if(null!==a[0])if(a[0]instanceof q)b=a[0];else if(b instanceof k)b=h.parseGeometryFromDictionary(a[0]);
else throw Error("Illegal Argument");if(null!==a[1])if(a[1]instanceof k)f=h.parseAttributesFromDictionary(a[1]);else throw Error("Illegal Argument");}else{b=null;f={};if(null!==a[0])if(a[0]instanceof q)b=a[0];else if(b instanceof k)b=h.parseGeometryFromDictionary(a[0]);else throw Error("Illegal Argument");for(var e=1;e<a.length;e+=2){var x=d.toString(a[e]),g=a[e+1];if(null===g||void 0===g||d.isString(g)||isNaN(g)||d.isDate(g)||d.isNumber(g)||d.isBoolean(g)){if(d.isFunctionParameter(g)||!1===d.isSimpleType(g))throw Error("Illegal Argument");
f[x]=g===d.voidOperation?null:g}else throw Error("Illegal Argument");}}b=h.createFromGraphicLikeObject(b,f,null)}b._geometry=d.fixSpatialReference(b.geometry(),c.spatialReference);b.immutable=!1;return b})};g.dictionary=function(c,e){return l(c,e,function(b,c,a){if(0===a.length)throw Error("Missing Parameters");if(0!==a.length%2)throw Error("Missing Parameters");b={};for(c=0;c<a.length;c+=2){var f=d.toString(a[c]),e=a[c+1];if(null===e||void 0===e||d.isString(e)||isNaN(e)||d.isDate(e)||d.isNumber(e)||
d.isBoolean(e)||d.isArray(e)||d.isImmutableArray(e)){if(d.isFunctionParameter(e))throw Error("Illegal Argument");b[f]=e===d.voidOperation?null:e}else throw Error("Illegal Argument");}a=new k(b);a.immutable=!1;return a})};g.haskey=function(c,e){return l(c,e,function(b,c,a){d.pcCheck(a,2,2);b=d.toString(a[1]);if(a[0]instanceof h||a[0]instanceof k)return a[0].hasField(b);throw Error("Illegal Argument");})};g.indexof=function(c,e){return l(c,e,function(b,c,a){d.pcCheck(a,2,2);b=a[1];if(d.isArray(a[0])){for(c=
0;c<a[0].length;c++)if(d.equalityTest(b,a[0][c]))return c;return-1}if(d.isImmutableArray(a[0])){var e=a[0].length();for(c=0;c<e;c++)if(d.equalityTest(b,a[0].get(c)))return c;return-1}throw Error("Illegal Argument");})}}});