// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicFilter","dojo/_base/declare dojo/aspect dojo/dom-construct dijit/_WidgetBase dijit/_TemplatedMixin ./chart/ChartFilter ./locator/LocatorFilter ./areaDetails/AreaDetailsFilter ./comparison/ComparisonFilter ./dynamicInfographic/DynamicInfographicFilter".split(" "),function(e,d,c,f,g,h,k,l,m,n){return e([f,g],{templateString:"\x3cdiv class\x3d'esriGEReportPlayer_sectionDynamicFilter'\x3e\x3c/div\x3e",areaDetailsFilter:null,
chartFilter:null,comparisonFilter:null,dynamicInfographicFilter:null,locatorFilter:null,_areaDetailsFilterWidget:null,_chartFilterWidget:null,_comparisonFilterWidget:null,_dynamicInfographicFilterWidget:null,_locatorFilterWidget:null,postCreate:function(){this._tryInitAreaDetailsFilter();this._tryInitChartFilter();this._tryInitComparisonFilter();this._tryInitDynamicInfographicFilter();this._tryInitLocatorFilter()},_tryInitAreaDetailsFilter:function(){function a(){b._areaDetailsFilterWidget.setNumItems(b.areaDetailsFilter.getNumItemsTotal(),
b.areaDetailsFilter.getNumItemsShown())}var b=this;this.areaDetailsFilter&&(this._areaDetailsFilterWidget=(new l({onAreaDetailsFilterChanged:this.onAreaDetailsFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicFilter_row"},this.domNode)),this.own(this._areaDetailsFilterWidget),a(),this.own(d.after(this.areaDetailsFilter,"onContentUpdated",a)))},_tryInitChartFilter:function(){function a(){b._chartFilterWidget.setNumElements(b.chartFilter.getNumElementsTotal(),b.chartFilter.getNumElementsShown())}
var b=this;this.chartFilter&&(this._chartFilterWidget=(new h({onFilterRangesChanged:this.onChartFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicFilter_row"},this.domNode)),this.own(this._chartFilterWidget),this._chartFilterWidget.setSettings(this.chartFilter),a(),this.own(d.after(this.chartFilter,"onContentUpdated",a)))},_tryInitComparisonFilter:function(){function a(){b._comparisonFilterWidget.setNumAreas(b.comparisonFilter.getNumAreasTotal(),b.comparisonFilter.getNumAreasShown())}
var b=this;this.comparisonFilter&&(this._comparisonFilterWidget=(new m({onComparisonFilterChanged:this.onComparisonFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicFilter_row"},this.domNode)),this.own(this._comparisonFilterWidget),this._comparisonFilterWidget.setFilter(this.comparisonFilter),a(),this.own(d.after(this.comparisonFilter,"onContentUpdated",a)))},_tryInitDynamicInfographicFilter:function(){function a(){b._dynamicInfographicFilterWidget.setNumAreas(b.dynamicInfographicFilter.getNumAreasTotal(),
b.dynamicInfographicFilter.getNumAreasShown())}var b=this;this.dynamicInfographicFilter&&(this._dynamicInfographicFilterWidget=(new n({onDynamicInfographicFilterChanged:this.onDynamicInfographicFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicFilter_row"},this.domNode)),this.own(this._dynamicInfographicFilterWidget),this._dynamicInfographicFilterWidget.setFilter(this.dynamicInfographicFilter),a(),this.own(d.after(this.dynamicInfographicFilter,"onContentUpdated",a)))},updateDynamicInfographicFilter:function(a){if(this.dynamicInfographicFilter){var b=
this._dynamicInfographicFilterWidget.domNode.parentNode;this._dynamicInfographicFilterWidget.destroy();c.destroy(b);this.dynamicInfographicFilter=a;this._tryInitDynamicInfographicFilter()}},_tryInitLocatorFilter:function(){function a(){b._locatorFilterWidget.setNumPoints(b.locatorFilter.getNumPointsTotal(),b.locatorFilter.getNumPointsShown())}var b=this;this.locatorFilter&&(this._locatorFilterWidget=(new k({onLocatorFilterChanged:this.onLocatorFilterChanged.bind(this)})).placeAt(c.create("div",{"class":"sectionDynamicFilter_row"},
this.domNode)),this.own(this._locatorFilterWidget),this._locatorFilterWidget.setFilterRanges(this.locatorFilter.filterRanges),a(),this.own(d.after(this.locatorFilter,"onContentUpdated",a)))},setVisualState:function(a){this._chartFilterWidget&&this._chartFilterWidget.setVisualState(a);this._locatorFilterWidget&&this._locatorFilterWidget.setVisualState(a);this._areaDetailsFilterWidget&&this._areaDetailsFilterWidget.setVisualState(a);this._comparisonFilterWidget&&this._comparisonFilterWidget.setVisualState(a);
this._dynamicInfographicFilterWidget&&this._dynamicInfographicFilterWidget.setVisualState(a)},onAreaDetailsFilterChanged:function(a){},onChartFilterChanged:function(a){},onComparisonFilterChanged:function(a){},onLocatorFilterChanged:function(a){},onDynamicInfographicFilterChanged:function(a){},onClosePopup:function(){}})});