// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/_ClusteredBarsBase","dojo/_base/lang dojo/_base/array dojo/_base/declare dojox/charting/plot2d/CartesianBase dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/lang/utils dojox/lang/functional dojox/lang/functional/reversed ./labelsRendering/_BarsLabelRenderingFix ./animation/_ClusteredBarsAnimation ./_MinVisibleBar".split(" "),function(u,z,C,D,E,v,y,F,G,H,I,J){var K=G.lambda("item.purgeGroup()");return C("dojox.charting.plot2d.Bars",
[D,E,H,I,J],{_mainShapes:null,_animationInfos:null,defaultParams:{gap:0,animate:null},optionalParams:{minBarSize:1,maxBarSize:1},constructor:function(a,b){this.opt=u.clone(u.mixin(this.opt,this.defaultParams));y.updateWithObject(this.opt,b);y.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate;this.renderingOptions={"shape-rendering":"crispEdges"}},getSeriesStats:function(){var a=v.collectSimpleStats(this.series,function(a){return null==a}),b;a.hmin-=.5;a.hmax+=.5;b=a.hmin;
a.hmin=a.vmin;a.vmin=b;b=a.hmax;a.hmax=a.vmax;a.vmax=b;return a},render:function(a,b){if(!this.chart.isPreRenderMode){this.dirty=this.isDirty();this.resetEvents();var d;this.dirty&&(z.forEach(this.series,K),this._eventSeries={},this.cleanGroup(),d=this.getGroup(),F.forEachRev(this.series,function(a){a.cleanGroup(d)}));var c=this.chart.theme,h=this._hScaler.scaler.getTransformerFromModel(this._hScaler),f=this._vScaler.scaler.getTransformerFromModel(this._vScaler),g=h(Math.max(c.series.baseLineValue||
0,this._hScaler.bounds.lower)),m=this.events(),n=this.getBarProperties();this._mainShapes=[];this._animationInfos=[];for(var A=this.extractValues(this._vScaler),A=this.rearrangeValues(A,h,g),r=this.series.length-1;0<=r;--r){var e=this.series[r];if(this.dirty||e.dirty){e.cleanGroup();var u=c.next("bar",[this.opt,e]),v=Array(e.data.length);d=e.group;for(var w=z.some(e.data,function(a){return"number"===typeof a||a&&!a.hasOwnProperty("x")}),y=w?Math.min(e.data.length,Math.ceil(this._vScaler.bounds.to)):
e.data.length,k=w?Math.max(0,Math.floor(this._vScaler.bounds.from-1)):0;k<y;++k){var l=e.data[k];if(null!=l){var q=this.getValue(l,k,r,w);h(q.y);var B=A[r][k],p;this.opt.styleFunc||"number"!==typeof l?(p="number"!==typeof l?[l]:[],this.opt.styleFunc&&p.push(this.opt.styleFunc(l)),p=c.addMixin(u,"bar",p,!0)):p=c.post(u,"bar");if(1<=n.height){var t={x:b.l+g+Math.min(B,0),y:a.height-b.b-f(q.x+1.5)+n.gap+n.thickness*this._getYShift(r,c),width:Math.abs(B),height:n.height},t=this._drawBar(d,l,t,p,a,b,e,
g,k),x=t.shape;c.series.isEditMode&&(x.rawNode.style.cursor="pointer");x.value=l;this._mainShapes.push(x);t=t.rect;m&&(q={element:"bar",index:k,run:e,shape:x,cx:q.y,cy:q.x+1.5,x:w?k:e.data[k].x,y:w?e.data[k]:e.data[k].y},this._connectEvents(q),v[k]=q);this.createLabel(d,l,t,p,a,b);this.animate&&(l={shape:x,hoffset:b.l+g,hsize:-B},this._animationInfos.push(l),this._animateBar(l))}}}this._eventSeries[e.name]=v;e.dirty=!1}else c.skip(),this._reconnectEvents(e.name)}this._renderLabels(p,a,b,d);this.dirty=
!1;return this}},getMainShapes:function(){return this._mainShapes},_drawBar:function(a,b,d,c,h,f,g,m,n){},_getYShift:function(a,b){return b.series.renderColumnBarsInOppositeDirections?a>=this.series.length/2?a-this.series.length/2:a:a},getValue:function(a,b,d,c){c?(d="number"===typeof a?a:a.y,a=b):(d=a.y,a=a.x-1);return{y:d,x:a}},extractValues:function(a){for(var b=[],d=this.series.length-1;0<=d;--d){var c=this.series[d];if(this.dirty||c.dirty){var h=z.some(c.data,function(a){return"number"==typeof a||
a&&!a.hasOwnProperty("x")}),f=h?Math.max(0,Math.floor(a.bounds.from-1)):0,h=h?Math.min(c.data.length,Math.ceil(a.bounds.to)):c.data.length,g=b[d]=[];g.min=f;for(g.max=h;f<h;++f){var m=c.data[f];g[f]=this.isNullValue(m)?0:"number"==typeof m?m:m.y}}}return b},rearrangeValues:function(a,b,d){for(var c=0,h=a.length;c<h;++c){var f=a[c];if(f)for(var g=f.min,m=f.max;g<m;++g){var n=f[g];f[g]=this.isNullValue(n)?0:b(n)-d}}return a},getBarProperties:function(){var a=v.calculateBarSize(this._vScaler.bounds.scale,
this.opt,this._getClusterSize());return{gap:a.gap,height:a.size,thickness:a.size}},_getClusterSize:function(){var a=this.series.length;return this.chart.theme.series.renderColumnBarsInOppositeDirections?Math.round(a/2):a}})});