// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/paginatableTable/SectionJsonsBuilder","dojo/_base/lang ../../sections/SectionTypes ../../grid/coreUtils/GridDataUtil ../../supportClasses/tableJson/TableJsonResizeUtil ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoFormatUtil esri/dijit/geoenrichment/utils/FieldUtil".split(" "),function(f,x,q,r,y,t){function u(b,a){return t.isNumericField(b)&&"number"===typeof a&&!isNaN(a)}var c={buildSectionJsonsAndStat:function(b){var a=
c._collectGridDataObjectsAndStats(b);if(!a)return null;if(a.gridDataObjects.length)var d=c._splitRowsByPages(a.gridDataObjects,b).map(function(a){return c._buildSectionJsonForPage(a,b)});return{sectionJsons:d,stats:a.stats,unitedSectionJson:c._buildSectionJsonForPage(a.gridDataObjects,b)}},_collectGridDataObjectsAndStats:function(b){var a=b.calculatorDataArray,d=b.searchTextRe;if(!a||!a.length)return null;var c=b.dataSectionJson.stack[0],k=c.data.data[0],g=c.data.data[1],e={numAttributesTotal:0,numAttributesShown:0,
ranges:{}},l;b.filterRanges&&(l={},b.filterRanges.forEach(function(a){l[a.fieldName]=a}));for(var z in k.fieldInfos){var m=k.fieldInfos[z];t.isNumericField(m)&&(e.ranges[m.name]={fieldName:m.name,alias:m.alias,min:Infinity,max:-Infinity,sumTotal:0,sumShown:0,decimals:m.decimals,dataArray:[]})}var p=[];a.forEach(function(a,w){var n={style:null,fieldInfos:{}};e.numAttributesTotal++;var f=!1,v=!1,m=!1;c.data.columns.forEach(function(b){var c=k.fieldInfos[b.field],h=a[c.name];if(u(c,h)){var g=e.ranges[c.name];
g.min=Math.min(g.min,h);g.max=Math.max(g.max,h);g.dataArray.push(h)}void 0===h||"string"===typeof h?n[b.field]=h||"":(n[b.field]=y.formatNumber(h,c),q.setNumericDataValue(h,n,b.field));n.__attributeIndex=w;(b=l&&l[c.name])&&(h<b.min||h>b.max)&&(f=!0);d&&"string"===typeof h&&(v=!0,d.test(h)&&(m=!0))});var g=f||v&&!m;g||(p.push(n),e.numAttributesShown++);c.data.columns.forEach(function(b){var c=k.fieldInfos[b.field];b=a[c.name];u(c,b)&&(c=e.ranges[c.name],c.sumTotal+=b,g||(c.sumShown+=b))});b.setAttributeVisibleAt&&
b.setAttributeVisibleAt(w,!g)});b.sorting&&p.sort(function(a,c){var d=q.getNumericDataValue(a,b.sorting.field),d=void 0!==d?d:a[b.sorting.field];a=q.getNumericDataValue(c,b.sorting.field);a=void 0!==a?a:c[b.sorting.field];c="number"===typeof d?d-a:d.localeCompare(a);return"desc"===b.sorting.order?-c:c});p.forEach(function(a,b){a.style=f.clone((0!==b%2?g||k:k).style);a.style.height=k.style.height});e.ranges=Object.keys(e.ranges).map(function(a){return e.ranges[a]});return{stats:e,gridDataObjects:p}},
getAttributeIndexForGridData:function(b){return b.__attributeIndex},_splitRowsByPages:function(b,a){var d=c._getHeaderHeight(a),f=c._getDataRowHeight(a),k=c._getDataListHeight(b,a),g=[],e,l=0;b.forEach(function(a){e||(e=[],g.push(e),l+=d);e.push(a);l+=f;l+f>k&&(e=null,l=0)});return g},_getHeaderHeight:function(b){return b.scaleToFitHeight?b.minRowHeight:b.headerSectionJson?b.headerSectionJson.stack[0].data.data[0].style.height:0},_getDataRowHeight:function(b){return b.scaleToFitHeight?b.minRowHeight:
b.dataSectionJson.stack[0].data.data[0].style.height},_getDataListHeight:function(b,a){var d=c._getHeaderHeight(a),f=c._getDataRowHeight(a),k=a.height-(a.hasFooter?a.footerHeight:0)-(a.hasTitle?a.titleHeight:0);a=a.height-a.footerHeight-(a.hasTitle?a.titleHeight:0);return d+f*b.length<=k?k:a},_buildSectionJsonForPage:function(b,a){var d;a.headerSectionJson?(d=a.headerSectionJson.stack[0],d={id:"table",attributes:{},style:{width:a.width},data:{columns:f.clone(d.data.columns),data:[f.clone(d.data.data[0])].concat(f.clone(b))}}):
d={id:"table",attributes:{},style:{width:a.width},data:{columns:f.clone(a.dataSectionJson.stack[0].data.columns),data:f.clone(b)}};d.data.data.forEach(function(b,d){b.style.height=0===d&&a.headerSectionJson?c._getHeaderHeight(a):c._getDataRowHeight(a)});a.scaleToFitHeight&&(b=c._getDataListHeight(b,a),r.resizeTableJsonToFitHeight(d,b));r.resizeTableJsonToFitWidth(d,a.width);return{type:x.DETAILS,stack:[d]}}};return c});