// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var u=function(m,p){u=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(p,m){p.__proto__=m}||function(p,m){for(var u in m)m.hasOwnProperty(u)&&(p[u]=m[u])};return u(m,p)};return function(m,p){function w(){this.constructor=m}u(m,p);m.prototype=null===p?Object.create(p):(w.prototype=p.prototype,new w)}}(),__assign=this&&this.__assign||function(){__assign=Object.assign||function(u){for(var m,p=1,w=arguments.length;p<w;p++){m=arguments[p];for(var x in m)Object.prototype.hasOwnProperty.call(m,
x)&&(u[x]=m[x])}return u};return __assign.apply(this,arguments)};
define("esri/arcade/featureset/sources/FeatureLayerDynamicMap","require exports ../../../graphic ../../../request ../../Attachment ../support/FeatureSet ../support/IdSet ../support/sha ../support/shared ../support/stats ../../polyfill/promiseUtils ../../../layers/FeatureLayer ../../../tasks/query ../../../tasks/QueryTask ../../../tasks/StatisticDefinition".split(" "),function(u,m,p,w,x,D,y,E,z,F,q,G,v,A,B){return function(m){function f(a){var c=m.call(this,a)||this;c.declaredClass="esri.layers.featureset.sources.FeatureLayerDynamic";
c._removeGeometry=!1;c._overrideFields=null;c.formulaCredential=null;c._pageJustIds=!1;c._requestStandardised=!1;a.spatialReference&&(c.spatialReference=a.spatialReference);c._transparent=!0;c._maxProcessing=1E3;c._layer=a.layer;c._wset=null;if(!1===c._layer.loaded)throw Error("Can only create FeatureSets from Loaded FeatureLayers. Use FeatureLayer or FeatureCollection classes");void 0!==a.outFields&&(c._overrideFields=a.outFields);void 0!==a.includeGeometry&&(c._removeGeometry=!1===a.includeGeometry);
return c}__extends(f,m);f.prototype._maxQueryRate=function(){return z.defaultMaxRecords};f.prototype.convertQueryToLruCacheKey=function(a){a=z.stableStringify(a.toJson());return(new E(a,"TEXT")).getHash("SHA-1","B64")};f.prototype.end=function(){return this._layer};f.prototype.load=function(){var a=this;null===this._loadPromise&&(this._loadPromise=q.create(function(c,e){a._initialiseFeatureSet();c(a)}));return this._loadPromise};f.prototype.optimisePagingFeatureQueries=function(a){this._pageJustIds=
a};f.prototype._initialiseFeatureSet=function(){if(!this._layer.getMap())throw Error("Can only use featuresets with layers attached to map");null==this.spatialReference&&(this.spatialReference=this._layer.getMap().spatialReference);this.geometryType=this._layer.geometryType;this.fields=this._layer.fields.slice(0);var a=this._layer.getOutFields();if(1!==a.length||"*"!==a[0]){for(var c=[],e=0,h=this.fields;e<h.length;e++){var g=h[e];if("esriFieldTypeOID"===g.type)c.push(g);else for(var b=0,l=a;b<l.length;b++){var d=
l[b];if(d.toLowerCase()===g.name.toLowerCase()){c.push(g);break}}}this.fields=c}if(null!==this._overrideFields)if(1===this._overrideFields.length&&"*"===this._overrideFields[0])this._overrideFields=null;else{c=[];a=[];e=0;for(h=this.fields;e<h.length;e++)if(g=h[e],"esriFieldTypeOID"===g.type)c.push(g),a.push(g.name);else for(b=0,l=this._overrideFields;b<l.length;b++)if(d=l[b],d.toLowerCase()===g.name.toLowerCase()){c.push(g);a.push(g.name);break}this.fields=c;this._overrideFields=a}this._layer&&(!0===
this._layer.useStandardizedQueries?this._databaseType=z.FeatureServiceDatabaseType.Standardised:(c=this._layer.version,void 0!==c&&null!==c&&10.5<=c&&(this._databaseType=z.FeatureServiceDatabaseType.Standardised,this._requestStandardised=!0)));this.objectIdField=this._layer.objectIdField;this.typeIdField=this._layer.typeIdField;this.types=this._layer.types};f.prototype._isInFeatureSet=function(a){return z.IdState.InFeatureSet};f.prototype._refineSetBlock=function(a,c){return q.resolve(a)};f.prototype._candidateIdTransform=
function(a){return a};f.prototype._transformSetWithIdChanges=function(a){};f.prototype._getSet=function(a){var c=this;return null===this._wset?this._ensureLoaded().then(function(){return c._getFilteredSet("",null,null,null,a)}).then(function(a){return c._wset=a}):q.resolve(this._wset)};f.prototype._runDatabaseProbe=function(a){var c=this;return q.create(function(e,h){try{c._ensureLoaded().then(function(){try{var g=new v;g.where=a.replace("OBJECTID",c._layer.objectIdField);c.executeQuery(g,"executeForIds").then(function(a){e(!0)},
function(a){try{e(!1)}catch(l){h(l)}})}catch(b){h(b)}})}catch(g){h(g)}})};f.prototype.pbfSupportedForQuery=function(a){return this._layer._canFetchPBFForQuery(a)};f.prototype.executeQuery=function(a,c){var e=new A(this._layerUrl()),h="execute"===c&&this.pbfSupportedForQuery(a);h&&(a.quantizationParameters={mode:"edit"});var g=null;if(this.recentlyUsedQueries){var b=this.convertQueryToLruCacheKey(a);(g=this.recentlyUsedQueries.getFromCache(b))&&g.isRejected()&&(g=null,this.recentlyUsedQueries.removeFromCache(b));
null===g&&(g=!0!==h?e[c](a):e[c](a,null,null,{format:"pbf"}),this.recentlyUsedQueries.addToCache(b,g))}null===g&&(g=!0!==h?e[c](a):e[c](a,null,null,{format:"pbf"}));return g};f.prototype._canUsePagination=function(){return void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsPagination?!0:!1};f.prototype._cacheableFeatureSetSourceKey=function(){return this._layer.url};f.prototype._getFilteredSet=function(a,
c,e,h,g){var b=this;return this.databaseType().then(function(l){if(b.isTable()&&c&&null!==a&&""!==a)return new y([],[],!0,null);if(b._canUsePagination())return b._getFilteredSetUsingPaging(a,c,e,h,g);var d="",f=!1;null!==h&&void 0!==b._layer.advancedQueryCapabilities&&null!==b._layer.advancedQueryCapabilities&&!0===b._layer.advancedQueryCapabilities.supportsOrderBy&&(d=h.constructClause(),f=!0);var k=new v;b._requestStandardised&&(k.sqlFormat="standard");k.where=null===e?null===c?"1\x3d1":"":e.toWhereClause(l);
k.spatialRelationship=b._makeRelationshipEnum(a);k.outSpatialReference=b.spatialReference;k.orderByFields=""!==d?d.split(","):null;k.geometry=null===c?"":c;k.relationParam=b._makeRelationshipParam(a);return b.executeQuery(k,"executeForIds").then(function(a){null===a&&(a=[]);b._checkCancelled(g);return new y([],a,f,null)})})};f.prototype._expandPagedSet=function(a,c,e,h,g){return this._expandPagedSetFeatureSet(a,c,e,h,g)};f.prototype._getFilteredSetUsingPaging=function(a,c,e,h,g){var b=this;try{var l=
"",d=!1;null!==h&&void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsOrderBy&&(l=h.constructClause(),d=!0);return this.databaseType().then(function(h){h=null===e?null===c?"1\x3d1":"":e.toWhereClause(h);b._layer.getDefinitionExpression()&&(h=""!==h?"(("+b._layer.getDefinitionExpression()+") AND ("+h+"))":b._layer.getDefinitionExpression());var k=b._maxQueryRate();void 0!==b._layer.maxRecordCount&&b._layer.maxRecordCount<
k&&(k=b._layer.maxRecordCount);var f=null;if(!0===b._pageJustIds)f=new y([],["GETPAGES"],d,{spatialRel:b._makeRelationshipEnum(a),relationParam:b._makeRelationshipParam(a),outFields:b._layer.objectIdField,resultRecordCount:k,resultOffset:0,geometry:null===c?"":c,where:h,orderByFields:l,returnGeometry:"false",returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}});else{var t=!0;!0===b._removeGeometry&&(t=!1);var r=null!==b._overrideFields?b._overrideFields:b._fieldsIncludingObjectId(b._layer.getOutFields()),
f=new y([],["GETPAGES"],d,{spatialRel:b._makeRelationshipEnum(a),relationParam:b._makeRelationshipParam(a),outFields:r.join(","),resultRecordCount:k,resultOffset:0,geometry:null===c?"":c,where:h,orderByFields:l,returnGeometry:t,returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}})}return b._expandPagedSet(f,k,0,1,g).then(function(a){return f})})}catch(t){return q.reject(t)}};f.prototype._clonePageDefinition=function(a){return null===a?null:!0!==a.groupbypage?{groupbypage:!1,spatialRel:a.spatialRel,
relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,resultOffset:a.resultOffset,geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}:{groupbypage:!0,spatialRel:a.spatialRel,relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,useOIDpagination:a.useOIDpagination,generatedOid:a.generatedOid,groupByFieldsForStatistics:a.groupByFieldsForStatistics,
resultOffset:a.resultOffset,outStatistics:a.outStatistics,geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}};f.prototype._getPhysicalPage=function(a,c,e){var h=this;try{var g=a.pagesDefinition.internal.lastRetrieved,b=new v;this._requestStandardised&&(b.sqlFormat="standard");b.spatialRelationship=a.pagesDefinition.spatialRel;b.relationParam=a.pagesDefinition.relationParam;b.outFields=a.pagesDefinition.outFields.split(",");
b.num=a.pagesDefinition.resultRecordCount;b.start=a.pagesDefinition.internal.lastRetrieved;b.geometry=a.pagesDefinition.geometry;b.where=a.pagesDefinition.where;b.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;b.returnGeometry=a.pagesDefinition.returnGeometry;b.outSpatialReference=this.spatialReference;return this.executeQuery(b,"execute").then(function(b){h._checkCancelled(e);if(a.pagesDefinition.internal.lastRetrieved!==g)return"done";for(var d=
0;d<b.features.length;d++)void 0===b.features[d].geometry&&(b.features[d].geometry=null),a.pagesDefinition.internal.set[g+d]=b.features[d].attributes[h._layer.objectIdField];if(!1===h._pageJustIds)for(d=0;d<b.features.length;d++)h._featureCache[b.features[d].attributes[h._layer.objectIdField]]=b.features[d];b.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=g+a.pagesDefinition.resultRecordCount;return"done"})}catch(l){return q.reject(l)}};
f.prototype._fieldsIncludingObjectId=function(a){if(null===a)return[this.objectIdField];a=a.slice(0);if(-1<a.indexOf("*"))return a;for(var c=!1,e=0;e<a.length;e++)if(a[e].toUpperCase()===this.objectIdField.toUpperCase()){c=!0;break}!1===c&&a.push(this.objectIdField);return a};f.prototype._getFeatures=function(a,c,e,h){var g=this,b=[];try{-1!==c&&void 0===this._featureCache[c]&&b.push(c);if(!0===this._checkIfNeedToExpandKnownPage(a,this._maxProcessingRate(),h))return this._expandPagedSet(a,this._maxProcessingRate(),
0,0,h).then(function(b){return g._getFeatures(a,c,e,h)});for(var l=0,d=a._lastFetchedIndex;d<a._known.length;d++){a._lastFetchedIndex+=1;l++;if(void 0===this._featureCache[a._known[d]]){var f=!1;if(null!==this._layer._mode&&void 0!==this._layer._mode){var k=this._layer._mode;if(void 0!==k._featureMap[a._known[d]]){var C=k._featureMap[a._known[d]];null!==C&&(f=!0,this._featureCache[a._known[d]]=C)}}if(!1===f&&(a._known[d]!==c&&b.push(a._known[d]),b.length>=this._maxProcessingRate()-1))break}if(l>=
e&&0===b.length)break}if(0===b.length)return q.resolve("success");try{var n=new v;this._requestStandardised&&(n.sqlFormat="standard");n.objectIds=b;n.outFields=null!==this._overrideFields?this._overrideFields:this._fieldsIncludingObjectId(this._layer.getOutFields());n.returnGeometry=!0;!0===this._removeGeometry&&(n.returnGeometry=!1);n.outSpatialReference=this.spatialReference;return this.executeQuery(n,"execute").then(function(a){g._checkCancelled(h);if(void 0!==a.error)return q.reject(Error(a.error));
for(var b=0;b<a.features.length;b++)void 0===a.features[b].geometry&&(a.features[b].geometry=null),g._featureCache[a.features[b].attributes[g._layer.objectIdField]]=a.features[b];return"success"})}catch(r){return q.reject(r)}}catch(r){return q.reject(r)}};f.prototype._layerUrl=function(){return this._layer.url};f.prototype._getDistinctPages=function(a,c,e,h,g,b,l,d,f){var k=this;return this._ensureLoaded().then(function(){for(var t=e.parseTree.column,n=0;n<k._layer.fields.length;n++)if(k._layer.fields[n].name.toLowerCase()===
t.toLowerCase()){t=k._layer.fields[n].name;break}return k.databaseType().then(function(r){var n=new v;k._requestStandardised&&(n.sqlFormat="standard");r=null===b?null===g?"1\x3d1":"":b.toWhereClause(r);k._layer.getDefinitionExpression()&&(r=""!==r?"(("+k._layer.getDefinitionExpression()+") AND ("+r+"))":k._layer.getDefinitionExpression());n.where=r;n.spatialRelationship=k._makeRelationshipEnum(h);n.relationParam=k._makeRelationshipParam(h);n.geometry=null===g?null:g;n.returnDistinctValues=!0;n.returnGeometry=
!1;n.outFields=[t];return k.executeQuery(n,"execute").then(function(n){k._checkCancelled(f);if(!n.hasOwnProperty("features"))return q.reject(Error("Unnexected Result querying statistics from layer"));for(var r=!1,m=0;m<k._layer.fields.length;m++)if(k._layer.fields[m].name===t){"esriFieldTypeDate"===k._layer.fields[m].type&&(r=!0);break}for(m=0;m<n.features.length;m++){if(r){var p=n.features[m].attributes[t];null!==p?d.push(new Date(p)):d.push(p)}else d.push(n.features[m].attributes[t]);if(d.length>=
l)break}return 0===n.features.length?d:n.features.length===k._layer.maxRecordCount&&d.length<l?k._getDistinctPages(a+n.features.length,c,e,h,g,b,l,d,f).then(function(a){return{calculated:!0,result:a}}):d})})})};f.prototype._distinctStat=function(a,c,e,h,g,b,l){return this._getDistinctPages(0,a,c,e,h,g,b,[],l).then(function(a){return{calculated:!0,result:a}})};f.prototype.isTable=function(){return!1};f.prototype._countstat=function(a,c,e,h,g){var b=this;return this.databaseType().then(function(a){var d=
new v;b._requestStandardised&&(d.sqlFormat="standard");if(b.isTable()&&e&&null!==c&&""!==c)return{calculated:!0,result:0};a=null===h?null===e?"1\x3d1":"":h.toWhereClause(a);b._layer.getDefinitionExpression()&&(a=""!==a?"(("+b._layer.getDefinitionExpression()+") AND ("+a+"))":b._layer.getDefinitionExpression());d.where=a;d.where=a;d.spatialRelationship=b._makeRelationshipEnum(c);d.relationParam=b._makeRelationshipParam(c);d.geometry=null===e?null:e;d.returnGeometry=!1;new A(b._layerUrl());return b.executeQuery(d,
"executeForCount").then(function(a){return{calculated:!0,result:a}})})};f.prototype._stats=function(a,c,e,h,g,b,l){var d=this;return this._ensureLoaded().then(function(){var f=d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsSqlExpression,k=d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsStatistics,m=d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsDistinct;return"count"===a?m?d._countstat(a,
e,h,g,l):{calculated:!1}:!1===k||!1===c.isSingleField()&&!1===f||!1===c.isStandardized()?""!==e||null!==g?{calculated:!1}:d._manualStat(a,c,b,l):"distinct"===a?!1===m?""!==e||null!==g?{calculated:!1}:d._manualStat(a,c,b,l):d._distinctStat(a,c,e,h,g,b,l):d.databaseType().then(function(b){if(d.isTable()&&h&&null!==e&&""!==e)return{calculated:!0,result:null};var k=new v;d._requestStandardised&&(k.sqlFormat="standard");var l=null===g?null===h?"1\x3d1":"":g.toWhereClause(b);d._layer.getDefinitionExpression()&&
(l=""!==l?"(("+d._layer.getDefinitionExpression()+") AND ("+l+"))":d._layer.getDefinitionExpression());k.where=l;k.spatialRelationship=d._makeRelationshipEnum(e);k.relationParam=d._makeRelationshipParam(e);k.geometry=null===h?null:h;l=new B;l.statisticType=F.decodeStatType(a);l.onStatisticField=c.toWhereClause(b);var f=l.outStatisticFieldName="ARCADE_STAT_RESULT";k.returnGeometry=!1;k.outStatistics=[l];return d.executeQuery(k,"execute").then(function(a){if(!a.hasOwnProperty("features")||0===a.features.length)return q.reject(Error("Unnexected Result querying statistics from layer"));
for(var b=!1,c=0;c<a.fields.length;c++)if("ARCADE_STAT_RESULT"===a.fields[c].name.toUpperCase()){f=a.fields[c].name;"esriFieldTypeDate"===a.fields[c].type&&(b=!0);break}return b?(b=a.features[0].attributes[f],null!==b&&(b=new Date(a.features[0].attributes[f])),{calculated:!0,result:b}):{calculated:!0,result:a.features[0].attributes[f]}})})})};f.prototype._stat=function(a,c,e,h,g,b,l){return this._stats(a,c,e,h,g,b,l)};f.prototype._canDoAggregates=function(a,c,e,h,g){var b=this;return this._ensureLoaded().then(function(a){a=
!1;var d=b._layer.advancedQueryCapabilities&&!0===b._layer.advancedQueryCapabilities.supportsSqlExpression;void 0!==b._layer.advancedQueryCapabilities&&null!==b._layer.advancedQueryCapabilities&&!0===b._layer.advancedQueryCapabilities.supportsStatistics&&!0===b._layer.advancedQueryCapabilities.supportsOrderBy&&(a=!0);if(a)for(var e=0;e<c.length-1;e++)null!==c[e].workingexpr&&(!1===c[e].workingexpr.isStandardized()?a=!1:!1===c[e].workingexpr.isSingleField()&&!1===d&&(a=!1));return!1===a?!1:!0})};f.prototype._makeRelationshipEnum=
function(a){return 0<=a.indexOf("esriSpatialRelRelation")?"esriSpatialRelRelation":a};f.prototype._makeRelationshipParam=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?a.split(":")[1]:""};f.prototype._getAggregatePagesDataSourceDefinition=function(a,c,e,h,g,b,l){var d=this;return this._ensureLoaded().then(function(f){return d.databaseType().then(function(k){var f="",n=!1,m=!1;null!==b&&void 0!==d._layer.advancedQueryCapabilities&&null!==d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsOrderBy&&
(f=b.constructClause(),m=!0);void 0!==d._layer.advancedQueryCapabilities&&null!==d._layer.advancedQueryCapabilities&&!1===d._layer.advancedQueryCapabilities.supportsPagination&&(m=!1,n=!0,f=d._layer.objectIdField);for(var t=[],p=0;p<c.length;p++){var q=new B;q.onStatisticField=null!==c[p].workingexpr?c[p].workingexpr.toWhereClause(k):"";q.outStatisticFieldName=c[p].field;q.statisticType=c[p].toStatisticsName();t.push(q)}""===f&&(f=a.join(","));p=d._maxQueryRate();void 0!==d._layer.maxRecordCount&&
d._layer.maxRecordCount<p&&(p=d._layer.maxRecordCount);k=null===g?null===h?"1\x3d1":"":g.toWhereClause(k);d._layer.getDefinitionExpression()&&(k=""!==k?"(("+d._layer.getDefinitionExpression()+") AND ("+k+"))":d._layer.getDefinitionExpression());return new y([],["GETPAGES"],m,{groupbypage:!0,spatialRel:d._makeRelationshipEnum(e),relationParam:d._makeRelationshipParam(e),outFields:["*"],useOIDpagination:n,generatedOid:l,resultRecordCount:p,resultOffset:0,groupByFieldsForStatistics:a,outStatistics:t,
geometry:null===h?null:h,where:k,orderByFields:f,returnGeometry:!1,returnIdsOnly:!1,internal:{lastMaxId:-1,set:[],lastRetrieved:0,fullyResolved:!1}})})})};f.prototype._getAgregagtePhysicalPage=function(a,c,e){var f=this;try{var g=a.pagesDefinition.where;!0===a.pagesDefinition.useOIDpagination&&(g=""!==g?"("+g+") AND ("+a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString()+")":a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString());var b=
a.pagesDefinition.internal.lastRetrieved,l=new v;this._requestStandardised&&(l.sqlFormat="standard");l.where=g;l.spatialRelationship=a.pagesDefinition.spatialRel;l.relationParam=a.pagesDefinition.relationParam;l.outFields=a.pagesDefinition.outFields;l.outStatistics=a.pagesDefinition.outStatistics;l.geometry=a.pagesDefinition.geometry;l.groupByFieldsForStatistics=a.pagesDefinition.groupByFieldsForStatistics;l.num=a.pagesDefinition.resultRecordCount;l.start=a.pagesDefinition.internal.lastRetrieved;
l.returnGeometry=a.pagesDefinition.returnGeometry;l.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;return this.isTable()&&l.geometry&&l.spatialRelationship?q.resolve([]):this.executeQuery(l,"execute").then(function(c){f._checkCancelled(e);if(!c.hasOwnProperty("features"))return q.reject(Error("Unnexected Result querying aggregates from layer"));var d=[];if(a.pagesDefinition.internal.lastRetrieved!==b)return[];for(var k=0;k<c.features.length;k++)void 0===
c.features[k].geometry&&(c.features[k].geometry=null),a.pagesDefinition.internal.set[b+k]=c.features[k].attributes[a.pagesDefinition.generatedOid];for(k=0;k<c.features.length;k++)d.push(new p({attributes:c.features[k].attributes,geometry:null}));!0===a.pagesDefinition.useOIDpagination?0===c.features.length?a.pagesDefinition.internal.fullyResolved=!0:a.pagesDefinition.internal.lastMaxId=c.features[c.features.length-1].attributes[a.pagesDefinition.generatedOid]:c.features.length!==a.pagesDefinition.resultRecordCount&&
(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=b+a.pagesDefinition.resultRecordCount;return d})}catch(d){return q.reject(d)}};f.create=function(a,c,e){a=new G({url:a,outFields:null===c?["*"]:c});return new f({layer:a,spatialReference:e})};f.prototype.canBeBigDataFeatureSet=function(){return!0};f.prototype.shouldBeResolvedAsBigData=function(){return!1};f.prototype.expressAsArcadeScriptImpl=function(a,c,e){this.arcadeAssignNextScriptStepIdentifiers(e);a=this.arcadeAssignNextGlobalIdentifier(e);
c[a]={name:a,type:"FeatureLayer",params:{url:this._layer.url,definitionExpression:this._layer.getDefinitionExpression(),fields:this._layer.getOutFields()}};e.featuresetsyms.push(a);return""};f.prototype._queryAttachments=function(a){var c=this,e=__assign({},a,{f:"json"});0<e.objectIds.length&&(e.objectIds=e.objectIds.join(","));e.size&&(e.size=e.size.join(","));e.attachmentTypes&&(e.attachmentTypes=e.attachmentTypes.join(","));return q.create(function(a,f){w({url:c._layer._url.path+"/queryAttachments",
content:e,callbackParamName:"callback",load:function(b){var c={};if(b&&b.attachmentGroups){var d=0;for(b=b.attachmentGroups;d<b.length;d++){var e=b[d];void 0===c[e.parentObjectId]&&(c[e.parentObjectId]=[]);for(var f=0,g=e.attachmentInfos;f<g.length;f++){var h=g[f];c[e.parentObjectId].push({id:h.id,globalId:h.globalId,name:h.name,contentType:h.contentType,size:h.size})}}}a(c)},error:function(a){f(a)}})})};f.prototype.queryAttachments=function(a,c,e,f){var g=this;if(this._layer.hasAttachments){var b=
{objectIds:[a]};if(c&&0<c||e&&0<e)b.size=[c&&0<c?c:0,e&&0<e?e:c+1];f&&0<f.length&&(b.attachmentTypes=f);return this._queryAttachments(b).then(function(b){var c=[];if(b&&b[a]){var e=g._layer._url.path;b[a].forEach(function(b){c.push(new x(b.id,b.name,b.contentType,b.size,e+"/"+a.toString()+"/attachments/"+b.id.toString()))})}return c})}return q.resolve([])};return f}(D)});