// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/locator/LocatorTableInfographic","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/when dojo/string dojo/dom-construct ../paginatableTable/PaginatableTableInfographic ../paginatableTable/SectionJsonsBuilder ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ../../supportClasses/tableJson/TableJsonUtil ../../supportClasses/ViewModes ../../sections/sectionUtils/SectionJsonUtil ../utils/InfographicJsonUtil ./ExportToExcelUtil ./SummaryFooterSectionJsonBuilder esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/FieldUtil esri/dijit/geoenrichment/utils/InvokeUtil esri/dijit/geoenrichment/utils/RegExpUtil esri/dijit/geoenrichment/utils/WaitingUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(g,h,f,u,k,l,m,v,w,n,r,x,y,z,A,p,B,q,C,D,e){e=e.geoenrichment.dijit.ReportPlayer.LocatorTableInfographic;g=g(l,{noDataText:e.noLocatorData,_locatorPointsController:null,_areaName:null,_areaShortName:null,_stats:null,_unitedSectionJson:null,_summarySection:null,_summaryFooterSection:null,updateInfographic:function(a){if(this.domNode)return a.locatorCalculatorInfo&&this.viewModel.dynamicReportInfo&&(this.viewModel.dynamicReportInfo.isMultiFeature?(this._areaName=this.viewModel.dynamicReportInfo.combinedAreasInfo.name,
this._areaShortName=this.viewModel.dynamicReportInfo.combinedAreasInfo.shortName):(this._areaName=this.viewModel.dynamicReportInfo.analysisAreas[this.currentFeatureIndex].name,this._areaShortName=this.viewModel.dynamicReportInfo.analysisAreas[this.currentFeatureIndex].shortName),this._locatorPointsController=this.viewModel.getLocatorPointsController(a.locatorCalculatorInfo,this.currentFeatureIndex),this.own(this._locatorPointsController)),this._summaryFields=a.summaryFooterFields,this.inherited(arguments)},
_doUpdateContent:function(){this.domNode&&this.width&&(this.inherited(arguments),this._registerLocatorPointsController())},_buildSectionJsonsAndStat:function(){var a=this,b=m.buildSectionJsonsAndStat({headerSectionJson:this._currentInfographicJson.headerSectionJson,dataSectionJson:this._currentInfographicJson.dataSectionJson,calculatorDataArray:this._getCalculatorDataArray(),filterRanges:this._filterRanges,searchTextRe:this._searchTextRe,sorting:this._sorting,minRowHeight:this.minRowHeight,scaleToFitHeight:this._currentInfographicJson.scaleToFitHeight,
height:this.height,width:this.width,hasTitle:!!this._currentInfographicJson.titleSectionJson,titleHeight:this._getTitleHeight(),hasFooter:this._currentInfographicJson.showNumberOfLocations,footerHeight:l.BOTTOM_AREA_HEIGHT+this._getSummaryFooterHeight(),setAttributeVisibleAt:function(b,d){a._isDataDrillingView()||a._locatorPointsController&&a._locatorPointsController.setPointVisibleAt(b,d)}});this._stats=b&&b.stats;this._unitedSectionJson=b&&b.unitedSectionJson;return b},_resizeSection:function(a){this.isEditMode&&
this.inherited(arguments);var b=a.getTables()[0];this._isDataDrillingView()||this._locatorPointsController&&this._locatorPointsController.registerLocatorTable(b)},_getCalculatorDataArray:function(){return this._locatorPointsController.getCalculatorDataArray()},_renderParts:function(a){var b=this._currentInfographicJson.showAsSummary;p[b?"hide":"show"]([this.paginationDiv,this.summaryFooterDiv,this.pageNavigatorDiv,this.footnoteDiv]);p[b?"show":"hide"]([this.summaryDiv]);this.footnoteDiv.innerHTML=
"";b?(this._renderTitleSection(),this._renderSummarySection()):(this.inherited(arguments),this._renderSummaryFooterSection())},_renderFootNote:function(){var a=this.getNumPointsShown();this.footnoteDiv.innerHTML=this._currentInfographicJson.showNumberOfLocations&&a?1===a?e.oneClosestLocations:u.substitute(e.numClosestLocations,{numPoints:a}):"";this.footnoteDiv.style.color=this.viewModel.getDocumentDefaultStyles(this.theme).color},_getFooterHeight:function(){return(!this._isSinglePage||this._currentInfographicJson.showNumberOfLocations?
l.BOTTOM_AREA_HEIGHT:0)+this._getSummaryFooterHeight()},_getSummaryFooterHeight:function(){return this._summaryFields?2*this.minRowHeight:0},_renderSummaryFooterSection:function(){var a=this;if(this._summaryFields){p.show(this.summaryFooterDiv);var b={};b.initialWidth=this._getPageWidth();b.json=this._currentInfographicJson.summaryFooterSectionJson||z.buildSummaryFooterSectionJson(this._currentInfographicJson);b.viewModel=this.viewModel;b.theme=this.theme;b.parentWidget=this;b.noContentOffset=!0;
b.tableParams={trimTextIfOverflows:!0,hasResizableColumns:!1,disableResizableColumnsAutoDetection:!0};b.initialViewMode=this.isEditMode?n.EDIT:n.PREVIEW_VALUES;b.getPreviewValueFunction=function(){var b={};a._summaryFields.forEach(function(c){a._stats.ranges.some(function(a){if(a.fieldName===c)return b[c]={number:a&&a.sumShown||0},!0})});return{formattedValue:"",fields:b}};this._columnWidths&&this._columnWidths.forEach(function(a,c){b.json.stack[0].data.columns[c].style.width=a});h.mixin(b,this._prepareSummaryFooterSectionCreationParams());
this.summaryFooterDiv||(this.summaryFooterDiv=k.create("div",{"class":"esriGEAbsoluteStretched locatorTableInfographic_summaryFooterDiv"},this.dataDiv),this.summaryFooterDiv.style.borderTop="1px solid "+A.getCSSColorWithAlpha(this.viewModel.getDocumentDefaultStyles(this.theme).color,.5),this.summaryFooterLabelDiv=k.create("div",{"class":"esriGEAbsoluteStretched",innerHTML:e.summaryInTable},this.summaryFooterDiv),this.summaryFooterLabelDiv.style.color=this.viewModel.getDocumentDefaultStyles(this.theme).color,
this.summaryFooterSectionDiv=k.create("div",{"class":"esriGEAbsoluteStretched"},this.summaryFooterDiv));this.summaryFooterDiv.style.top="auto";this.summaryFooterDiv.style.bottom=this._getFooterHeight()-this._getSummaryFooterHeight()+"px";this.summaryFooterDiv.style.height=this._getSummaryFooterHeight()+"px";this.summaryFooterLabelDiv.style.bottom="auto";this.summaryFooterLabelDiv.style.height=this.summaryFooterLabelDiv.style.lineHeight=this._getSummaryFooterHeight()/2+"px";this.summaryFooterSectionDiv.style.top=
"auto";this.summaryFooterSectionDiv.style.height=this._getSummaryFooterHeight()/2+"px";var c=this.viewModel.layoutBuilder.createElement("section",b,this.summaryFooterSectionDiv);c.setHeight(this._getSummaryFooterHeight()/2);c.setWidth(this._getPageWidth());c.fitContentNicely();this._summaryFooterSection=c}else p.hide(this.summaryFooterDiv)},_prepareSummaryFooterSectionCreationParams:function(){return null},_onColumnWidthsChanged:function(){this._columnWidths&&this._summaryFooterSection&&(table=this._summaryFooterSection.getTables()[0],
this._columnWidths.forEach(function(a,b){table.columns[b].style.width=a}),table.refresh())},_renderSummarySection:function(){var a=this;if(this._currentInfographicJson.summarySectionJson){var b={};b.initialWidth=this._getPageWidth();b.json=this._provideDataDrillingForSummarySectionJson();b.viewModel=this.viewModel;b.theme=this.theme;b.parentWidget=this;b.noContentOffset=!0;b.tableParams={trimTextIfOverflows:!0};b.initialViewMode=this.isEditMode?n.EDIT:n.PREVIEW_VALUES;b.getPreviewValueFunction=function(){var b,
d=a.getNumPointsShown(),t=a._currentInfographicJson.summarizeField;t?(b=(b=a._stats.ranges.filter(function(a){return a.fieldName===t})[0])&&b.sumShown||0,a._currentInfographicJson.summarizeByAverage&&d&&(b/=d)):b=d;return{number:b}};h.mixin(b,this._prepareSummarySectionCreationParams());this.summaryDiv=this.summaryDiv||k.create("div",{"class":"esriGEAbsoluteStretched"},this.dataDiv);this.summaryDiv.style.top=this._getTitleHeight()+"px";b=this.viewModel.layoutBuilder.createElement("section",b,this.summaryDiv);
b.setHeight(this.height-this._getTitleHeight());b.setWidth(this._getPageWidth());b.fitContentNicely();this._summarySection=b}},_prepareSummarySectionCreationParams:function(){return null},_provideDataDrillingForSummarySectionJson:function(){var a=r.getSectionJsonInfographic(this._currentInfographicJson.summarySectionJson);delete a.dataDrilling;var b=h.clone(this._currentInfographicJson);b.showAsSummary=!1;b=w.createSingleCellTable({width:this.width,height:this.height,fieldInfo:v.createFieldInfoFromInfographic(b)});
b=r.wrapInDetailsSectionJson(b);x.setDataDrilling(a,a.variableTables[0].variable.fieldInfo.templateName,{sectionJson:b});return this._currentInfographicJson.summarySectionJson},_registerLocatorPointsController:function(){this._locatorPointsController&&this._locatorPointsController.setLocatorTableCallbacks({getCellForPointAtFunc:this._getCellForPointAt.bind(this),getPointIndexForCellFunc:this._getPointIndexForCellFunc.bind(this)})},_getPointIndexForCellFunc:function(a){return a&&m.getAttributeIndexForGridData(a.gridData)},
_getCellForPointAt:function(a){if(!this._currentInfographicJson.showAsSummary){var b=-1,c;this._sectionJsons.some(function(d,e){return d.stack[0].data.data.some(function(f){if(m.getAttributeIndexForGridData(f)===a)return b=e,c=d,!0})});if(-1!==b){this.pagination.set("currentPage",b,!0);var d;this._getSectionByJson(c).getTables()[0].getFieldCells().some(function(b){if(m.getAttributeIndexForGridData(b.gridData)===a)return d=b,!0});return d}}},_filterRanges:null,_searchText:null,_searchTextRe:null,getFilterRanges:function(){return f(this._updatePromise,
function(){return this._stats&&this._stats.ranges}.bind(this))},setFilterRanges:function(a){this._filterRanges=a;q.invoke(this,"_doUpdateContent",50)},setSearchText:function(a){this._searchTextRe=(this._searchText=a)&&C.createRegExp(a,"i",!0);q.invoke(this,"_doUpdateContent",50)},_summaryFields:null,getSummaryInfos:function(){var a=this;return f(this._updatePromise,function(){var b=!a._currentInfographicJson.showAsSummary&&a._stats&&a._stats.ranges;if(!b)return null;var c=[];b.forEach(function(b){B.isDistanceField(b.fieldName)||
c.push({fieldName:b.fieldName,label:b.alias,visible:a._summaryFields&&-1!==a._summaryFields.indexOf(b.fieldName)})});return c})},setVisibleSummaryFields:function(a){this._summaryFields=a&&a.length?a:null;q.invoke(this,"_doUpdateContent",50)},getNumPointsTotal:function(){return this._stats&&this._stats.numAttributesTotal||0},getNumPointsShown:function(){return this._stats&&this._stats.numAttributesShown||0},getVisualState:function(){return this._filterRanges||this._summaryFields||this._searchText||
this._sorting||this._columnWidths?{filterRanges:this._filterRanges,summaryFields:this._summaryFields,searchText:this._searchText,sorting:this._sorting,columnWidths:this._columnWidths}:null},setVisualState:function(a){a&&(a.filterRanges&&this.setFilterRanges(a.filterRanges),a.summaryFields&&this.setVisibleSummaryFields(a.summaryFields),a.searchText&&this.setSearchText(a.searchText),a.sorting&&this._setSorting(a.sorting),a.columnWidths&&(this._columnWidths=a.columnWidths,q.invoke(this,"_doUpdateContent",
50)))},canExportToExcel:function(){return!this._isDataDrillingView()&&this.viewModel.canExportToExcel()},exportToExcel:function(){var a=this;return f(this._updatePromise,function(){return f(a.viewModel.pepareExportToExcelParameters({layerID:a._locatorPointsController.getLayerID(),hasMaps:a._locatorPointsController.getMapInfos()&&a._locatorPointsController.getMapInfos().length}),function(b){return D.showProgressPromise(a.domNode,f(a.prepareExportToExcelParameters(b),function(b){return a.viewModel.exportToExcel(b)}))})})},
prepareExportToExcelParameters:function(a){a=a||{};return y.prepareExportParameters({areaName:this._areaName,areaShortName:this._areaShortName,layerName:this._locatorPointsController.getLayerName(),layerID:this._locatorPointsController.getLayerID(),sectionJson:this._unitedSectionJson,mapInfos:this._locatorPointsController.getMapInfos(),exportMaps:a.exportMaps})},toJson:function(){var a=h.clone(this._currentInfographicJson);a.summarySectionJson&&delete r.getSectionJsonInfographic(a.summarySectionJson).dataDrilling;
return a},_isDataDrillingView:function(){return this.parentWidget.parentWidget.parentWidget.parentWidget.isDataDrillingView},_destroySections:function(){this.inherited(arguments);this._stats=null;this._summaryFooterSection&&this._summaryFooterSection.destroy();this._summaryFooterSection=null;this._summarySection&&this._summarySection.destroy();this._summarySection=null}});g.MIN_ROW_HEIGHT=l.MIN_ROW_HEIGHT;return g});