// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var k=function(g,b){k=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,b){e.__proto__=b}||function(b,g){for(var e in g)g.hasOwnProperty(e)&&(b[e]=g[e])};return k(g,b)};return function(g,b){function e(){this.constructor=g}k(g,b);g.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}();
define("esri/arcade/featureset/actions/OrderBy","require exports ../support/FeatureSet ../support/IdSet ../support/OrderbyClause ../../polyfill/promiseUtils".split(" "),function(k,g,b,e,n,l){var m=function(b){function d(a){var c=b.call(this,a)||this;c._orderbyclause=null;c.declaredClass="esri.arcade.featureset.actions.OrderBy";c._maxProcessing=100;c._orderbyclause=a.orderbyclause;c._parent=a.parentfeatureset;return c}__extends(d,b);d.prototype._getSet=function(a){var c=this;return null===this._wset?
this._ensureLoaded().then(function(){return c._getFilteredSet("",null,null,c._orderbyclause,a)}).then(function(h){c._checkCancelled(a);c._wset=h;return c._wset}):l.resolve(this._wset)};d.prototype.manualOrderSet=function(a,c){var h=this;return this.getIdColumnDictionary(a,[],-1,c).then(function(a){h._orderbyclause.order(a);for(var c=new e([],[],!0,null),b=0;b<a.length;b++)c._known.push(a[b].id);return c})};d.prototype.getIdColumnDictionary=function(a,c,b,f){var e=this;if(b<a._known.length-1){var d=
this._maxQueryRate();return"GETPAGES"===a._known[b+1]?this._parent._expandPagedSet(a,d,0,0,f).then(function(d){return e.getIdColumnDictionary(a,c,b,f)}):this._parent._getFeature(a,a._known[b+1],f).then(function(d){b+=1;e._checkCancelled(f);c.push({id:a._known[b],feature:d});return e.getIdColumnDictionary(a,c,b,f)})}return 0<a._candidates.length?this._refineSetBlock(a,this._maxProcessingRate(),f).then(function(){e._checkCancelled(f);return e.getIdColumnDictionary(a,c,b,f)}):l.resolve(c)};d.prototype._isInFeatureSet=
function(a){return this._parent._isInFeatureSet(a)};d.prototype._getFeatures=function(a,c,b,e){return this._parent._getFeatures(a,c,b,e)};d.prototype._featureFromCache=function(a){if(void 0===this._featureCache[a]){var c=this._parent._featureFromCache(a);return void 0===c?void 0:null===c?null:this._featureCache[a]=c}return this._featureCache[a]};d.prototype._fetchAndRefineFeatures=function(a,c,b){return l.reject(Error("Fetch and Refine should not be called in this featureset"))};d.prototype._getFilteredSet=
function(a,c,b,d,g){var f=this;return this._ensureLoaded().then(function(){return f._parent._getFilteredSet(a,c,b,null===d?f._orderbyclause:d,g)}).then(function(a){f._checkCancelled(g);var d;d=new e(a._candidates.slice(0),a._known.slice(0),a._ordered,f._clonePageDefinition(a.pagesDefinition));var h=!0;0<a._candidates.length&&(h=!1);return!1===d._ordered?f.manualOrderSet(d,g).then(function(a){!1!==h||null===c&&null===b||(a=new e(a._candidates.slice(0).concat(a._known.slice(0)),[],a._ordered,f._clonePageDefinition(a.pagesDefinition)));
return a}):d})};d.prototype.arcadeScriptStep=function(a,c,b){a=this.arcadeAssignNextScriptStepIdentifiers(b);c=this._orderbyclause.constructClause();return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("orderby( "+a.currentFeatureSet+',"'+c+'")')+";"};return d}(b);b._featuresetFunctions.orderBy=function(b){return""===b?this:new m({parentfeatureset:this,orderbyclause:new n(b)})};return m});