// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/conversion/portalToEditorUtils/parsers/ChartConverterPtoE","dojo/_base/lang esri/dijit/geoenrichment/utils/ColorUtil esri/dijit/geoenrichment/utils/ImageUtil esri/dijit/geoenrichment/utils/JsonXmlConverter ../../../charts/utils/ChartJsonUtil ../../ConversionUtil esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ChartTypes esri/dijit/geoenrichment/ReportPlayer/core/charts/legends/ChartLegendTypes ./_FieldInfoBuilder dojo/i18n!esri/nls/jsapi".split(" "),
function(w,D,J,p,F,q,B,G,A,v){function c(a,c){a=Number(a);return isNaN(a)?void 0:c?c(a):a}function C(a,f){return c(a,1.7<=f.revisionVersion?q.ptToPx:null)}function f(a){return q.ptToPxObj(q.parseStyleString(a))}function K(a,c,e){return p.queryJson(a,"series").filter(function(a){return a.tags&&a.tags[0]&&"point"===a.tags[0].name}).map(function(d){if(!d.tags)return null;d.attributes=d.attributes||{};return{label:d.attributes.Text||"",color:n(d.attributes.color),thickness:d.attributes.thickness,points:d.tags.map(function(e,
h){e.attributes=e.attributes||{};var k=(a.attributes.type===B.GAUGE||a.attributes.type===B.WAFFLE)&&h===d.tags.length-1;if((h=(h=(h=e.tags&&e.tags[0])&&h.attributes&&h.attributes.f)&&A.getCalculatorOrScriptFieldInfo(h,c))||k){k&&(h=null);h&&h.isMissing&&(k=e.attributes.Text,!k&&c.variableProvider.isPlayerOnly&&(k=(k=c.variableProvider.toCalculator(h.templateName))&&k.variable.alias),h.alias=k?k+" ("+v.missingVariable+")":v.missingVariable);var k=(k=e.attributes.CaptionField)&&A.getCalculatorOrScriptFieldInfo(k,
c),f=p.queryJson(e,"pointIcon")[0],f=f&&c.parsers.getParser("field").parseField(f.tags[0],f,null,c);return F.createChartPoint(h,e.attributes.Text||"",n(e.attributes.color),f,k)}}).filter(function(a){return!!a})}}).filter(function(a){return a&&a.points&&!!a.points.length})}function H(a,f,e){var d={gridLines:a.gridlines,gridLinesCentered:a.gridlinesCentered,gridLinesOpacity:c(a.gridlinesOpacity),gridLinesColor:n(a.gridlinesColor),gridLinesThickness:C(a.gridlinesThickness,e),gridLinesStyle:a.gridlinesStyle,
gridStripes:a.gridStripes,gridStripesColor:n(a.gridStripesColor),gridStripesColorAlt:n(a.gridStripesColorAlt)};f&&w.mixin(d,{hideBaseLine:void 0!==a.baseLine?!a.baseLine:a.hideBaseLine,baseLineColor:n(a.baseLineColor),baseLineOpacity:c(a.baseLineOpacity),baseLineThickness:C(a.baseLineThickness,e),baseLineStyle:a.baseLineStyle,baseLineValue:c(a.baseLineValue)});return d}function L(a){var p=a.dataLabels,e=a.dataLabelsShowLabelUnder,d;d=a.CustomPercentFormat||a.CustomValueFormat;"string"!==typeof d?
d=0:(d=d.replace("%",""),d="0"===d?0:d.replace("0.","").length);return{dataLabels:p,dataLabelsShowLabelUnder:e,dataLabelsDecimals:d,dataLabelsStyle:f(a.dataLabelsStyle),dataLabelsLabelStyle:a.dataLabelsLabelStyle?f(a.dataLabelsLabelStyle):f(a.dataLabelsStyle),dataLabelsAltColor:n(a.dataLabelsAltColor),dataLabelsEnableAltColor:a.dataLabelsEnableAltColor,dataLabelsInside:a.dataLabelsInside,dataLabelsStackedInColumns:a.dataLabelsStackedInColumns,dataLabelsHorizontalAlign:a.dataLabelsHorizontalAlign,
dataLabelsVerticalAlign:a.dataLabelsVerticalAlign,dataLabelsShowValuePercentSymbol:a.dataLabelsShowValuePercentSymbol,dataLabelsShowValueCurrencySymbol:a.dataLabelsShowValueCurrencySymbol,dataLabelsAngle:c(a.dataLabelsAngle),dataLabelsMaxWidth:c(a.dataLabelsMaxWidth,q.ptToPx)}}function M(a){return(a=p.queryJson(a,"BackImage")[0])&&a.tags&&a.tags[0].text?J.base64DataToDataURL(a.tags[0].text):null}function n(a){a&&"string"===typeof a&&(a=6===a.length&&-1===a.indexOf("#")?"#"+a:D.toCSSColor(a));return a}
v=v.geoenrichment.dijit.ReportPlayer.ReportPlayer;return{portalToEditor:function(a,v,e){var d=p.queryJson(a,"comparisonInfo")[0],x;if(d){var h=d.attributes.name,k=e.templateJson.metadata.comparisonCalculatorsHash[h];k&&(x={calculatorName:h,chartType:d.attributes.chartType,color:d.attributes.color,lineThickness:C(d.attributes.lineThickness,e),lineStyle:d.attributes.lineStyle,lineMarker:d.attributes.lineMarker,levels:k.levels})}var z=K(a,e,x);if(!z.length)return null;var b=a.attributes,y=p.queryJson(a,
"chartTitle")[0],l=p.queryJson(a,"legend")[0],t=p.queryJson(a,"xAxis")[0],u=p.queryJson(a,"yAxis")[0],d=p.queryJson(a,"chartIcon"),d=p.queryJson(a,"chartIcon"),h=p.queryJson(a,"floatingIcon"),k=p.queryJson(a,"floatingText"),E=p.queryJson(a,"trigger");y.attributes=y.attributes||{};var r=t&&t.attributes,m=u&&u.attributes,A=r,I=m;e.isGraphicReport&&1.3>e.revisionVersion&&(A=m,I=r);z.forEach(function(a){a.thickness=c(a.thickness)});var g;B.isColumnBarLike(b.type)&&(g=1<z[0].thickness?"Large":1>z[0].thickness?
"Small":"Medium");var t=t&&t.tags&&t.tags[0].attributes&&t.tags[0].attributes,u=u&&u.tags&&u.tags[0].attributes&&u.tags[0].attributes,D=M(a);g={isChart:!0,type:b._type||b.type,isMultiFeatureChart:!!b.isMultiFeatureChart,seriesItems:z,visualProperties:w.mixin({width:q.ptToPx(b.width),height:q.ptToPx(b.height),backgroundColor:n(b.backColor),panelBackgroundColor:n(b.panelBackgroundColor),barBorders:b.barBorders,view3D:!!b.view3D,origin:c(b.origin),lineThickness:B.isLineLike(b.type)?C(z[0].thickness,
e):void 0,columnThickness:g,backgroundImageData:D,title:{text:y.attributes.text,align:y.attributes.align&&y.attributes.align.toLowerCase(),style:f(y.attributes.style),verticalShift:c(y.attributes.verticalShift,q.ptToPx)},xAxis:r&&w.mixin({show:"None"!==r.placement,hideLine:void 0!==r.line?!r.line:r.hideLine,showTicks:r.ticks,ticksInside:r.ticksInside||void 0,hideLabels:r.hideLabels||void 0,placement:"OtherSide"===r.placement?"OtherSide":void 0,title:t&&t.text,titleStyle:t&&f(t.style),style:f(r.style),
labelsAngle:c(r.labelsAngle),lineColor:n(r.lineColor)},H(A,!1,e)),yAxis:m&&w.mixin({show:"None"!==m.placement,hideLine:void 0!==m.line?!m.line:m.hideLine,showTicks:m.ticks,ticksInside:m.ticksInside,hideLabels:m.hideLabels||void 0,placement:"OtherSide"===m.placement?"OtherSide":void 0,title:u&&u.text,titleStyle:u&&f(u.style),style:f(m.style),labelsAngle:c(m.labelsAngle),lineColor:n(m.lineColor),showPercentSymbol:m.showPercentSymbol,showCurrencySymbol:m.showCurrencySymbol,showSymbolForAllLabels:m.showSymbolForAllLabels,
showValuesAsWeightsInSeries:m.showValuesAsWeightsInSeries},H(I,!0,e)),isStacked:b.isStacked,columnBarGap:c(b.columnBarGap,q.ptToPx),columnBarOpacity:c(b.columnBarOpacity),renderColumnBarsInOppositeDirections:b.renderColumnBarsInOppositeDirections,showColumnBarBackground:b.showColumnBarBackground,columnBarBackgroundColor:n(b.columnBarBackgroundColor),columnBarBackgroundOpacity:c(b.columnBarBackgroundOpacity),columnBarLineOpacity:c(b.columnBarLineOpacity),columnBarLineColor:n(b.columnBarLineColor),
columnBarLineThickness:c(b.columnBarLineThickness,q.ptToPx),columnBarLineStyle:b.columnBarLineStyle,fillLineArea:b.fillLineArea,lineAreaOpacity:b.lineAreaOpacity,donutHolePercent:c(b.donutHolePercent),donutGap:c(b.donutGap),donutArcPercent:c(b.donutArcPercent),gaugeHolePercent:c(b.gaugeHolePercent),gaugeRangeMin:c(b.gaugeRangeMin),gaugeRangeMax:c(b.gaugeRangeMax),gaugeGap:c(b.gaugeGap),gaugeStartAngle:c(b.gaugeStartAngle),gaugeArcPercent:c(b.gaugeArcPercent),gaugeLabelStyle:f(b.gaugeLabelStyle),gaugeLabelPlacement:b.gaugeLabelPlacement||
void 0,gaugeShowArrow:b.gaugeShowArrow||void 0,gaugeArrowLineColor:n(b.gaugeArrowLineColor),gaugeArrowFillColor:n(b.gaugeArrowFillColor),gaugeConditionalStylingOthers:void 0!==b.gaugeConditionalStylingIgnoreOthers?b.gaugeConditionalStylingIgnoreOthers:b.gaugeConditionalStylingOthers||void 0,gaugeConditionalStylingLabel:b.gaugeConditionalStylingLabel||void 0,gaugeShowFromToLabels:b.gaugeShowFromToLabels||void 0,gaugeFromLabelStyle:f(b.gaugeFromLabelStyle),gaugeToLabelStyle:f(b.gaugeToLabelStyle),waffleDirection:b.waffleDirection||
void 0,waffleShowWholePictures:b.waffleShowWholePictures||void 0,waffleRangeMin:c(b.waffleRangeMin),waffleRangeMax:c(b.waffleRangeMax),waffleLabelPlacement:b.waffleLabelPlacement||void 0,waffleLabelOffset:c(b.waffleLabelOffset,q.ptToPx),waffleHideValue:b.waffleHideValue||void 0,waffleHideLabel:b.waffleHideLabel||void 0,waffleShowLabelAbove:b.waffleShowLabelAbove||void 0,waffleValueStyle:f(b.waffleValueStyle),waffleLabelStyle:f(b.waffleLabelStyle),waffleColumnSpace:c(b.waffleColumnSpace,q.ptToPx),
waffleRowSpace:c(b.waffleRowSpace,q.ptToPx),waffleConditionalStylingOthers:void 0!==b.waffleConditionalStylingIgnoreOthers?b.waffleConditionalStylingIgnoreOthers:b.waffleConditionalStylingOthers||void 0,waffleConditionalStylingValue:b.waffleConditionalStylingValue||void 0,waffleConditionalStylingLabel:b.waffleConditionalStylingLabel||void 0,waffleNumIcons:c(b.waffleNumIcons),ringBackgroundColor:n(b.ringBackgroundColor),columnBarShowWholePictures:void 0!==b.showWholePictures?b.showWholePictures:b.columnBarShowWholePictures,
showAxisIcons:b.showAxisIcons,showChartIcons:b.showChartIcons,sorting:b.sorting},L(b))};l&&(l=l&&l.attributes||{},g.visualProperties.legend={type:l.type||G.SERIES},g.visualProperties.legend.type===G.MIN_MAX?w.mixin(g.visualProperties.legend,{minMax:{placement:l.placement,placementOffset:c(l.placementOffset),titleStyle:f(l.titleStyle),minVariableLabelStyle:f(l.minVariableLabelStyle),maxVariableLabelStyle:f(l.maxVariableLabelStyle)}}):w.mixin(g.visualProperties.legend,{series:{placement:l.placement,
placementOffset:c(l.placementOffset),hasBorder:l.hasBorder,labelParts:l.labelParts,style:f(l.style),symbol:l.symbol||void 0,hideOthers:l.hideOthers||void 0,showComparison:l.showComparison||void 0}}));1.2>e.revisionVersion&&(void 0!==g.visualProperties.donutGap&&(g.visualProperties.donutGap/=2*Math.PI),void 0!==g.visualProperties.gaugeGap&&(g.visualProperties.gaugeGap/=2*Math.PI));d&&d.length&&(g.visualProperties.chartIcons=d.map(function(a){return a.tags&&a.tags[0]?e.parsers.getParser("field").parseField(a.tags[0],
a,null,e):null}));h&&h.length&&(g.visualProperties.floatingIcons=h.map(function(a){return e.parsers.getParser("section").parseTable(a.tags[0],e)}));k&&k.length&&(g.visualProperties.floatingTexts=k.map(function(a){return e.parsers.getParser("section").parseTable(a.tags[0],e)}));E&&E.length&&(g.visualProperties.conditionalStyling=e.parsers.getParser("field").parseFieldTrigger(E[0]));g.comparisonInfo=x;x={};v.attributes&&v.attributes.style&&w.mixin(x,q.parseStyleString(v.attributes.style));q.ptToPxObj(x);
F.provideDefaultValueForMissing(g,{font:x});e.postProcessChartJson(a,g);return g}}});