// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/legends/SelectableLegend","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dijit/_WidgetBase dijit/_TemplatedMixin esri/dijit/geoenrichment/TriStateItem esri/dijit/geoenrichment/lists/FlowList ./ChartLegendSymbols ../utils/ThemeCalculator".split(" "),function(h,m,k,f,l,n,p,q,r,t,u,v,w){var x=h(null,{createPresentation:function(a,c,b,d,g){var h=this,e=f.create("div",{"class":"selectableLegendRoot "+
(this.isStacked()?"":"dijitInline")},b);e.style.paddingLeft=(this.isStacked()?3:10)+"px";e.style.paddingRight=(this.isStacked()?3:10)+"px";g=this.canSelect()&&new t(e,{"class":"dijitInline selectableLegendRootCheckbox"});d=f.create("div",{"class":"dijitInline selectableLegendRootColorRect "+this.getMarkerShape().toLowerCase()});a.fill&&(d.style.backgroundColor=a.fill);a.stroke&&(d.style.border="1px solid "+a.stroke);c=f.create("div",{innerHTML:a.label,"class":"dijitInline selectableLegendRootLabel TrimWithEllipses"});
if(b=a.valueText&&f.create("div",{innerHTML:this.isStacked()?a.valueText:"("+a.valueText+")","class":"dijitInline selectableLegendRootValue TrimWithEllipses"}))b.style.marginLeft="10px";this.isRtlPlacement()?(f.place(c,e),b&&f.place(b,e),f.place(d,e)):(f.place(d,e),f.place(c,e),b&&f.place(b,e));g&&(g.set("checked",!a.unchecked),k[a.unchecked?"add":"remove"](e,"selectableLegendRoot_unselected"),g.onClick=function(b){k[b.checked?"remove":"add"](e,"selectableLegendRoot_unselected");h.onSelectionChanged(a.label,
b.checked)});(g=this.getItemMaxWidth())&&this.needFormatAsTable()&&(b&&(d=g-l.getMarginBox(d).w-l.getMarginBox(c).w-b.clientWidth,b.style.marginLeft=d+"px"),e.style.width=g+"px");this.setItemWidth(n.get(e,"width"),e.clientWidth);this.canEditLabel(a)&&(k.add(c,"isEditable"),p(c,"click",function(b){b.stopPropagation();h.onLabelClicked(a,e)}));return e},isRtlPlacement:function(){},isStacked:function(){},needFormatAsTable:function(){},canSelect:function(){},onSelectionChanged:function(a,c){},getMarkerShape:function(){},
canEditLabel:function(a){},onLabelClicked:function(a,c){},getItemMaxWidth:function(){},setItemWidth:function(a,c){}});return h([q,r],{templateString:"\x3cdiv class\x3d'esriGESelectableLegend'\x3e\x3cdiv data-dojo-attach-point\x3d'listDiv'\x3e\x3c/div\x3e\x3c/div\x3e",series:null,allowSelect:!0,allowEditLabels:!1,showSeriesData:!1,isRtlPlacement:!1,keepItemsTheSameWidth:!1,legendSymbol:null,showValues:!1,isStacked:!1,hideLastPoint:!1,chartWidth:0,list:null,_isCollectingWidthsFlag:!1,_uncheckedSeriesHash:null,
_itemMaxWidth:0,_itemFullWidths:null,_isFlowStacked:!1,postCreate:function(){var a=this;this._uncheckedSeriesHash={};var c=m.mixin(new x,{onSelectionChanged:function(b,c){c?delete a._uncheckedSeriesHash[b]:a._uncheckedSeriesHash[b]=!0;a.onSeriesExclusionChanged(a._uncheckedSeriesHash)},onLabelClicked:function(b,c){if(a.showSeriesData)a.onPointLabelClickedAt(void 0!==b.unsortedIndex?b.unsortedIndex:a.list.items.indexOf(b),c);else a.onSeriesLabelClickedAt(a.list.items.indexOf(b),c)},isStacked:function(){return a.isStacked},
needFormatAsTable:function(){return a.isStacked||a._isFlowStacked},canSelect:function(){return a.allowSelect},getMarkerShape:function(){return a.legendSymbol||v.SQUARE},canEditLabel:function(b){return!b.isComparisonSeries&&a.allowEditLabels},isRtlPlacement:function(){return a.isRtlPlacement},getItemMaxWidth:function(){return a._isCollectingWidthsFlag?0:a._itemMaxWidth},setItemWidth:function(b,c){a._isCollectingWidthsFlag&&(a._itemFullWidths.push(c),a._itemMaxWidth=Math.max(a._itemMaxWidth,b))}});
this.list=new u({"class":"selectableLegendFlowList",itemRenderer:c},this.listDiv);this.own(this.list);this.isRtlPlacement&&(this.domNode.style.textAlign="right")},refresh:function(){var a=this._getItems();this.list.domNode.style.width="";this._itemMaxWidth=0;this._itemFullWidths=[];this._isCollectingWidthsFlag=!0;this._isFlowStacked=!1;this.list.setItems(a);this._isCollectingWidthsFlag=!1;var c=0;this._itemFullWidths.forEach(function(a){c+=a});this._isFlowStacked=!this.isStacked&&this.chartWidth&&
c>this.chartWidth;this.keepItemsTheSameWidth&&this.list.refresh();!this.isStacked&&this.chartWidth&&(this._isFlowStacked?(a=this.list.domNode.children[0].clientWidth,a=Math.max(1,Math.floor(this.chartWidth/a))*a+2):a=c+2,this.list.domNode.style.width=a+"px")},_getItems:function(){var a=this,c=[];this.showSeriesData?(this.series&&this.series[0]&&this.series[0].data.forEach(function(b){var d={label:b.name||"",valueText:a.showValues?b.tooltip.valueLabel:null,unsortedIndex:b.unsortedIndex};b=a._getDataFillAndStrokeColors(b);
d.fill=b.fill;d.stroke=b.stroke;c.push(d)}),this.hideLastPoint&&c.pop()):this.series&&this.series.forEach(function(b){var d={label:b.name,unchecked:!0===a._uncheckedSeriesHash[b.name],isComparisonSeries:b.isComparisonSeries};b=a._getDataFillAndStrokeColors(b.data[0]);d.fill=b.fill;d.stroke=b.stroke;c.push(d)});return c},_getDataFillAndStrokeColors:function(a){var c=w.getPointIconStyle(a);return{fill:a.fill||c.fillColor,stroke:a.stroke&&a.stroke.color||c.borderColor}},resetExclusion:function(){this._uncheckedSeriesHash=
{}},onSeriesLabelClickedAt:function(a,c){},onPointLabelClickedAt:function(a,c){},onSeriesExclusionChanged:function(a){}})});