// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/_ChartLegendSupport","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-style ./utils/ChartTypes ./utils/ChartStyleUtil ./utils/ChartCalculator ./legends/ChartLegendTypes ./legends/ChartLegendPlacements ./legends/MinMaxLegend ./legends/SelectableLegend ./legends/ChartLegendSymbols".split(" "),function(k,f,d,g,e,l,m,h,c,n,p,q){return k(null,{legend:null,_placements:[c.LEFT,c.RIGHT,c.TOP,c.BOTTOM],_excludedSeriesHash:null,_createLegend:function(){this._excludedSeriesHash=
{};this._placements.forEach(function(a){d.remove(this.domNode,"legendPlacement"+a)},this);this._currentVisualProperties.legend&&(this._currentVisualProperties.legend.type===h.MIN_MAX?this._createMinMaxLegend():this._createSeriesLegend())},_createSeriesLegend:function(){var a=this._currentVisualProperties.legend.series.placement;if(a!==c.NONE){var b=this._currentVisualProperties.legend.series.symbol||q.getDefaultSymbol(this._currentChartType,this.viewModel.isGraphicStyle);this.legend=(new p(f.mixin({chart:this.chart,
allowSelect:!!this.viewModel.dynamicReportInfo&&(e.isColumnBarLike(this._currentChartType)||e.isLineLike(this._currentChartType)),isStacked:c.isOnSide(a),isRtlPlacement:a===c.LEFT&&!this.viewModel.isGraphicStyle,keepItemsTheSameWidth:!0,legendSymbol:b,showValues:this._currentChartType===e.WAFFLE,hideLastPoint:this._currentVisualProperties.legend.series.hideOthers,onSeriesExclusionChanged:f.hitch(this,this._onSeriesExclusionChanged)},this._getAdditionalLegendParams()))).placeAt(this.getLegendNode());
this._applyStyleToSeriesLegend();d.add(this.domNode,"legendPlacement"+a)}},_applyStyleToSeriesLegend:function(){var a=this.viewModel.getChartDefaultStyles(this.theme),a=f.mixin({},a.legendStyle,this._currentVisualProperties.legend.series.style);this.viewModel.isGraphicStyle||delete a.backgroundColor;g.set(this.legend.domNode,l.getStyleObjWithUnits(a));this._currentVisualProperties.legend.series.hasBorder||g.set(this.legend.domNode,"border","none")},_createMinMaxLegend:function(){this._currentVisualProperties.legend.minMax&&
this._currentVisualProperties.legend.minMax.placement!==c.NONE&&(this.legend=(new n({viewModel:this.viewModel,theme:this.theme})).placeAt(this.getLegendNode()),d.add(this.domNode,"hasMinMaxLegend"),d.add(this.domNode,"legendPlacement"+this._currentVisualProperties.legend.minMax.placement))},_getAdditionalLegendParams:function(){return null},_onSeriesExclusionChanged:function(a){this._excludedSeriesHash=a;this._updateSeries()},_updateLegend:function(){this.legend&&(this._currentVisualProperties.legend.type===
h.MIN_MAX?this._updateMinMaxLegend():this._updateSeriesLegend())},_updateSeriesLegend:function(){this.legend.chartWidth=this.domNode.clientWidth-2*m.PRETTY_PADDING;var a=!this._isMultiFeatureChart&&this._currentComparisonInfo&&this._currentVisualProperties.legend.series.showComparison,b=this._currentSeries.filter(function(b){return!b.isComparisonSeries||a});this.legend.series=b;this.legend.showSeriesData=1===b.length&&!e.isLineLike(this._currentChartType);b=!!this.viewModel.dynamicReportInfo&&1<b.length;
b!==this.legend.allowSelect&&(this.legend.allowSelect=b);this.legend.refresh()},_updateMinMaxLegend:function(){var a=this._currentSeries.filter(function(a){return!a.isComparisonSeries});this.legend.refresh(a,this._currentVisualProperties)},_destroyLegend:function(){this.legend&&this.legend.destroy();this.legend=null}})});