// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var p=function(l,b){p=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(e,b){e.__proto__=b}||function(b,h){for(var e in h)h.hasOwnProperty(e)&&(b[e]=h[e])};return p(l,b)};return function(l,b){function e(){this.constructor=l}p(l,b);l.prototype=null===b?Object.create(b):(e.prototype=b.prototype,new e)}}();
define("esri/arcade/featureset/actions/SpatialFilter","require exports ../sources/Empty ../support/FeatureSet ../support/IdSet ../support/shared ../../polyfill/promiseUtils ../../../geometry/geometryEngineAsync".split(" "),function(p,l,b,e,h,m,n,k){var g=function(d){function b(a){var c=d.call(this,a)||this;c._relation="";c._relationGeom=null;c._relationString="";c.declaredClass="esri.arcade.featureset.actions.SpatialFilter";c._relationString=a.relationString;c._parent=a.parentfeatureset;c._maxProcessing=
40;c._relation=a.relation;c._relationGeom=a.relationGeom;return c}__extends(b,d);b.prototype._getSet=function(a){var c=this;return null===this._wset?this._ensureLoaded().then(function(){return c._parent._getFilteredSet("esriSpatialRelRelation"!==c._relation?c._relation:c._relation+":"+c._relationString,c._relationGeom,null,null,a)}).then(function(b){c._checkCancelled(a);c._wset=new h(b._candidates.slice(0),b._known.slice(0),b._ordered,c._clonePageDefinition(b.pagesDefinition));return c._wset}):n.resolve(this._wset)};
b.prototype._isInFeatureSet=function(a){var c=this._parent._isInFeatureSet(a);if(c===m.IdState.NotInFeatureSet)return c;c=this._idstates[a];return void 0===c?m.IdState.Unknown:c};b.prototype._getFeature=function(a,c,b){return this._parent._getFeature(a,c,b)};b.prototype._getFeatures=function(a,c,b,d){return this._parent._getFeatures(a,c,b,d)};b.prototype._featureFromCache=function(a){return this._parent._featureFromCache(a)};b.prototype.executeSpatialRelationTest=function(a){if(null===a.geometry)return n.resolve(!1);
switch(this._relation){case "esriSpatialRelEnvelopeIntersects":var c=m.shapeExtent(this._relationGeom);a=m.shapeExtent(a.geometry);return k.intersects(c,a);case "esriSpatialRelIntersects":return k.intersects(this._relationGeom,a.geometry);case "esriSpatialRelContains":return k.contains(this._relationGeom,a.geometry);case "esriSpatialRelOverlaps":return k.overlaps(this._relationGeom,a.geometry);case "esriSpatialRelWithin":return k.within(this._relationGeom,a.geometry);case "esriSpatialRelTouches":return k.touches(this._relationGeom,
a.geometry);case "esriSpatialRelCrosses":return k.crosses(this._relationGeom,a.geometry);case "esriSpatialRelRelation":return k.relate(this._relationGeom,a.geometry,this._relationString)}};b.prototype._fetchAndRefineFeatures=function(a,c,b){var d=this,e=new h([],a,!1,null),f=Math.min(c,a.length);return this._parent._getFeatures(e,-1,f,b).then(function(){d._checkCancelled(b);for(var c=[],e=0;e<f;e++){var q=d._parent._featureFromCache(a[e]);c.push(d.executeSpatialRelationTest(q))}return n.all(c)}).then(function(b){for(var e=
0;e<c;e++)d._idstates[a[e]]=!0===b[e]?m.IdState.InFeatureSet:m.IdState.NotInFeatureSet;return"success"})};b.prototype._getFilteredSet=function(a,c,b,d,e){var f=this;return this._ensureLoaded().then(function(){return f._parent._getFilteredSet("esriSpatialRelRelation"!==f._relation?f._relation:f._relation+":"+f._relationString,f._relationGeom,b,d,e)}).then(function(a){f._checkCancelled(e);return null!==c?new h(a._candidates.slice(0).concat(a._known.slice(0)),[],a._ordered,f._clonePageDefinition(a.pagesDefinition)):
new h(a._candidates.slice(0),a._known.slice(0),a._ordered,f._clonePageDefinition(a.pagesDefinition))})};b.prototype._stat=function(a,c,b,d,e,g,h){var f=this;return""!==b?n.resolve({calculated:!1}):this._parent._stat(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,e,g,h).then(function(k){return!1===k.calculated?null===e&&""===b&&null===d?f._manualStat(a,c,g,h):{calculated:!1}:k})};b.prototype._canDoAggregates=function(a,c,b,d,
e){return""!==b||null!==d||null===this._parent?n.resolve(!1):this._parent._canDoAggregates(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,this._relationGeom,e)};b.prototype._getAggregatePagesDataSourceDefinition=function(a,c,b,d,e,g,h){return null===this._parent?n.reject(Error("Should never be called")):this._parent._getAggregatePagesDataSourceDefinition(a,c,"esriSpatialRelRelation"!==this._relation?this._relation:this._relation+":"+this._relationString,
this._relationGeom,e,g,h)};b.prototype.arcadeScriptStep=function(a,c,b){a=this.arcadeAssignNextScriptStepIdentifiers(b);switch(this._relation){case "esriSpatialRelEnvelopeIntersects":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("envelopeIntersects( "+a.currentFeatureSet+","+this.constructArcadeGeom(null===this._relationGeom?null:this._relationGeom.extent,c,b)+")")+"; ";case "esriSpatialRelIntersects":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("intersects( "+
a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,c,b)+")")+"; ";case "esriSpatialRelContains":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("contains( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,c,b)+")")+"; ";case "esriSpatialRelOverlaps":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("overlaps( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,c,b)+")")+"; ";case "esriSpatialRelWithin":return"var "+
a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("within( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,c,b)+")")+"; ";case "esriSpatialRelTouches":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("touches( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,c,b)+")")+"; ";case "esriSpatialRelCrosses":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("crosses( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,
c,b)+")")+"; ";case "esriSpatialRelRelation":return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("relate( "+a.currentFeatureSet+","+this.constructArcadeGeom(this._relationGeom,c,b)+', "'+this._relationString+'")')+";"}return"var "+a.newFeatureSet+" \x3d null; "};return b}(e);e._featuresetFunctions.intersects=function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelIntersects",relationGeom:d})};e._featuresetFunctions.envelopeIntersects=
function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelEnvelopeIntersects",relationGeom:d})};e._featuresetFunctions.contains=function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelContains",relationGeom:d})};e._featuresetFunctions.overlaps=function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelOverlaps",
relationGeom:d})};e._featuresetFunctions.within=function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelWithin",relationGeom:d})};e._featuresetFunctions.touches=function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelTouches",relationGeom:d})};e._featuresetFunctions.crosses=function(d){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,
relation:"esriSpatialRelCrosses",relationGeom:d})};e._featuresetFunctions.relate=function(d,e){return null===d||void 0===d?new b({parentfeatureset:this}):new g({parentfeatureset:this,relation:"esriSpatialRelRelation",relationGeom:d,relationString:e})};return g});