// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var p=function(m,f){p=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,d){h.__proto__=d}||function(h,d){for(var k in d)d.hasOwnProperty(k)&&(h[k]=d[k])};return p(m,f)};return function(m,f){function h(){this.constructor=m}p(m,f);m.prototype=null===f?Object.create(f):(h.prototype=f.prototype,new h)}}();
define("esri/arcade/featureset/actions/Top","require exports ../support/FeatureSet ../support/IdSet ../support/shared ../../polyfill/promiseUtils".split(" "),function(p,m,f,h,d,k){var q=function(f){function e(a){var b=f.call(this,a)||this;b._topnum=0;b.declaredClass="esri.arcade.featureset.actions.Top";b._countedin=0;b._maxProcessing=100;b._topnum=a.topnum;b._parent=a.parentfeatureset;return b}__extends(e,f);e.prototype._getSet=function(a){var b=this;return null===this._wset?this._ensureLoaded().then(function(){return b._parent._getSet(a)}).then(function(a){b._wset=
new h(a._candidates.slice(0),a._known.slice(0),!1,b._clonePageDefinition(a.pagesDefinition));b._setKnownLength(b._wset)>b._topnum&&(b._wset._known=b._wset._known.slice(0,b._topnum));b._setKnownLength(b._wset)>=b._topnum&&(b._wset._candidates=[]);return b._wset}):k.resolve(this._wset)};e.prototype._setKnownLength=function(a){return 0<a._known.length&&"GETPAGES"===a._known[a._known.length-1]?a._known.length-1:a._known.length};e.prototype._isInFeatureSet=function(a){var b=this._parent._isInFeatureSet(a);
if(b===d.IdState.NotInFeatureSet)return b;var l=this._idstates[a];return l===d.IdState.InFeatureSet||l===d.IdState.NotInFeatureSet?l:b===d.IdState.InFeatureSet&&void 0===l?this._countedin<this._topnum?(this._idstates[a]=d.IdState.InFeatureSet,this._countedin++,d.IdState.InFeatureSet):this._idstates[a]=d.IdState.NotInFeatureSet:d.IdState.Unknown};e.prototype._expandPagedSet=function(a,b,l,g,d){var c=this;if(null===this._parent)return k.reject(Error("Parent Paging not implemented"));b>this._topnum&&
(b=this._topnum);return this._countedin>=this._topnum&&a.pagesDefinition.internal.set.length<=a.pagesDefinition.resultOffset?(b=a._known.length,0<b&&"GETPAGES"===a._known[b-1]&&(a._known.length=b-1),b=a._candidates.length,0<b&&"GETPAGES"===a._candidates[b-1]&&(a._candidates.length=b-1),k.resolve("success")):this._parent._expandPagedSet(a,b,l,g,d).then(function(b){c._setKnownLength(a)>c._topnum&&(a._known.length=c._topnum);c._setKnownLength(a)>=c._topnum&&(a._candidates.length=0);return b})};e.prototype._getFeatures=
function(a,b,d,g){var l=this,c=[],n=this._maxQueryRate();if(!0===this._checkIfNeedToExpandKnownPage(a,n,g))return this._expandPagedSet(a,n,0,0,g).then(function(c){return l._getFeatures(a,b,d,g)});-1!==b&&void 0===this._featureCache[b]&&c.push(b);for(var f=0,e=a._lastFetchedIndex;e<a._known.length&&!(f++,f<=d&&(a._lastFetchedIndex+=1),void 0===this._featureCache[a._known[e]]&&(a._known[e]!==b&&c.push(a._known[e]),c.length>n-1));e++);if(0===c.length)return k.resolve("success");var n=new h([],c,!1,null),
m=Math.min(c.length,d);return this._parent._getFeatures(n,-1,m,g).then(function(a){for(a=0;a<m;a++){var b=l._parent._featureFromCache(c[a]);void 0!==b&&(l._featureCache[c[a]]=b)}return"success"})};e.prototype._getFilteredSet=function(a,b,d,g,e){var c=this;return this._ensureLoaded().then(function(){return c._getSet(e)}).then(function(a){return new h(a._candidates.slice(0).concat(a._known.slice(0)),[],!1,c._clonePageDefinition(a.pagesDefinition))})};e.prototype._refineKnowns=function(a,b){for(var e=
0,g=null,f=[],c=0;c<a._candidates.length;c++){var h=this._isInFeatureSet(a._candidates[c]);if(h===d.IdState.InFeatureSet){if(a._known.push(a._candidates[c]),e+=1,null===g?g={start:c,end:c}:g.end===c-1?g.end=c:(f.push(g),g={start:c,end:c}),a._known.length>=this._topnum)break}else if(h===d.IdState.NotInFeatureSet)null===g?g={start:c,end:c}:g.end===c-1?g.end=c:(f.push(g),g={start:c,end:c}),e+=1;else if(h===d.IdState.Unknown)break;if(e>=b)break}null!==g&&f.push(g);for(b=f.length-1;0<=b;b--)a._candidates.splice(f[b].start,
f[b].end-f[b].start+1);this._setKnownLength(a)>this._topnum&&(a._known=a._known.slice(0,this._topnum));this._setKnownLength(a)>=this._topnum&&(a._candidates=[])};e.prototype._stat=function(a,b,d,e,f,c,h){return k.resolve({calculated:!1})};e.prototype._canDoAggregates=function(a,b,d,e,f){return k.resolve(!1)};e.prototype.arcadeScriptStep=function(a,b,d){a=this.arcadeAssignNextScriptStepIdentifiers(d);return"var "+a.newFeatureSet+" \x3d "+this.bigDataCachePipeline("top( "+a.currentFeatureSet+","+this._topnum.toString()+
")")+"; "};return e}(f);f._featuresetFunctions.top=function(d){return new q({parentfeatureset:this,topnum:d})};return q});