// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/annotations/shape/ShapeContainer","dojo/_base/declare dojo/_base/lang dojo/sniff dojo/dom-class dojo/dom-construct dojo/dom-style ../../grid/valueField/ValueField esri/dijit/geoenrichment/utils/MathUtil esri/dijit/geoenrichment/utils/ShapeUtil ../utils/AnnotationsUtil ./ShapeThemeUtil dojo/i18n!esri/nls/jsapi".split(" "),function(u,h,v,p,k,e,w,x,r,f,y,A){var z={borderColor:"#AAAAAA",fillColor:"#AAAAAA"};return u(w,{__isShapeContainer:!0,viewModel:null,
theme:null,currentFeatureIndex:null,shapeJson:null,relativeParent:null,alignParams:null,applyThemeStyle:!0,getPreviewValueFunction:null,parentWidget:null,_g:!1,_viewBox:!1,_shapeStyle:null,_shapeThemeStyle:null,_needSaveShapeThemeStyle:!0,_preserveAspectRatio:void 0,_showAsBar:!1,_showBarBackground:!1,_barBackgroundStyle:null,_isPlaceholder:!1,_angle:0,postCreate:function(){this.content=k.create("div",{"class":"floatingElement templateShape"});this.fieldStyle=this.fieldStyle||{};this.fieldStyle.width=
this.shapeJson.style.width;this.fieldStyle.height=this.shapeJson.style.height;this._g=this.shapeJson.g;this._viewBox=this.shapeJson.viewBox;this._shapeStyle=this.shapeJson.style||{};this._preserveAspectRatio=this.shapeJson.preserveAspectRatio;this._isPlaceholder=this.shapeJson.isPlaceholder;this._angle=this.shapeJson.style.angle||0;this._processThemeStyle();this._showAsBar=this.shapeJson.showAsBar;this._showBarBackground=this.shapeJson.showBarBackground;this._barBackgroundStyle=this.shapeJson.barBackgroundStyle||
{};this.inherited(arguments);p.add(this.domNode,"floatingElementContainer");e.set(this.domNode,"position","absolute");e.set(this.domNode,"top",(this.shapeJson.style.top||0)+"px");e.set(this.domNode,"left",(this.shapeJson.style.left||0)+"px");this._updateShapeNode();this._applyRotation();this.alignParams&&f.alignAnnotationContainer(this,this.alignParams);this.onInitialized()},_processThemeStyle:function(){this.applyThemeStyle&&(this._shapeThemeStyle=y.getThemeStylesFromShapeJson(this.shapeJson,this.parentWidget.parentGrid),
this._needSaveShapeThemeStyle=!!this.shapeJson.themeStyle)},setAngle:function(a){this._angle=x.angleTo180_180Range(Number(a)||0);this._applyRotation()},_applyRotation:function(){this._angle=0<this._angle||0>this._angle?this._angle:0;var a=v("webkit")?"webkitTransform":"transform";this.content.style[a]="rotate("+this._angle+"deg)"},_lastAlignParams:null,resize:function(a,b){a&&(this.setWidth(a.w),this.setHeight(a.h));this._updateShapeNode();this._lastAlignParams=b||this._lastAlignParams;f.alignAnnotationContainer(this,
this._lastAlignParams)},scaleProportionallyWithinParent:function(a){var b=this.getShapeBox();this.resize({w:b.w*a.xScale,h:b.h*a.yScale});e.set(this.domNode,{left:b.l*a.xScale+"px",top:b.t*a.yScale+"px"})},getShapeBox:function(){return{l:e.get(this.domNode,"left"),t:e.get(this.domNode,"top"),w:this.getWidth(),h:this.getHeight()}},_updateShapeNode:function(){function a(a){function d(a){var d=r.createSVGNode(c,{width:l+"px",height:n+"px",overflow:"visible"});b._preserveAspectRatio&&d.setAttribute("preserveAspectRatio",
b._preserveAspectRatio);b._g.forEach(function(a){(a=r.createNodeByAttributes(a,q,{overrideFillOpacity:!0}))&&d.appendChild(a)});var g=k.create("div",{"class":"shapeContainer_svgContainerElement"},f);e.set(g,"left",a*l+"px");k.place(d,g)}var f=k.create("div",{"class":"shapeContainer_svgContainer esriGEAbsoluteStretched"},b.content),q;a?(p.add(f,"shapeContainer_svgContainerBackground"),q=h.mixin({},b._barBackgroundStyle,z)):q=h.mixin({},b._shapeThemeStyle,b._shapeStyle);var g=1;b._showAsBar&&(g=a?1:
b.getPreviewValueFunction?b.getPreviewValueFunction().normalizedValue:.5+.5*Math.random(),e.set(f,"width",g*m+"px"),p.add(f,"shapeContainer_svgContainerShowAsBar"));a=b._showAsBar?Math.floor(m/l):1;a=Math.round(g*a);for(g=0;g<a;g++)d(g)}var b=this,c=this._viewBox;if(0<this._shapeStyle.borderAlpha&&0<this._shapeStyle.borderWidth){var d=this._shapeStyle.borderWidth,c=h.mixin({},this._viewBox);c.xmin=c.xmin||0;c.ymin=c.ymin||0;c.xmin-=d/4;c.ymin-=d/4;c.width+=d/2;c.height+=d/2}var m=this.getWidth(),
d=this.getHeight(),f=c.width/c.height,t=Math.min(m,d*f),l,n;"none"===this._preserveAspectRatio?(l=m,n=d):(l=t,n=t/f);e.set(this.content,"width",(this._showAsBar?m:l)+"px");e.set(this.content,"height",n+"px");k.empty(this.content);this._isPlaceholder?k.create("div",{"class":"shapeContainer_svgPlaceholder"},this.content):(this._showAsBar&&this._showBarBackground&&a(!0),a())},onInitialized:function(){},_domNodePositionToShapeStyle:function(){this.domNode&&(this._shapeStyle.top=e.get(this.domNode,"top"),
this._shapeStyle.left=e.get(this.domNode,"left"))},toJson:function(){this._domNodePositionToShapeStyle();var a={id:"shape",g:this._g,viewBox:this._viewBox,preserveAspectRatio:this._preserveAspectRatio,isPlaceholder:this._isPlaceholder,style:h.mixin({},this._shapeStyle,{angle:this._angle,width:this.getWidth(),height:this.getHeight()}),themeStyle:this._needSaveShapeThemeStyle?this._shapeThemeStyle:void 0,showAsBar:this._showAsBar,showBarBackground:this._showBarBackground,barBackgroundStyle:h.mixin({},
this._barBackgroundStyle)};return h.clone(a)}})});