// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/utils/TooltipUtil","dojo/_base/declare dojo/_base/lang dojo/dom-class dojo/dom-construct dojo/dom-geometry dojo/dom-style dojo/on dojo/mouse dojo/sniff dijit/Tooltip dijit/place ./DeviceUtil ./DnDUtil ./DomUtil ./MouseUtil dojo/domReady!".split(" "),function(C,D,n,k,t,E,p,q,y,z,F,w,G,r,x){function A(){}var c={},H=C(z._MasterTooltip,{_customClasses:null,addCustomClasses:function(a){a&&(n.add(this.domNode,a),this._customClasses=a)},show:function(a,d,b,g,e,c,h){if(!this.aroundNode||
this.aroundNode!==d||this.containerNode.innerHTML!=a)if("playing"==this.fadeOut.status())this._onDeck=arguments;else{"string"===typeof a?this.containerNode.innerHTML=a:(this.containerNode.innerHTML="",k.place(a.domNode,this.containerNode));e&&this.set("textDir",e);this.containerNode.align=g?"right":"left";var l=F.around(this.domNode,d,b&&b.length?b:z.defaultPosition,!g,D.hitch(this,"orient")),f=l.aroundNodePos;"M"==l.corner.charAt(0)&&"M"==l.aroundCorner.charAt(0)?(this.connectorNode.style.top=f.y+
(f.h-this.connectorNode.offsetHeight>>1)-l.y+"px",this.connectorNode.style.left=""):"M"==l.corner.charAt(1)&&"M"==l.aroundCorner.charAt(1)?this.connectorNode.style.left=f.x+(f.w-this.connectorNode.offsetWidth>>1)-l.x+"px":(this.connectorNode.style.left="",this.connectorNode.style.top="");this.domNode.style.opacity="0";this.fadeIn.play();this.isShowingNow=!0;this.aroundNode=d;this.onMouseEnter=c||A;this.onMouseLeave=h||A}},orient:function(a,d,b,g,e){this.connectorNode.style.top="";var f=g.h;g=g.w;
a.className="dijitTooltip "+{"MR-ML":"dijitTooltipRight","ML-MR":"dijitTooltipLeft","TM-BM":"dijitTooltipAbove","BM-TM":"dijitTooltipBelow","BL-TL":"dijitTooltipBelow dijitTooltipABLeft","TL-BL":"dijitTooltipAbove dijitTooltipABLeft","BR-TR":"dijitTooltipBelow dijitTooltipABRight","TR-BR":"dijitTooltipAbove dijitTooltipABRight","BR-BL":"dijitTooltipRight","BL-BR":"dijitTooltipLeft"}[d+"-"+b];this.addCustomClasses(this._customClasses);this.domNode.style.width="auto";var c=t.position(this.domNode);
if(y("ie")||y("trident"))c.w+=2;t.setMarginBox(this.domNode,{w:Math.min(Math.max(g,1),c.w)});"B"==b.charAt(0)&&"B"==d.charAt(0)?(a=t.position(a),d=this.connectorNode.offsetHeight,a.h>f?(this.connectorNode.style.top=f-(e.h+d>>1)+"px",this.connectorNode.style.bottom=""):(this.connectorNode.style.bottom=Math.min(Math.max(e.h/2-d/2,0),a.h-d)+"px",this.connectorNode.style.top="")):(this.connectorNode.style.top="",this.connectorNode.style.bottom="");return Math.max(0,c.w-g)}}),B={show:function(a,d,b,c){b=
b&&b.map(function(a){return{after:"after-centered",before:"before-centered"}[a]||a});var e=new H;e.addCustomClasses(c);e.show(a,d,b);return e}};c.setTooltipToNode=function(a,d,b){function g(){!e&&c.showTooltipForNode(a,d,b)}b=b||{};if(a&&(c.hideTooltipForNode(a),a.__setTooltipToNodeMouseEnterHandle&&a.__setTooltipToNodeMouseEnterHandle.remove(),d)){var e=!1;w.isMobileDevice()?a.__setTooltipToNodeMouseEnterHandle=G.addNoDragClickHandler(a,g):a.__setTooltipToNodeMouseEnterHandle=p(a,q.enter,g);return{remove:function(){d=
null;c.hideTooltipForNode(a)},suspend:function(){c.hideTooltipForNode(a);e=!0},resume:function(){e=!1}}}};c.showTooltipForNode=function(a,d,b){function g(){c.hideTooltipForNode(a);var d=Array.isArray(b.classes)?b.classes.join(" "):b.classes,d=(d||"")+" esriGETooltip";b.notRestricted&&(d+=" notRestricted");a._shownTooltip=f=B.show(e,a,b.position||["after","before"],d)}if(a){c.hideTooltipForNode(a);var e="function"==typeof d?d():d;if(e){b.textAlign&&(e="\x3cdiv class\x3d'"+("start"===b.textAlign?"esriGEStart":
"end"===b.textAlign?"esriGEEnd":"")+"'\x3e"+e+"\x3c/div\x3e");n.add(a,"esriGESimpleTextTooltip");var f;g();var h=c.hideTooltipForNode.bind(c,a);w.isMobileDevice()?a.__setTooltipToNodeMouseLeaveHandle=p(document.body,"touchstart",function(d){x.isMouseOver(a,{event:d})||h()}):a.__setTooltipToNodeMouseLeaveHandle=p.once(a,q.leave,function(){!b.stayOnHover&&h()});b.ignoreNodeRemoval||(a.__setTooltipToNodeInLayoutHandle=setInterval(function(){!r.isNodeInLayout(a)&&h()},300));w.isMobileDevice()||(a.__setTooltipToNodeMouseOverHandle=
setInterval(function(){b.stayOnHover&&x.isMouseOver(f.domNode)||x.isMouseOver(a)||h()},300),a.__setTooltipToNodeClickHandle=p(a,"click",function(d){d.stopPropagation();b.hideOnClick?h():!a._shownTooltip&&g()}),b.stayOnHover&&(a.__setTooltipToNodeMouseLeaveMasterHandle=p(f.domNode,q.leave,h)));return a._shownTooltip}}};c.hideTooltipForNode=function(a){a&&(delete a.title,n.remove(a,"esriGESimpleTextTooltip"),a._shownTooltip&&a._shownTooltip.destroy(),delete a._shownTooltip,a.__setTooltipToNodeMouseLeaveHandle&&
a.__setTooltipToNodeMouseLeaveHandle.remove(),clearInterval(a.__setTooltipToNodeInLayoutHandle),clearInterval(a.__setTooltipToNodeMouseOverHandle),a.__setTooltipToNodeClickHandle&&a.__setTooltipToNodeClickHandle.remove(),a.__setTooltipToNodeMouseLeaveMasterHandle&&a.__setTooltipToNodeMouseLeaveMasterHandle.remove())};var m=null;c.autoTooltip=function(a){p(a,".TrimWithEllipses:mouseover",function(){if(this!==m&&this.offsetWidth<this.scrollWidth){m=this;var a=B.show(m.textContent,m,["above","below"]);
p.once(m,"mouseout, mousedown, touchstart",function(){a.destroy();m=null})}})};c.showClosableTooltip=function(a){var d=c._createClosableTooltip(a.message,a.tooltipClass,a.position);return c._placeClosableTooltip(d,a.node,a.timeout,a.position,a.onClosed)};c.removeClosableTooltip=function(a){a&&a._removeFunc&&a._removeFunc()};c._createClosableTooltip=function(a,d,b){function c(){var a=k.create("div",{"class":"esriGEClosableTooltipTip"},f);n.add(a,"right"===b?"esriGEClosableTooltipTipRight":"esriGEClosableTooltipTipLeft")}
function e(){h=k.create("div",{"class":"esriGEClosableTooltipBody"},f);k.create("div",{innerHTML:a,"class":"esriGEClosableTooltipLabel"},h);l=k.create("div",{"class":"esriGEClosableTooltipCloseButton"},h)}var f=k.create("div",{"class":"esriGEClosableTooltip esriGENonSelectable "+(d||"")},document.body),h,l;"right"!==b?(e(),c()):(c(),e());f.style.position="fixed";return{tooltip:f,body:h,closeButton:l}};c._placeClosableTooltip=function(a,d,b,c,e){function f(){var b=t.position(d),c=b.x+";"+b.y+";"+b.w+
";"+b.h;c!==g&&(g=c,c=t.getMarginBox(a.tooltip),E.set(a.tooltip,{left:(h?b.x+b.w:b.x-c.w)+"px",top:b.y+b.h/2-c.h/2+"px"}))}var h="rtl"===document.dir&&"right"!==c||"rtl"!==document.dir&&"right"===c,g;f();var k,m,n,q,u,v=function(){k&&clearTimeout(k);m&&clearInterval(m);n&&clearInterval(n);q&&q.remove();a.tooltip.parentNode&&a.tooltip.parentNode.removeChild(a.tooltip)};m=setInterval(function(){r.isNodeInLayout(d)||(u=!1,v());r.isNodeVisible(d)&&r.isNodeOnscreen(d)?(u=!0,r.show(a.tooltip)):(u=!1,r.hide(a.tooltip))},
300);n=setInterval(function(){u&&f()},0);b&&(k=setTimeout(v,b));q=p(a.closeButton,"click",function(){v();e&&e()});a.tooltip._removeFunc=v;return a.tooltip};return c});