// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ThemeCalculator","dojo/_base/lang dojox/charting/Theme ../../themes/ThemeLibrary ./ChartTypes ./ChartLineMarkers esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(k,u,n,h,p,v){function t(c,b,e){var a;switch(c){case h.COLUMN:a=b.column&&b.column.colors;break;case h.BAR:a=b.bar&&b.bar.colors;break;case h.LINE:a=b.line&&b.line.colors;break;case h.VERTICAL_LINE:a=b.line&&b.line.colors;break;case h.PIE:a=b.pie&&b.pie.colors;break;
case h.DONUT:a=b.donut&&b.donut.colors;break;case h.GAUGE:a=b.gauge&&b.gauge.colors;break;case h.WAFFLE:a=b.waffle&&b.waffle.colors;break;case h.RING:a=b.ring&&b.ring.colors;break;case h.PICTURE_COLUMN:a=b.pictureColumn&&b.pictureColumn.colors;break;case h.PICTURE_BAR:a=b.pictureBar&&b.pictureBar.colors}a&&a.length||(a=null);return 3>=e&&b.colors3series&&b.colors3series.length&&b.colors3series||a||b.colors||q}var f={},q=["#AAAAAA","#888888","#555555","#333333"];f.DEFAULT_LINE_THICKNESS=1;f.DEFAULT_COLUMN_THICKNESS=
"Medium";f.DEFAULT_DONUT_HOLE_PERCENT=50;f.DEFAULT_DONUT_GAP=3;f.DEFAULT_DONUT_ARC_PERCENT=100;f.DEFAULT_GAUGE_HOLE_PERCENT=80;f.DEFAULT_GAUGE_GAP=2;f.DEFAULT_GAUGE_ANGLE=0;f.DEFAULT_GAUGE_ARC_PERCENT=100;f.getThemeForSettings=function(c,b,e){var a=new u({colors:b.colors||q});if(!c)return a;var d=c.visualProperties;a.plotarea.fill=d.backgroundColor||b.backgroundColor;a.plotarea.stroke={width:0};a.chart.fill="transparent";a.axis.title.font="normal normal normal 11px Verdana";h.hasBackgroundImage(c.type)&&
(a.plotarea.backgroundImageData=d.backgroundImageData);var g=k.mixin({},b.dataLabelsStyle,d.dataLabelsStyle);a.series.dataLabelsColor=g.color;a.series.dataLabelsAltColor=d.dataLabelsEnableAltColor&&(d.dataLabelsAltColor||b.dataLabelsAltColor);a.series.dataLabelsFont=f.combineFontString(g);a.series.dataLabelsHorizontalAlign=d.dataLabelsHorizontalAlign||"center";a.series.dataLabelsVerticalAlign=d.dataLabelsVerticalAlign||"middle";a.series.dataLabelsAngle=d.dataLabelsAngle;a.series.dataLabelsMaxWidth=
d.dataLabelsMaxWidth;var l=k.mixin({},g,d.dataLabelsLabelStyle);a.series.dataLabelsLabelColor=l.color;a.series.dataLabelsLabelFont=f.combineFontString(l);a.series.dataLabelsPercentColor=g.color;a.series.dataLabelsPercentFont=f.combineFontString(g);h.isColumnBarLike(c.type)&&(a.series.showColumnBarBackground=d.showColumnBarBackground,a.series.columnBarBackgroundColor=d.columnBarBackgroundColor||b.columnBarBackground&&b.columnBarBackground.backgroundColor,a.series.columnBarBackgroundColor&&(a.series.columnBarBackgroundColor=
1>d.columnBarBackgroundOpacity?v.getColorWithAlpha(a.series.columnBarBackgroundColor,d.columnBarBackgroundOpacity):a.series.columnBarBackgroundColor,a.series.renderColumnBarsInOppositeDirections=d.renderColumnBarsInOppositeDirections));h.hasAxis(c.type)&&(a.series.baseLineValue=d.yAxis.baseLineValue);c.type===h.DONUT&&(a.series.donutHolePercent=void 0!==d.donutHolePercent?d.donutHolePercent:f.DEFAULT_DONUT_HOLE_PERCENT,a.series.donutGap=void 0!==d.donutGap?d.donutGap:f.DEFAULT_DONUT_GAP,a.series.donutArcPercent=
void 0!==d.donutArcPercent?d.donutArcPercent:f.DEFAULT_DONUT_ARC_PERCENT,a.series.donutArcPercent=Math.min(100,Math.max(50,a.series.donutArcPercent)));c.type===h.GAUGE&&(a.series.donutHolePercent=void 0!==d.gaugeHolePercent?d.gaugeHolePercent:f.DEFAULT_GAUGE_HOLE_PERCENT,a.series.donutGap=void 0!==d.gaugeGap?d.gaugeGap:f.DEFAULT_GAUGE_GAP,a.series.startAngle=void 0!==d.gaugeStartAngle?d.gaugeStartAngle:f.DEFAULT_GAUGE_ANGLE,a.series.donutArcPercent=void 0!==d.gaugeArcPercent?d.gaugeArcPercent:f.DEFAULT_GAUGE_ARC_PERCENT,
a.series.donutArcPercent=Math.min(100,Math.max(50,a.series.donutArcPercent)),a.series.donutShowIcons=d.showChartIcons,d.gaugeShowArrow&&(a.series.gaugeShowArrowIndicator=!0,a.series.donutGap=0,100!==a.series.donutArcPercent&&(a.series.startAngle=0),a.series.gaugeArrowIndicatorLineColor=d.gaugeArrowLineColor||b.gauge&&b.gauge.arrowIndicator.lineColor,a.series.gaugeArrowIndicatorFillColor=d.gaugeArrowFillColor||b.gauge&&b.gauge.arrowIndicator.backgroundColor),g=k.mixin({},b.gauge&&b.gauge.dataLabelStyle,
d.gaugeLabelStyle),a.series.gaugeMainLabelPosition=d.gaugeLabelPlacement,a.series.gaugeMainLabelFont=f.combineFontString(g),a.series.gaugeMainLabelFontColor=d.gaugeConditionalStylingLabel?null:g.color,a.series.gaugeMainLabelFontColorFromConditionalStyling=d.gaugeConditionalStylingLabel&&!!d.conditionalStyling,a.series.gaugeMainLabelFontSize=d.gaugeLabelStyle&&d.gaugeLabelStyle.fontSize,a.series.gaugeMainLabelTextDecoration=g.textDecoration,d.gaugeShowFromToLabels&&(a.series.gaugeShowFromToLabels=
d.gaugeShowFromToLabels,g=k.mixin({},b.gauge&&b.gauge.dataLabelStyle,d.gaugeFromLabelStyle),a.series.gaugeFromLabelValue=d.gaugeRangeMin||0,a.series.gaugeFromLabelFont=f.combineFontString(g),a.series.gaugeFromLabelFontColor=g.color,a.series.gaugeFromLabelFontSize=g.fontSize,a.series.gaugeFromLabelTextDecoration=g.textDecoration,g=k.mixin({},b.gauge&&b.gauge.dataLabelStyle,d.gaugeToLabelStyle),a.series.gaugeToLabelValue=d.gaugeRangeMax||"",a.series.gaugeToLabelFont=f.combineFontString(g),a.series.gaugeToLabelFontColor=
g.color,a.series.gaugeToLabelFontSize=g.fontSize,a.series.gaugeToLabelTextDecoration=g.textDecoration));c.type===h.WAFFLE&&(a.series.waffleDirection=d.waffleDirection,a.series.waffleShowWholePictures=d.waffleShowWholePictures,a.series.waffleLabelPlacement=d.waffleLabelPlacement,a.series.waffleLabelOffset=d.waffleLabelOffset,a.series.waffleColumnSpace=d.waffleColumnSpace,a.series.waffleRowSpace=d.waffleRowSpace,a.series.waffleNumIcons=d.waffleNumIcons,a.series.waffleHideValue=d.waffleHideValue,g=k.mixin({},
b.waffle&&b.waffle.dataValueStyle,d.waffleValueStyle),a.series.waffleValueFont=f.combineFontString(g),a.series.waffleValueFontColor=d.waffleConditionalStylingValue?null:g.color,a.series.waffleValueFontColorFromConditionalStyling=d.waffleConditionalStylingValue&&!!d.conditionalStyling,a.series.waffleValueFontSize=g.fontSize,a.series.waffleValueTextDecoration=g.textDecoration,a.series.waffleHideLabel=d.waffleHideLabel,g=k.mixin({},b.waffle&&b.waffle.dataLabelStyle,d.waffleLabelStyle),a.series.waffleLabelFont=
f.combineFontString(g),a.series.waffleLabelFontColor=d.waffleConditionalStylingLabel?null:g.color,a.series.waffleLabelFontColorFromConditionalStyling=d.waffleConditionalStylingLabel&&!!d.conditionalStyling,a.series.waffleLabelFontSize=g.fontSize,a.series.waffleLabelTextDecoration=g.textDecoration,a.series.waffleShowLabelAbove=d.waffleShowLabelAbove);c.type===h.RING&&(a.series.show100PercentLabel=!0,a.series.ringBackgroundColor=d.ringBackgroundColor||b.ring&&b.ring.ringBackground&&b.ring.ringBackground.backgroundColor);
h.isPictureLike(c.type)&&(a.series.columnBarShowWholePictures=d.columnBarShowWholePictures);a.marker.fill="#FFFFFF";a.series.outline=null;a.series.isEditMode=e;return a};f.getComparisonSymbol=function(){return p.getMarkerPath(p.CIRCLE)};f.calcColorForPoint=function(c){var b=c.point,e=c.seriesItem,a=c.pointIndex,d=c.isOthersPoint,g=c.seriesIndex,l=c.numSeries,k=c.chartType,m=c.themeSettings,n=c.isComparisonSeries;c=c.comparisonInfo;var p=e&&e.points.length;k===h.WAFFLE&&p--;var e=e&&e.color,q=h.isSingleSeries(k)||
h.isColumnBarLike(k)&&!m.renderSingleDataSeriesWithSameColor&&1===l,l=t(k,m,q?p:l),r;if(h.isLineLike(k))n&&c?a=c.color||m.comparisonInfo.lineColor:(r=l[g%l.length],a=e||r||"#000000");else if(n&&c&&c.color)a=c.color;else{b=h.isPictureLike(k)?b&&f.getPointIconStyle(b).fillColor:b&&b.color;if(k===h.GAUGE&&d&&m.gauge.othersColor)return b||m.gauge.othersColor;if(k===h.WAFFLE&&d&&m.waffle.othersColor)return b||m.waffle.othersColor;r=r||(q?l[a%l.length]:l[g%l.length]);a=b||!h.isSingleSeries(k)&&e||r||"#000000"}return a};
f.pointCanHaveColor=function(c){return h.isPictureLike(c.chartType)?!!(c.point.iconFieldInfo&&c.point.iconFieldInfo.shapeJson&&c.point.iconFieldInfo.shapeJson.g.length):!0};f.setPointColor=function(c,b){delete c.color;c.iconFieldInfo?c.iconFieldInfo.shapeJson&&(delete c.iconFieldInfo.shapeJson.style.fillColor,delete c.iconFieldInfo.shapeJson.style.borderColor,b&&(c.iconFieldInfo.shapeJson.style.fillColor=b,c.iconFieldInfo.shapeJson.style.borderColor=b)):b&&(c.color=b)};f.calcColorForSeries=function(c){var b=
c.seriesItem,e=c.seriesIndex,a=c.numSeries,d=c.chartType,g=c.themeSettings;if(h.isSingleSeries(d))return null;c=h.isColumnBarLike(d)&&!g.renderSingleDataSeriesWithSameColor&&1===a;a=t(d,g,a);e=h.isLineLike(d)?a[e%a.length]:c?null:a[e%a.length];return b&&b.color||e||"#000000"};f.provideMissingIconsForPoints=function(c,b){if(h.isPictureLike(b)){var e,a=[];c.forEach(function(b){b.iconFieldInfo?(e=b.iconFieldInfo,a.forEach(function(a){a.iconFieldInfo=k.clone(e)}),a.length=0):e?b.iconFieldInfo=k.clone(e):
a.push(b)})}};f.setWaffleChartPointIcon=function(c,b,e){var a=c&&c.shapeJson;0===b?e.forEach(function(b,e){if(b.fieldInfo||a){var d=f.getPointIconStyle(b);b.iconFieldInfo=0===e?c:c&&k.clone(c);b.iconFieldInfo&&b.iconFieldInfo.shapeJson&&0!==e&&(b.iconFieldInfo.shapeJson.style.fillColor=d.fillColor,b.iconFieldInfo.shapeJson.style.borderColor=d.borderColor)}}):e[b].iconFieldInfo=c;b=e[0];e=e[e.length-1];!e.iconFieldInfo&&b.iconFieldInfo&&b.iconFieldInfo.shapeJson&&(e.iconFieldInfo=k.clone(b.iconFieldInfo),
delete e.iconFieldInfo.shapeJson.style.fillColor,delete e.iconFieldInfo.shapeJson.style.borderColor)};f.getPointIconStyle=function(c,b){function e(a,b){return"number"===typeof a?a:b}var a=c&&(c.iconFieldInfo||c.icon);if(!a||!a.shapeJson)return{fillColor:null,fillAlpha:null,borderColor:null,borderAlpha:null,borderWidth:null,borderDashArray:null};c=a.shapeJson.style;b=b&&b.considerTheme&&a.shapeJson.themeStyle;return{fillColor:c&&c.fillColor||b&&b.fillColor,fillAlpha:e(c&&c.fillAlpha,b&&b.fillAlpha),
borderColor:c&&c.borderColor||b&&b.borderColor,borderAlpha:e(c&&c.borderAlpha,b&&b.borderAlpha),borderWidth:e(c&&c.borderWidth,b&&b.borderWidth),borderDashArray:c&&c.borderDashArray||b&&b.borderDashArray}};f.calcIconForPoint=function(c,b,e){if(!h.isPictureLike(e))return null;(c=c.iconFieldInfo)&&c.shapeJson&&b&&(c=k.clone(c),c.shapeJson.themeStyle={fillColor:b,borderColor:b});return c};f.calcBackgroundIconForPoint=function(c,b,e,a){if(!h.isPictureLike(b))return null;b=a.columnBarBackgroundColor||
e.columnBarBackground&&e.columnBarBackground.backgroundColor;return(c=c.iconFieldInfo)&&c.shapeJson&&b?(c=k.clone(c),c.shapeJson.themeStyle={fillColor:b,borderColor:b},c):null};f.combineFontString=function(c){c=c||{};return(c.fontStyle||"normal")+" normal "+(c.fontWeight||"normal")+" "+((c.fontSize||n.CHART_DATA_FONT_SIZE)+"px")+" "+(c.fontFamily||n.DEFAULT_FONT_FAMILY_CLASSIC)};return f});