// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/waffle/_ShapeRenderer","dojo/_base/Color dojox/gfx dojox/gfx/utils ../pictureUtil/Converter ../../../../supportClasses/images/ImageDataHolder ../supportClasses/WaffleDirections".split(" "),function(A,z,B,C,D,r){var E={packRect:function(c,e,a,f,b,g){if(!b||1===b)return a=Math.min(a/c,f/e),{w:c*a,h:e*a,numColumns:1,numRows:1};c/=e;e*=c;f*=c;var d=Math.sqrt(a*f/b);e=Math.max(1,Math.round(a/d));for(var d=Math.max(1,Math.round(f/d)),
h=0,l=0,p=0,n=-100;101>n;n++)for(var v=-100;101>v;v++){var m=e+n,k=d+v;if(!(1>m||1>k||(g?m*k!==b:m*k<b))){var q=Math.min(a/m,f/k);q>h&&(h=q,l=m,p=k)}}return{w:h,h:h/c,numColumns:l,numRows:p}}},t={renderShape:function(c,e,a,f,b){var g=[],d=[],h=[];c.map(function(b){b.icon&&(g.push(b.icon),b=a.createGroup(),e.series.isEditMode&&(b.rawNode.style.cursor="pointer"),b.openBatch(),d.push(b))});if(g.length){var l=t._calcIconParams(g,f,e);d.forEach(function(b,a){a=g[a];var c=[];h.push(c);for(var d=0;d<l.numRows;d++)for(var n=
0;n<l.numColumns&&(!e.series.waffleNumIcons||c.length!==e.series.waffleNumIcons);n++)c.push(t._renderIcon(d,n,b,a,f,e,l))})}d.forEach(function(a){a.closeBatch()});var p=function(a){return t._fillIcons(a,g,d,h,c,e,l)};b.push({isShape:!0,func:p});return p},_calcIconParams:function(c,e,a){c=c[0];var f=c.shapeJson||c.imageJson,b,g;a.series.waffleNumIcons?(c=40,f=c*f.style.height/f.style.width,g=E.packRect(c+a.series.waffleColumnSpace,f+a.series.waffleRowSpace,e.w+a.series.waffleColumnSpace,e.h+a.series.waffleRowSpace,
a.series.waffleNumIcons,!0),c=g.w-a.series.waffleColumnSpace,f=g.h-a.series.waffleRowSpace,b=g.numColumns,g=g.numRows):(c=40*(f.style.zoom||1),f=c*f.style.height/f.style.width,b=Math.max(1,Math.floor((e.w+a.series.waffleColumnSpace)/(c+a.series.waffleColumnSpace))),g=Math.max(1,Math.floor((e.h+a.series.waffleRowSpace)/(f+a.series.waffleRowSpace))));var d=1===b?0:(e.w-c*b)/(b-1);e=1===g?0:(e.h-f*g)/(g-1);if(a=a.series.waffleDirection===r.RIGHT||a.series.waffleDirection===r.LEFT){var h=b;b=g;g=h}return{iconW:c,
iconH:f,numColumns:Math.min(b,1E3),numRows:Math.min(g,1E3),columnSpace:d,rowSpace:e,isColumnRowsTransposed:a}},_renderIcon:function(c,e,a,f,b,g,d){var h=d.iconW,l=d.iconH,p=d.columnSpace;d=d.rowSpace;var n=f.shapeJson||f.imageJson;a=a.createGroup();if(f.shapeJson){var v=C.shapeJsonToGFXJson(n);try{B.deserialize(a,v)}catch(q){console.log(q)}}else a.createImage({x:0,y:0,width:h,height:l,src:D.getImageData(n.fileName)}),a.rawNode.style.opacity=n.style.opacity;a.createRect({x:0,y:0,width:h+p,height:l+
d}).setFill(new A([0,0,0,.001]));var m,k;switch(g.series.waffleDirection){case r.DOWN:m=b.x+e*(h+p);k=b.y+c*(l+d);break;case r.UP:m=b.x+e*(h+p);k=b.y+b.h-(c+1)*l-c*d;break;case r.RIGHT:m=b.x+c*(h+p);k=b.y+b.h-(e+1)*l-e*d;break;case r.LEFT:m=b.x+b.w-(c+1)*h-c*p,k=b.y+b.h-(e+1)*l-e*d}a.applyTransform(z.matrix.translate(m,k));f.shapeJson&&a.applyTransform(z.matrix.scale(h/n.style.width));return a},_fillIcons:function(c,e,a,f,b,g,d){var h=d.iconW,l=d.iconH,p=d.numColumns,n=d.numRows,v=d.isColumnRowsTransposed;
a.forEach(function(a){a.openBatch()});var m=g.series.waffleNumIcons||n*p,k=0;b.forEach(function(a){k+=a.y||0});var q=1,r=b.map(function(a,d){a=c*(a.y||0)/k;g.series.waffleShowWholePictures&&(a=Math.round(m*a)/m);a=Math.max(0,Math.min(1,a));d<b.length-1&&(q-=a);return a});1<b.length&&(r[r.length-1]=q);var t=0;f.forEach(function(a,b){var c=0,d=t;t+=r[b];for(var d=d*m,f=t*m,g=0;g<n;g++)for(var k=0;k<p;k++){var q=a[c];if(!q)break;q.setClip(null);q.rawNode.style.display="none";c++;if(c>d&&c-1<f){q.rawNode.style.display=
"";var w=Math.max(0,d-(c-1)),x=Math.max(0,c-f);if(0<w||0<x){var u=e[b],y=u.shapeJson?u.shapeJson.style.width:h,u=u.shapeJson?u.shapeJson.style.height:l;v?q.setClip({x:0,y:u*x,width:y,height:u*(1-(w+x))}):q.setClip({x:y*w,y:0,width:y*(1-(w+x)),height:u})}}}});a.forEach(function(a){a.closeBatch()});return{shapes:a}},DEFAULT_ICON_SIZE:40};return t});