// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var u=function(n,p){u=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(p,m){p.__proto__=m}||function(p,m){for(var r in m)m.hasOwnProperty(r)&&(p[r]=m[r])};return u(n,p)};return function(n,p){function v(){this.constructor=n}u(n,p);n.prototype=null===p?Object.create(p):(v.prototype=p.prototype,new v)}}();
define("esri/arcade/featureset/sources/FeatureLayerMemory","require exports ../../../graphic ../support/FeatureSet ../support/IdSet ../support/shared ../../polyfill/promiseUtils ../../../geometry/Geometry ../../../geometry/geometryEngineAsync ../../../geometry/jsonUtils ../../../layers/Field".split(" "),function(u,n,p,v,m,r,e,x,t,y,w){return function(n){function b(a){var c=n.call(this,a)||this;c.source=[];a.spatialReference&&(c.spatialReference=a.spatialReference);c.types=a.types;c.geometryType=a.geometryType;
c.typeIdField=a.typeIdField;c.objectIdField=a.objectIdField;c.fields=a.fields.slice(0);c.source=a.source;c._transparent=!0;c._maxProcessing=1E3;c._wset=null;return c}__extends(b,n);b.prototype._maxQueryRate=function(){return r.defaultMaxRecords};b.prototype.load=function(){var a=this;null===this._loadPromise&&(this._loadPromise=e.create(function(c,k){a._initialiseFeatureSet();c(a)}));return this._loadPromise};b.prototype._initialiseFeatureSet=function(){this._databaseType=r.FeatureServiceDatabaseType.Standardised};
b.prototype.optimisePagingFeatureQueries=function(a){};b.prototype._allFeatures=function(){return this.source};b.prototype._isInFeatureSet=function(a){return r.IdState.InFeatureSet};b.prototype.isTable=function(){return null===this.geometryType||""===this.geometryType};b.prototype._transformSetWithIdChanges=function(a){};b.prototype._candidateIdTransform=function(a){return a};b.prototype._getSet=function(a){var c=this;return null===this._wset?this._ensureLoaded().then(function(){return c._getFilteredSet("",
null,null,null,a)}).then(function(a){return c._wset=a}):e.resolve(this._wset)};b.prototype._getFilteredSet=function(a,c,k,d,b){var h=this;try{return this._ensureLoaded().then(function(){if(h.isTable()&&c&&null!==a&&""!==a)return new m([],[],!0,null);if(null===h._wset){var d=[];h._allFeatures().forEach(function(a){void 0===a.geometry&&(a.geometry=null);var c=a.attributes[h.objectIdField];d.push(c);h._featureCache[c]=a});h._wset=new m([],d,!1,null)}var l=h._wset._known.slice(0);h._checkCancelled(b);
return h.fetchAndRefineFeaturesByWhere(l,k,b).then(function(d){h._checkCancelled(b);return null!==c?h.fetchAndRefineFeaturesSpatially(d,c,a,b).then(function(a){return new m([],a,!1,null)}):new m([],d,!1,null)})})}catch(f){return e.reject(f)}};b.prototype.executeSpatialRelationTest=function(a,c,b,d){if(null===a.geometry)return e.resolve(!1);switch(c){case "esriSpatialRelEnvelopeIntersects":return c=r.shapeExtent(b),a=r.shapeExtent(a.geometry),t.intersects(c,a);case "esriSpatialRelIntersects":return t.intersects(b,
a.geometry);case "esriSpatialRelContains":return t.contains(b,a.geometry);case "esriSpatialRelOverlaps":return t.overlaps(b,a.geometry);case "esriSpatialRelWithin":return t.within(b,a.geometry);case "esriSpatialRelTouches":return t.touches(b,a.geometry);case "esriSpatialRelCrosses":return t.crosses(b,a.geometry);case "esriSpatialRelRelation":return t.relate(b,a.geometry,d)}};b.prototype.executeWhereTest=function(a,c){return c.testFeature(a)};b.prototype.fetchAndRefineFeaturesSpatially=function(a,
c,b,d){var l=[];d=[];var h="";0<=b.indexOf("esriSpatialRelRelation")&&(h=b.split(":")[1],b="esriSpatialRelRelation");for(var f=0;f<a.length;f++){var k=this._featureFromCache(a[f]);d.push(this.executeSpatialRelationTest(k,b,c,h))}return 0===d.length?e.resolve(l):e.all(d).then(function(c){for(var b=0;b<a.length;b++)!0===c[b]&&l.push(a[b]);return l})};b.prototype.fetchAndRefineFeaturesByWhere=function(a,c,b){b=[];if(null===c)return e.resolve(a);for(var d=0;d<a.length;d++){var l=this._featureFromCache(a[d]);
this.executeWhereTest(l,c)&&b.push(a[d])}return e.resolve(b)};b.prototype._getFeatures=function(a,b,k,d){d=[];-1!==b&&void 0===this._featureCache[b]&&d.push(b);for(var c=a._lastFetchedIndex;c<a._known.length&&!(a._lastFetchedIndex+=1,void 0===this._featureCache[a._known[c]]&&(a._known[c]!==b&&d.push(a._known[c]),d.length>k));c++);return 0===d.length?e.resolve("success"):e.reject(Error("Unaccounted for Features. Not in Feature Collection"))};b.prototype._refineSetBlock=function(a,b,k){return e.resolve(a)};
b.prototype._stat=function(a,b,k,d,l,h,f){return e.resolve({calculated:!1})};b.prototype._canDoAggregates=function(a,b,k,d,l){return e.resolve(!1)};b._cloneAttr=function(a){var b={},k;for(k in a)b[k]=a[k];return b};b.create=function(a,c){var k=c.toJson(),d=a.layerDefinition.objectIdField,l=a.layerDefinition.geometryType;void 0===l&&(l=a.featureSet.geometryType);void 0===l&&(l="");var h=a.featureSet.features;if(""===d||void 0===d){for(var f=!1,e=0,q=a.layerDefinition.fields;e<q.length;e++){var g=q[e];
if("oid"===g.type||"esriFieldTypeOID"===g.type){d=g.name;f=!0;break}}if(!1===f){d="FID";f=!0;for(e=0;f;){for(var q=!0,m=0,n=a.layerDefinition.fields;m<n.length;m++)if(g=n[m],g.name===d){q=!1;break}!0===q?f=!1:(e++,d="FID"+e.toString())}a.layerDefinition.fields.push({type:"esriFieldTypeOID",name:d,alias:d});g=[];for(f=0;f<h.length;f++)g.push({geometry:a.featureSet.features[f].geometry,attributes:a.featureSet.features[f].attributes?this._cloneAttr(a.featureSet.features[f].attributes):{}}),g[f].attributes[d]=
f;h=g}}f=[];e=0;for(q=a.layerDefinition.fields;e<q.length;e++)g=q[e],g instanceof w?f.push(g):f.push(new w(g));e=[];for(q=0;q<h.length;q++)g=h[q],g.geometry&&!1===g.geometry instanceof x&&void 0===g.geometry.spatialReference&&(g.geometry.spatialReference=k),e.push(new p(null===g.geometry||void 0===g.geometry?null:y.fromJson(g.geometry),null,g.attributes));return new b({source:e,types:a.types,typeIdField:a.typeIdField,fields:f,objectIdField:d,geometryType:l,spatialReference:c})};b.prototype.canBeBigDataFeatureSet=
function(){return!1};b.prototype.shouldBeResolvedAsBigData=function(){return!1};b.prototype.queryAttachments=function(a,b,k,d){return e.resolve([])};return b}(v)});