// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var y=function(q,l){y=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(l,v){l.__proto__=v}||function(l,v){for(var q in v)v.hasOwnProperty(q)&&(l[q]=v[q])};return y(q,l)};return function(q,l){function z(){this.constructor=q}y(q,l);q.prototype=null===l?Object.create(l):(z.prototype=l.prototype,new z)}}(),__assign=this&&this.__assign||function(){__assign=Object.assign||function(y){for(var q,l=1,z=arguments.length;l<z;l++){q=arguments[l];for(var v in q)Object.prototype.hasOwnProperty.call(q,
v)&&(y[v]=q[v])}return y};return __assign.apply(this,arguments)};
define("esri/arcade/featureset/sources/FeatureLayerDynamic","require exports ../../../graphic ../../../request ../../../sniff ../../../SpatialReference ../../../urlUtils ../../Attachment ../support/cache ../support/FeatureSet ../support/IdSet ../support/sha ../support/shared ../support/stats ../../polyfill/promiseUtils ../../../geometry/Extent ../../../layers/FeatureType ../../../layers/Field ../../../tasks/query ../../../tasks/QueryTask ../../../tasks/StatisticDefinition".split(" "),function(y,q,
l,z,v,G,H,I,w,J,A,K,B,L,n,M,N,C,x,D,E){var O=!!v("esri-pbf"),P=!!v("esri-featurelayer-pbf"),S=function(){function l(b,a,c){void 0===c&&(c=null);this.url=b;this.outFields=a;this.spatialReference=c;this._url=null;this.supportsAttachments=this.supportsFormatPBF=!1;this._queryTask=this._loadPromise=null;this.currentVersion=0;this.useStandardizedQueries=!1;this.fields=[];this._url=H.urlToObject(b)}l.prototype._canFetchPBFForQuery=function(b){return O&&P&&this.supportsFormatPBF&&!b.outStatistics};l.prototype._loadMetaData=
function(b){if(null!==w.applicationCache){var a=w.applicationCache.getLayerInfo(b);if(null!==a)return a}var c=!1,g=n.create(function(a,k){z({url:b,content:{f:"json"},callbackParamName:"callback",load:function(f){null!==w.applicationCache&&!1===c&&(c=!0,w.applicationCache.setLayerInfo(b,g));a(f)},error:function(a){null!==w.applicationCache&&!1===c&&(c=!0,w.applicationCache.setLayerInfo(b,g));null!==w.applicationCache&&w.applicationCache.clearLayerInfo(b);k(a)}})});null!==w.applicationCache&&!1===c&&
(c=!0,w.applicationCache.setLayerInfo(b,g));return g};l.prototype.load=function(){var b=this;null===this._loadPromise&&(this._loadPromise=n.create(function(a,c){var g=b._url.path;b._loadMetaData(g).then(function(e){try{b._queryTask=new D(g);b.objectIdField=e.objectIdField;b.supportsAttachments=!0===e.hasAttachments;if(!b.objectIdField)for(var k=e.fields,f=0;f<k.length;f++){var m=k[f];if("esriFieldTypeOID"===m.type){b.objectIdField=m.name;break}}b.globalIdField=e.globalIdField;b.geometryType=e.geometryType;
b.typeIdField=e.typeIdField;b.fullExtent=new M(e.fullExtent);b.advancedQueryCapabilities=e.advancedQueryCapabilities||{supportsStatistics:e.supportsStatistics,supportsOrderBy:e.supportsAdvancedQueries,supportsDistinct:e.supportsAdvancedQueries};if(e.supportedQueryFormats)for(var k=0,d=e.supportedQueryFormats.split(",");k<d.length;k++)if("pbf"===d[k].replace(/^\s+|\s+$/gm,"").toLowerCase()){b.supportsFormatPBF=!0;break}!0===e.useStandardizedQueries&&(b.useStandardizedQueries=!0);void 0!==e.currentVersion&&
(b.currentVersion=e.currentVersion);if(e.types){b.types=[];for(var d=0,r=e.types;d<r.length;d++){var h=r[d],Q=new N(h);b.types.push(Q)}}e.spatialReference&&!b.spatialReference&&(b.spatialReference=new G(e.spatialReference));if(1===b.outFields.length&&"*"===b.outFields[0])for(var t=0,p=e.fields;t<p.length;t++){var h=p[t],u=new C(h);b.fields.push(u)}else for(p=0,t=e.fields;p<t.length;p++)if(h=t[p],"esriFieldTypeOID"===h.type)u=new C(h),b.fields.push(u);else{e=!1;for(var r=0,F=b.outFields;r<F.length;r++){var l=
F[r];if(h.name.toUpperCase()===l.toUpperCase()){e=!0;break}}e&&(u=new C(h),b.fields.push(u))}b.definitionExpression="";a(b)}catch(R){c(R)}},c)}));return this._loadPromise};l.prototype.queryIds=function(b){var a=this;return n.create(function(c,g){a._queryTask.executeForIds(b,c,g)})};l.prototype.queryAttachments=function(b){var a=this,c=__assign({},b,{f:"json"});0<c.objectIds.length&&(c.objectIds=c.objectIds.join(","));c.size&&(c.size=c.size.join(","));c.attachmentTypes&&(c.attachmentTypes=c.attachmentTypes.join(","));
return n.create(function(b,e){z({url:a._url.path+"/queryAttachments",content:c,callbackParamName:"callback",load:function(a){var c={};if(a&&a.attachmentGroups){var e=0;for(a=a.attachmentGroups;e<a.length;e++){var d=a[e];void 0===c[d.parentObjectId]&&(c[d.parentObjectId]=[]);for(var g=0,h=d.attachmentInfos;g<h.length;g++){var k=h[g];c[d.parentObjectId].push({id:k.id,globalId:k.globalId,name:k.name,contentType:k.contentType,size:k.size})}}}b(c)},error:function(a){e(a)}})})};return l}();return function(q){function b(a){var c=
q.call(this,a)||this;c._layer=null;c._removeGeometry=!1;c.formulaCredential=null;c._pageJustIds=!1;c._requestStandardised=!1;a.spatialReference&&(c.spatialReference=a.spatialReference);c._layer=new S(a.url,a.outFields,c.spatialReference);c._transparent=!0;c._maxProcessing=1E3;c._wset=null;void 0!==a.includeGeometry&&(c._removeGeometry=!1===a.includeGeometry);return c}__extends(b,q);b.prototype.optimisePagingFeatureQueries=function(a){this._pageJustIds=a};b.prototype._maxQueryRate=function(){return B.defaultMaxRecords};
b.prototype.convertQueryToLruCacheKey=function(a){a=B.stableStringify(a.toJson());return(new K(a,"TEXT")).getHash("SHA-1","B64")};b.prototype.load=function(){var a=this;null===this._loadPromise&&(this._loadPromise=n.create(function(c,b){a._layer.load().then(function(){try{a._initialiseFeatureSet(),c(a)}catch(e){b(e)}},function(a){b(a)})}));return this._loadPromise};b.prototype._initialiseFeatureSet=function(){null==this.spatialReference&&(this.spatialReference=this._layer.spatialReference);this.geometryType=
this._layer.geometryType;void 0===this.geometryType&&(this.geometryType="");this.fields=this._layer.fields.slice(0);if(!0===this._layer.useStandardizedQueries)this._databaseType=B.FeatureServiceDatabaseType.Standardised;else{var a=this._layer.currentVersion;void 0!==a&&null!==a&&10.5<=a&&(this._databaseType=B.FeatureServiceDatabaseType.Standardised,this._requestStandardised=!0)}this.objectIdField=this._layer.objectIdField;this.typeIdField=this._layer.typeIdField;this.types=this._layer.types};b.prototype._isInFeatureSet=
function(a){return B.IdState.InFeatureSet};b.prototype._refineSetBlock=function(a,c){return n.resolve(a)};b.prototype._candidateIdTransform=function(a){return a};b.prototype._transformSetWithIdChanges=function(a){};b.prototype._getSet=function(a){var c=this;return null===this._wset?this._ensureLoaded().then(function(){return c._getFilteredSet("",null,null,null,a)}).then(function(a){return c._wset=a}):n.resolve(this._wset)};b.prototype._runDatabaseProbe=function(a){var c=this;return n.create(function(b,
e){try{c._ensureLoaded().then(function(){try{var g=new x;g.where=a.replace("OBJECTID",c._layer.objectIdField);c._layer.queryIds(g).then(function(a){b(!0)},function(a){try{b(!1)}catch(m){e(m)}})}catch(f){e(f)}})}catch(k){e(k)}})};b.prototype._canUsePagination=function(){return void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsPagination?!0:!1};b.prototype._cacheableFeatureSetSourceKey=function(){return this._layer.url};
b.prototype._getFilteredSet=function(a,c,b,e,k){var f=this;return this.databaseType().then(function(g){if(f.isTable()&&c&&null!==a&&""!==a)return new A([],[],!0,null);if(f._canUsePagination())return f._getFilteredSetUsingPaging(a,c,b,e,k);var d="",m=!1;null!==e&&void 0!==f._layer.advancedQueryCapabilities&&null!==f._layer.advancedQueryCapabilities&&!0===f._layer.advancedQueryCapabilities.supportsOrderBy&&(d=e.constructClause(),m=!0);var h=new x;f._requestStandardised&&(h.sqlFormat="standard");h.where=
null===b?null===c?"1\x3d1":"":b.toWhereClause(g);h.spatialRelationship=f._makeRelationshipEnum(a);h.outSpatialReference=f.spatialReference;h.orderByFields=""!==d?d.split(","):null;h.geometry=null===c?null:c;h.relationParam=f._makeRelationshipParam(a);return f.executeQuery(h,"executeForIds").then(function(a){null===a&&(a=[]);f._checkCancelled(k);return new A([],a,m,null)})})};b.prototype._expandPagedSet=function(a,c,b,e,k){return this._expandPagedSetFeatureSet(a,c,b,e,k)};b.prototype._getFilteredSetUsingPaging=
function(a,c,b,e,k){var f=this;try{var m="",d=!1;null!==e&&void 0!==this._layer.advancedQueryCapabilities&&null!==this._layer.advancedQueryCapabilities&&!0===this._layer.advancedQueryCapabilities.supportsOrderBy&&(m=e.constructClause(),d=!0);return this.databaseType().then(function(e){e=null===b?null===c?"1\x3d1":"":b.toWhereClause(e);f._layer.definitionExpression&&(e=""!==e?"(("+f._layer.definitionExpression+") AND ("+e+"))":f._layer.definitionExpression);var h=f._maxQueryRate();void 0!==f._layer.maxRecordCount&&
f._layer.maxRecordCount<h&&(h=f._layer.maxRecordCount);var g=null;if(!0===f._pageJustIds)g=new A([],["GETPAGES"],d,{spatialRel:f._makeRelationshipEnum(a),relationParam:f._makeRelationshipParam(a),outFields:f._layer.objectIdField,resultRecordCount:h,resultOffset:0,geometry:null===c?"":c,where:e,orderByFields:m,returnGeometry:!1,returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}});else{var r=!0;!0===f._removeGeometry&&(r=!1);var p=f._fieldsIncludingObjectId(f._layer.outFields),
g=new A([],["GETPAGES"],d,{spatialRel:f._makeRelationshipEnum(a),relationParam:f._makeRelationshipParam(a),outFields:p.join(","),resultRecordCount:h,resultOffset:0,geometry:null===c?"":c,where:e,orderByFields:m,returnGeometry:r,returnIdsOnly:"false",internal:{set:[],lastRetrieved:0,fullyResolved:!1}})}return f._expandPagedSet(g,h,0,1,k).then(function(a){return g})})}catch(r){return n.reject(r)}};b.prototype._clonePageDefinition=function(a){return null===a?null:!0!==a.groupbypage?{groupbypage:!1,spatialRel:a.spatialRel,
relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,resultOffset:a.resultOffset,geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}:{groupbypage:!0,spatialRel:a.spatialRel,relationParam:a.relationParam,outFields:a.outFields,resultRecordCount:a.resultRecordCount,useOIDpagination:a.useOIDpagination,generatedOid:a.generatedOid,groupByFieldsForStatistics:a.groupByFieldsForStatistics,
resultOffset:a.resultOffset,outStatistics:a.outStatistics,geometry:a.geometry,where:a.where,orderByFields:a.orderByFields,returnGeometry:a.returnGeometry,returnIdsOnly:a.returnIdsOnly,internal:a.internal}};b.prototype._getPhysicalPage=function(a,c,b){var e=this;try{var g=a.pagesDefinition.internal.lastRetrieved,f=new x;this._requestStandardised&&(f.sqlFormat="standard");f.spatialRelationship=a.pagesDefinition.spatialRel;f.relationParam=a.pagesDefinition.relationParam;f.outFields=a.pagesDefinition.outFields.split(",");
f.num=a.pagesDefinition.resultRecordCount;f.start=a.pagesDefinition.internal.lastRetrieved;f.geometry=a.pagesDefinition.geometry;f.where=a.pagesDefinition.where;f.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;f.returnGeometry=a.pagesDefinition.returnGeometry;f.outSpatialReference=this.spatialReference;return this.executeQuery(f,"execute").then(function(c){e._checkCancelled(b);if(a.pagesDefinition.internal.lastRetrieved!==g)return"done";for(var d=
0;d<c.features.length;d++)void 0===c.features[d].geometry&&(c.features[d].geometry=null),a.pagesDefinition.internal.set[g+d]=c.features[d].attributes[e._layer.objectIdField];if(!1===e._pageJustIds)for(d=0;d<c.features.length;d++)e._featureCache[c.features[d].attributes[e._layer.objectIdField]]=c.features[d];c.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=g+a.pagesDefinition.resultRecordCount;return"done"})}catch(m){return n.reject(m)}};
b.prototype._fieldsIncludingObjectId=function(a){if(null===a)return[this.objectIdField];a=a.slice(0);if(-1<a.indexOf("*"))return a;for(var c=!1,b=0;b<a.length;b++)if(a[b].toUpperCase()===this.objectIdField.toUpperCase()){c=!0;break}!1===c&&a.push(this.objectIdField);return a};b.prototype._getFeatures=function(a,c,b,e){var g=this,f=[];try{-1!==c&&void 0===this._featureCache[c]&&f.push(c);if(!0===this._checkIfNeedToExpandKnownPage(a,this._maxProcessingRate(),e))return this._expandPagedSet(a,this._maxProcessingRate(),
0,0,e).then(function(d){return g._getFeatures(a,c,b,e)});for(var m=0,d=a._lastFetchedIndex;d<a._known.length;d++){a._lastFetchedIndex+=1;m++;if(void 0===this._featureCache[a._known[d]]){var r=!1;if(null!==this._layer._mode&&void 0!==this._layer._mode){var h=this._layer._mode;if(void 0!==h._featureMap[a._known[d]]){var l=h._featureMap[a._known[d]];null!==l&&(r=!0,this._featureCache[a._known[d]]=l)}}if(!1===r&&(a._known[d]!==c&&f.push(a._known[d]),f.length>=this._maxProcessingRate()-1))break}if(m>=
b&&0===f.length)break}if(0===f.length)return n.resolve("success");try{var t=new x;this._requestStandardised&&(t.sqlFormat="standard");t.objectIds=f;t.outFields=this._fieldsIncludingObjectId(this._layer.outFields);t.returnGeometry=!0;!0===this._removeGeometry&&(t.returnGeometry=!1);t.outSpatialReference=this.spatialReference;return this.executeQuery(t,"execute").then(function(a){g._checkCancelled(e);if(void 0!==a.error)return n.reject(Error(a.error));for(var c=0;c<a.features.length;c++)void 0===a.features[c].geometry&&
(a.features[c].geometry=null),g._featureCache[a.features[c].attributes[g._layer.objectIdField]]=a.features[c];return"success"})}catch(p){return n.reject(p)}}catch(p){return n.reject(p)}};b.prototype._layerUrl=function(){return this._layer.url};b.prototype.pbfSupportedForQuery=function(a){return this._layer._canFetchPBFForQuery(a)};b.prototype.executeQuery=function(a,c){var b=new D(this._layerUrl()),e="execute"===c&&this.pbfSupportedForQuery(a);e&&(a.quantizationParameters={mode:"edit"});var k=null;
if(this.recentlyUsedQueries){var f=this.convertQueryToLruCacheKey(a);(k=this.recentlyUsedQueries.getFromCache(f))&&k.isRejected()&&(k=null,this.recentlyUsedQueries.removeFromCache(f));null===k&&(k=!0!==e?b[c](a):b[c](a,null,null,{format:"pbf"}),this.recentlyUsedQueries.addToCache(f,k))}null===k&&(k=!0!==e?b[c](a):b[c](a,null,null,{format:"pbf"}));return k};b.prototype._getDistinctPages=function(a,c,b,e,k,f,m,d,r){var h=this;return this._ensureLoaded().then(function(){for(var g=b.parseTree.column,
l=0;l<h._layer.fields.length;l++)if(h._layer.fields[l].name.toLowerCase()===g.toLowerCase()){g=h._layer.fields[l].name;break}return h.databaseType().then(function(l){var u=new x;h._requestStandardised&&(u.sqlFormat="standard");l=null===f?null===k?"1\x3d1":"":f.toWhereClause(l);h._layer.definitionExpression&&(l=""!==l?"(("+h._layer.definitionExpression+") AND ("+l+"))":h._layer.definitionExpression);u.where=l;u.spatialRelationship=h._makeRelationshipEnum(e);u.relationParam=h._makeRelationshipParam(e);
u.geometry=null===k?null:k;u.returnDistinctValues=!0;u.returnGeometry=!1;u.outFields=[g];return h.executeQuery(u,"execute").then(function(l){h._checkCancelled(r);if(!l.hasOwnProperty("features"))return n.reject(Error("Unnexected Result querying statistics from layer"));for(var u=!1,p=0;p<h._layer.fields.length;p++)if(h._layer.fields[p].name===g){"esriFieldTypeDate"===h._layer.fields[p].type&&(u=!0);break}for(p=0;p<l.features.length;p++){if(u){var t=l.features[p].attributes[g];null!==t?d.push(new Date(t)):
d.push(t)}else d.push(l.features[p].attributes[g]);if(d.length>=m)break}return 0===l.features.length?d:l.features.length===h._layer.maxRecordCount&&d.length<m?h._getDistinctPages(a+l.features.length,c,b,e,k,f,m,d,r).then(function(a){return{calculated:!0,result:a}}):d})})})};b.prototype._distinctStat=function(a,c,b,e,k,f,m){return this._getDistinctPages(0,a,c,b,e,k,f,[],m).then(function(a){return{calculated:!0,result:a}})};b.prototype.isTable=function(){return null===this._layer.geometryType||""===
this._layer.geometryType||void 0===this._layer.geometryType};b.prototype._countstat=function(a,c,b,e,k){var f=this;return this.databaseType().then(function(a){var d=new x;f._requestStandardised&&(d.sqlFormat="standard");if(f.isTable()&&b&&null!==c&&""!==c)return{calculated:!0,result:0};a=null===e?null===b?"1\x3d1":"":e.toWhereClause(a);f._layer.definitionExpression&&(a=""!==a?"(("+f._layer.definitionExpression+") AND ("+a+"))":f._layer.definitionExpression);d.where=a;d.where=a;d.spatialRelationship=
f._makeRelationshipEnum(c);d.relationParam=f._makeRelationshipParam(c);d.geometry=null===b?null:b;d.returnGeometry=!1;return f.executeQuery(d,"executeForCount").then(function(a){return{calculated:!0,result:a}})})};b.prototype._stats=function(a,c,b,e,k,f,m){var d=this;return this._ensureLoaded().then(function(){var g=d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsSqlExpression,h=d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsStatistics,
l=d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsDistinct;return"count"===a?l?d._countstat(a,b,e,k,m):{calculated:!1}:!1===h||!1===c.isSingleField()&&!1===g||!1===c.isStandardized()?""!==b||null!==k?{calculated:!1}:d._manualStat(a,c,f,m):"distinct"===a?!1===l?""!==b||null!==k?{calculated:!1}:d._manualStat(a,c,f,m):d._distinctStat(a,c,b,e,k,f,m):d.databaseType().then(function(f){if(d.isTable()&&e&&null!==b&&""!==b)return{calculated:!0,result:null};var h=new x;d._requestStandardised&&
(h.sqlFormat="standard");var g=null===k?null===e?"1\x3d1":"":k.toWhereClause(f);d._layer.definitionExpression&&(g=""!==g?"(("+d._layer.definitionExpression+") AND ("+g+"))":d._layer.definitionExpression);h.where=g;h.spatialRelationship=d._makeRelationshipEnum(b);h.relationParam=d._makeRelationshipParam(b);h.geometry=null===e?null:e;g=new E;g.statisticType=L.decodeStatType(a);g.onStatisticField=c.toWhereClause(f);var m=g.outStatisticFieldName="ARCADE_STAT_RESULT";h.returnGeometry=!1;h.outStatistics=
[g];return d.executeQuery(h,"execute").then(function(a){if(!a.hasOwnProperty("features")||0===a.features.length)return n.reject(Error("Unnexected Result querying statistics from layer"));for(var c=!1,b=0;b<a.fields.length;b++)if("ARCADE_STAT_RESULT"===a.fields[b].name.toUpperCase()){m=a.fields[b].name;"esriFieldTypeDate"===a.fields[b].type&&(c=!0);break}return c?(c=a.features[0].attributes[m],null!==c&&(c=new Date(a.features[0].attributes[m])),{calculated:!0,result:c}):{calculated:!0,result:a.features[0].attributes[m]}})})})};
b.prototype._stat=function(a,c,b,e,k,f,m){return this._stats(a,c,b,e,k,f,m)};b.prototype._canDoAggregates=function(a,c,b,e,k){var f=this;return this._ensureLoaded().then(function(a){a=!1;var b=f._layer.advancedQueryCapabilities&&!0===f._layer.advancedQueryCapabilities.supportsSqlExpression;void 0!==f._layer.advancedQueryCapabilities&&null!==f._layer.advancedQueryCapabilities&&!0===f._layer.advancedQueryCapabilities.supportsStatistics&&!0===f._layer.advancedQueryCapabilities.supportsOrderBy&&(a=!0);
if(a)for(var e=0;e<c.length-1;e++)null!==c[e].workingexpr&&(!1===c[e].workingexpr.isStandardized()?a=!1:!1===c[e].workingexpr.isSingleField()&&!1===b&&(a=!1));return!1===a?!1:!0})};b.prototype._makeRelationshipEnum=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?"esriSpatialRelRelation":a};b.prototype._makeRelationshipParam=function(a){return 0<=a.indexOf("esriSpatialRelRelation")?a.split(":")[1]:""};b.prototype._getAggregatePagesDataSourceDefinition=function(a,c,b,e,k,f,m){var d=this;return this._ensureLoaded().then(function(g){return d.databaseType().then(function(h){var g=
"",l=!1,p=!1;null!==f&&void 0!==d._layer.advancedQueryCapabilities&&null!==d._layer.advancedQueryCapabilities&&!0===d._layer.advancedQueryCapabilities.supportsOrderBy&&(g=f.constructClause(),p=!0);void 0!==d._layer.advancedQueryCapabilities&&null!==d._layer.advancedQueryCapabilities&&!1===d._layer.advancedQueryCapabilities.supportsPagination&&(p=!1,l=!0,g=d._layer.objectIdField);for(var r=[],n=0;n<c.length;n++){var q=new E;q.onStatisticField=null!==c[n].workingexpr?c[n].workingexpr.toWhereClause(h):
"";q.outStatisticFieldName=c[n].field;q.statisticType=c[n].toStatisticsName();r.push(q)}""===g&&(g=a.join(","));n=d._maxQueryRate();void 0!==d._layer.maxRecordCount&&d._layer.maxRecordCount<n&&(n=d._layer.maxRecordCount);h=null===k?null===e?"1\x3d1":"":k.toWhereClause(h);d._layer.definitionExpression&&(h=""!==h?"(("+d._layer.definitionExpression+") AND ("+h+"))":d._layer.definitionExpression);return new A([],["GETPAGES"],p,{groupbypage:!0,spatialRel:d._makeRelationshipEnum(b),relationParam:d._makeRelationshipParam(b),
outFields:["*"],useOIDpagination:l,generatedOid:m,resultRecordCount:n,resultOffset:0,groupByFieldsForStatistics:a,outStatistics:r,geometry:null===e?null:e,where:h,orderByFields:g,returnGeometry:!1,returnIdsOnly:!1,internal:{lastMaxId:-1,set:[],lastRetrieved:0,fullyResolved:!1}})})})};b.prototype._getAgregagtePhysicalPage=function(a,b,g){var c=this;try{var k=a.pagesDefinition.where;!0===a.pagesDefinition.useOIDpagination&&(k=""!==k?"("+k+") AND ("+a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString()+
")":a.pagesDefinition.generatedOid+"\x3e"+a.pagesDefinition.internal.lastMaxId.toString());var f=a.pagesDefinition.internal.lastRetrieved,m=new x;this._requestStandardised&&(m.sqlFormat="standard");m.where=k;m.spatialRelationship=a.pagesDefinition.spatialRel;m.relationParam=a.pagesDefinition.relationParam;m.outFields=a.pagesDefinition.outFields;m.outStatistics=a.pagesDefinition.outStatistics;m.geometry=a.pagesDefinition.geometry;m.groupByFieldsForStatistics=a.pagesDefinition.groupByFieldsForStatistics;
m.num=a.pagesDefinition.resultRecordCount;m.start=a.pagesDefinition.internal.lastRetrieved;m.returnGeometry=a.pagesDefinition.returnGeometry;m.orderByFields=""!==a.pagesDefinition.orderByFields?a.pagesDefinition.orderByFields.split(","):null;return this.isTable()&&m.geometry&&m.spatialRelationship?n.resolve([]):this.executeQuery(m,"execute").then(function(b){c._checkCancelled(g);if(!b.hasOwnProperty("features"))return n.reject(Error("Unnexected Result querying aggregates from layer"));var e=[];if(a.pagesDefinition.internal.lastRetrieved!==
f)return n.resolve([]);for(var d=0;d<b.features.length;d++)void 0===b.features[d].geometry&&(b.features[d].geometry=null),a.pagesDefinition.internal.set[f+d]=b.features[d].attributes[a.pagesDefinition.generatedOid];for(d=0;d<b.features.length;d++)e.push(new l({attributes:b.features[d].attributes,geometry:null}));!0===a.pagesDefinition.useOIDpagination?0===b.features.length?a.pagesDefinition.internal.fullyResolved=!0:a.pagesDefinition.internal.lastMaxId=b.features[b.features.length-1].attributes[a.pagesDefinition.generatedOid]:
b.features.length!==a.pagesDefinition.resultRecordCount&&(a.pagesDefinition.internal.fullyResolved=!0);a.pagesDefinition.internal.lastRetrieved=f+a.pagesDefinition.resultRecordCount;return e})}catch(d){return n.reject(d)}};b.create=function(a,c,g){return new b({url:a,outFields:null===c?["*"]:c,spatialReference:g})};b.prototype.canBeBigDataFeatureSet=function(){return!0};b.prototype.shouldBeResolvedAsBigData=function(){return!1};b.prototype.expressAsArcadeScriptImpl=function(a,b,g){this.arcadeAssignNextScriptStepIdentifiers(g);
a=this.arcadeAssignNextGlobalIdentifier(g);b[a]={name:a,type:"FeatureLayer",params:{url:this._layer.url,definitionExpression:this._layer.definitionExpression,fields:this._layer.outFields}};g.featuresetsyms.push(a);return""};b.prototype.queryAttachments=function(a,b,g,e){var c=this;if(this._layer.supportsAttachments){var f={objectIds:[a]};if(b&&0<b||g&&0<g)f.size=[b&&0<b?b:0,g&&0<g?g:b+1];e&&0<e.length&&(f.attachmentTypes=e);return this._layer.queryAttachments(f).then(function(b){var d=[];if(b&&b[a]){var e=
c._layer._url.path;b[a].forEach(function(b){d.push(new I(b.id,b.name,b.contentType,b.size,e+"/"+a.toString()+"/attachments/"+b.id.toString()))})}return d})}return n.resolve([])};return b}(J)});