// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var q=function(l,h){q=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,m){h.__proto__=m}||function(h,m){for(var n in m)m.hasOwnProperty(n)&&(h[n]=m[n])};return q(l,h)};return function(l,h){function r(){this.constructor=l}q(l,h);l.prototype=null===h?Object.create(h):(r.prototype=h.prototype,new r)}}();
define("esri/arcade/featureset/sources/FeatureLayerMemoryMap","require exports ../../../graphic ../support/FeatureSet ../support/IdSet ../support/shared ../../polyfill/promiseUtils ../../../geometry/geometryEngineAsync".split(" "),function(q,l,h,r,m,n,g,p){return function(l){function b(a){var c=l.call(this,a)||this;c.declaredClass="esri.layers.featureset.sources.FeatureLayerMemory";c._removeGeometry=!1;c._overrideFields=null;c.allf=null;a.spatialReference&&(c.spatialReference=a.spatialReference);
c._transparent=!0;c._maxProcessing=1E3;c._layer=a.layer;c._wset=null;if(!1===c._layer.loaded)throw Error("Can only create Feature FeatureSets from Loaded FeatureLayers. Use FeatureLayer or FeatureCollection classes");void 0!==a.outFields&&(c._overrideFields=a.outFields);void 0!==a.includeGeometry&&(c._removeGeometry=!1===a.includeGeometry);return c}__extends(b,l);b.prototype._maxQueryRate=function(){return n.defaultMaxRecords};b.prototype.end=function(){return this._layer};b.prototype.optimisePagingFeatureQueries=
function(a){};b.prototype.load=function(){var a=this;null===this._loadPromise&&(this._loadPromise=g.create(function(c,d){a._initialiseFeatureSet();c(a)}));return this._loadPromise};b.prototype._initialiseFeatureSet=function(){if(!this._layer.getMap())throw Error("Can only use featuresets with layers attached to map");null==this.spatialReference&&(this.spatialReference=this._layer.getMap().spatialReference);this.geometryType=this._layer.geometryType;this.fields=this._layer.fields.slice(0);var a=this._layer.getOutFields();
if(1!==a.length||"*"!==a[0]){for(var c=[],d=0,e=this.fields;d<e.length;d++){var f=e[d];if("esriFieldTypeOID"===f.type)c.push(f);else for(var b=0,k=a;b<k.length;b++){var g=k[b];if(g.toLowerCase()===f.name.toLowerCase()){c.push(f);break}}}this.fields=c}if(null!==this._overrideFields)if(1===this._overrideFields.length&&"*"===this._overrideFields[0])this._overrideFields=null;else{c=[];a=[];d=0;for(e=this.fields;d<e.length;d++)if(f=e[d],"esriFieldTypeOID"===f.type)c.push(f),a.push(f.name);else for(b=0,
k=this._overrideFields;b<k.length;b++)if(g=k[b],g.toLowerCase()===f.name.toLowerCase()){c.push(f);a.push(f.name);break}this.fields=c;this._overrideFields=a}this.objectIdField=this._layer.objectIdField;this._databaseType=n.FeatureServiceDatabaseType.Standardised;this.typeIdField=this._layer.typeIdField;this.types=this._layer.types};b.prototype._isInFeatureSet=function(a){return n.IdState.InFeatureSet};b.prototype._transformSetWithIdChanges=function(a){};b.prototype._candidateIdTransform=function(a){return a};
b.prototype._getSet=function(a){var c=this;return null===this._wset?this._ensureLoaded().then(function(){return c._getFilteredSet("",null,null,null,a)}).then(function(a){return c._wset=a}):g.resolve(this._wset)};b.prototype._getFilteredSet=function(a,c,d,b,f){var e=this;try{return this._ensureLoaded().then(function(){if(null===e._wset){var b=[];e._allFeatures().forEach(function(a){void 0===a.geometry&&(a.geometry=null);var c=a.attributes[e._layer.objectIdField];b.push(c);e._featureCache[c]=a});e._wset=
new m([],b,!1,null)}var g=e._wset._known.slice(0);e._checkCancelled(f);return e.fetchAndRefineFeaturesByWhere(g,d,f).then(function(d){e._checkCancelled(f);return null!==c?e.fetchAndRefineFeaturesSpatially(d,c,a,f).then(function(a){return new m([],a,!1,null)}):new m([],d,!1,null)})})}catch(k){return g.reject(k)}};b.prototype.executeSpatialRelationTest=function(a,c,d,e){if(null===a.geometry)return g.resolve(!1);switch(c){case "esriSpatialRelEnvelopeIntersects":return c=n.shapeExtent(d),a=n.shapeExtent(a.geometry),
p.intersects(c,a);case "esriSpatialRelIntersects":return p.intersects(d,a.geometry);case "esriSpatialRelContains":return p.contains(d,a.geometry);case "esriSpatialRelOverlaps":return p.overlaps(d,a.geometry);case "esriSpatialRelWithin":return p.within(d,a.geometry);case "esriSpatialRelTouches":return p.touches(d,a.geometry);case "esriSpatialRelCrosses":return p.crosses(d,a.geometry);case "esriSpatialRelRelation":return p.relate(d,a.geometry,e)}};b.prototype.executeWhereTest=function(a,c){return c.testFeature(a)};
b.prototype.fetchAndRefineFeaturesSpatially=function(a,c,d,e){var b=[];e=[];var h="";0<=d.indexOf("esriSpatialRelRelation")&&(h=d.split(":")[1],d="esriSpatialRelRelation");for(var k=0;k<a.length;k++){var l=this._featureFromCache(a[k]);e.push(this.executeSpatialRelationTest(l,d,c,h))}return 0===e.length?g.resolve(b):g.all(e).then(function(c){for(var d=0;d<a.length;d++)!0===c[d]&&b.push(a[d]);return b})};b.prototype.fetchAndRefineFeaturesByWhere=function(a,c,d){d=[];if(null===c)return g.resolve(a);
for(var b=0;b<a.length;b++){var f=this._featureFromCache(a[b]);this.executeWhereTest(f,c)&&d.push(a[b])}return g.resolve(d)};b.prototype._getFeatures=function(a,c,d,b){b=[];-1!==c&&void 0===this._featureCache[c]&&b.push(c);for(var e=a._lastFetchedIndex;e<a._known.length&&!(a._lastFetchedIndex+=1,void 0===this._featureCache[a._known[e]]&&(a._known[e]!==c&&b.push(a._known[e]),b.length>d));e++);return 0===b.length?g.resolve("success"):g.reject(Error("Unaccounted for Features. Not in Feature Collection"))};
b.prototype._refineSetBlock=function(a,c,b){return g.resolve(a)};b.prototype._stat=function(a,c,b,e,f,h,k){return g.resolve({calculated:!1})};b.prototype._canDoAggregates=function(a,c,b,e,f){return g.resolve(!1)};b._cloneAttr=function(a){var c={},b;for(b in a)c[b]=a[b];return c};b.prototype.cloneAttr=function(a){for(var c={},b=0,e=this.fields;b<e.length;b++){var f=e[b];c[f.name]=a[f.name]}return c};b.prototype._allFeatures=function(){var a=this;null==this.allf&&(this.allf=[],this._layer.graphics.forEach(function(b){a.allf.push(new h(!0===
a._removeGeometry?null:b.geometry,null,a.cloneAttr(b.attributes)))}));return this.allf};b.prototype.canBeBigDataFeatureSet=function(){return!1};b.prototype.shouldBeResolvedAsBigData=function(){return!1};b.prototype.queryAttachments=function(a,b,d,e){return g.resolve([])};return b}(r)});