// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/sections/dynamicSettings/SectionDynamicSettingsBuilder","dojo/_base/declare dojo/_base/lang dojo/on esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct dijit/Destroyable esri/dijit/geoenrichment/ReportPlayer/PlayerSelect esri/dijit/geoenrichment/ReportPlayer/PlayerThemes esri/dijit/geoenrichment/ReportPlayer/ReportPlayerState ./SettingsProvider ./SectionDynamicSettings ./SectionDynamicFilter ./supportClasses/ToolbarAdjuster ./dynamicInfographic/_DynamicInfographicSettingsBuilder esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/PopupUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(n,p,k,l,m,d,q,r,t,f,u,v,w,x,y,z,A,e,g,B,h){h=h.geoenrichment.dijit.ReportPlayer.SectionDynamicSettingsBuilder;return n(q,{_section:null,_settingsWidget:null,_filterWidget:null,_settingsToolbar:null,_buttonBar:null,_settingsButton:null,_filterButton:null,_filtersOnIndicator:null,_featureSelectDiv:null,_stats:null,_onButtonBarShowCallbacks:null,_needRequerySettingsSet:!1,constructor:function(a,b){this._section=a;p.mixin(this,b);this._createSettings()},_createSettings:function(){var a=this;
this._provideSettingsStats().then(function(){a._stats&&(a._tryAddFeatureSelect(),a._tryAddLocatorExportButton(),a._tryAddFilterButton(),a._tryAddSettingsButton(),a.onButtonsCreated())})},_provideSettingsStats:function(){var a=this;return u.getSettingsSet(this._section).then(function(b){a._stats=b})},_tryAddFeatureSelect:function(){var a=this;if(this._stats.multiFeatureSettings&&this._stats.multiFeatureSettings.canSelectFeatures){var b=this._section.viewModel.dynamicReportInfo.analysisAreas.map(function(a,
b){return{value:b,label:a.shortName||a.name}}),c=(new r({options:b,value:0,allowRepetitiveSelection:!1,onChange:function(b){a._needRequerySettingsSet=!0;a._setFiltersOnIndicatorVisible(!1);var d=a._section.toJson();d.currentFeatureIndex=b.value;a._section.fromJson(d);c.closePopup();a._settingsWidget&&a._settingsWidget.setVisualState(a._section.getVisualState());a._filterWidget&&(a._stats.dynamicInfographicSettings?l(y.provideDynamicInfogarphicSettings(a._section),function(b){a._filterWidget.updateDynamicInfographicFilter(b.filter)}):
a._filterWidget.setVisualState(a._section.getVisualState()))}})).placeAt(this._provideSettingsToolbar().featureSelectDiv);c.setTheme(t.DARK)}},_tryAddLocatorExportButton:function(){var a=this;if(this._stats.hasExport&&!this._section.isDataDrillingView){var b=this._createButton("dijitInline sectionDynamicSettings_exportButton");k(b,"click",function(){a._stats.locatorSettings.exportSettings.exportToExcel()});B.setTooltipToNode(b,h.exportInfographicPanel)}},_settingsStateTimeoutH:null,_filterPopupShown:!1,
_tryAddFilterButton:function(){var a=this,b=!1;this._stats.hasFilter&&(this._filterButton=this._createButton("dijitInline sectionDynamicSettings_filterButton",function(){b||(b=!0,g.makePopup(function(){return l(a._needRequerySettingsSet&&a._provideSettingsStats(),function(){a._needRequerySettingsSet=!1;return a._provideFilterWidget()})},a._section,a._filterButton,{orient:["before","below"],onShow:function(){a._filterPopupShown=!0;clearTimeout(a._settingsStateTimeoutH);f.isViewingDynamicSettings=!0},
onClose:function(){a._filterPopupShown=!1;a._settingsPopupShown||(a._settingsStateTimeoutH=setTimeout(function(){f.isViewingDynamicSettings=!1}))}}))}))},_settingsPopupShown:!1,_tryAddSettingsButton:function(){var a=this,b=!1;this._stats.hasViewSettings&&(this._settingsButton=this._createButton("dijitInline sectionDynamicSettings_settingsButton",function(){b||(b=!0,g.makePopup(function(){return l(a._needRequerySettingsSet&&a._provideSettingsStats(),function(){a._needRequerySettingsSet=!1;return a._provideSettingsWidget()})},
a._section,a._settingsButton,{orient:["before","below"],onShow:function(){a._settingsPopupShown=!0;clearTimeout(a._settingsStateTimeoutH);f.isViewingDynamicSettings=!0},onClose:function(){a._settingsPopupShown=!1;a._filterPopupShown||(a._settingsStateTimeoutH=setTimeout(function(){f.isViewingDynamicSettings=!1}))}}))}))},_createButton:function(a,b){return d.create("div",{"class":a},this._provideSettingsToolbar(b).buttonBar)},_provideSettingsToolbar:function(a){function b(a){c._section.isDataDrillingView&&
(a=!0);c._buttonBar.style.display=!a||!c._section.isDataDrillingView&&f.isViewingDataDrillingZoom?"none":"";a&&c._onButtonBarShowCallbacks.forEach(function(a){return a()});a?c._adjustToolbarPosition():c._closePopup();m[a?"add":"remove"](c._section.domNode,"hasDynamicSettingsToolbar")}var c=this;this._settingsToolbar||(this._settingsToolbar=d.create("div",{"class":"sectionDynamicSettings_toolbar"},this._section.domNode),this._featureSelectDiv=d.create("div",{"class":"dijitInline"},this._settingsToolbar),
this._buttonBar=d.create("div",{"class":"dijitInline sectionDynamicSettings_buttonBar"},this._section.dynamicSettingsToolbarRoot||this._settingsToolbar),this._onButtonBarShowCallbacks=[],b(!1),z.isMobileDevice()?(A.addNoDragClickHandler(this._section.domNode,function(){b(!0)}),this.own(k(document.body,"touchstart",function(a){c.isMouseOver(a)||b(!1)}))):this.own(k(document.body,"mousemove",function(){b(c.isMouseOver())})));a&&this._onButtonBarShowCallbacks.push(a);return{buttonBar:this._buttonBar,
featureSelectDiv:this._featureSelectDiv}},_closePopup:function(){g.close(this._settingsWidget);g.close(this._filterWidget)},_provideSettingsWidget:function(){var a=this;this._settingsWidget||(this._settingsWidget=new v({chartSettings:a._stats.chartSettings&&a._stats.chartSettings.viewSettings,comparisonSettings:a._stats.comparisonSettings&&a._stats.comparisonSettings.viewSettings,locatorSettings:a._stats.locatorSettings&&a._stats.locatorSettings.viewSettings,mapSettings:a._stats.mapSettings&&a._stats.mapSettings.viewSettings,
onSortChart:function(b){a._closePopup();a._section.getChart().sortChart(b)},onChartToTable:function(){a._closePopup();a._section.getChart().chartToTable()},onTableToChart:function(){a._closePopup();a._section.getChart().tableToChart()},onCalcStateChanged:function(b){a._closePopup();a._section.setChartCalculationState(b)},onShowChart:function(b){a._closePopup();a._section.getInfographic().getInnerInfographic().setChartView(b)},onLocatorSummaryChanged:function(b){a._section.getInfographic().getInnerInfographic().setVisibleSummaryFields(b.visibleFields)},
onLegendVisibilityChanged:function(b){a._section.getMapImages()[0].setLegendVisible(b)},onClosePopup:function(){a._closePopup()}}),this.own(this._settingsWidget),this._settingsWidget.setVisualState(this._section.getVisualState()));return this._settingsWidget},_provideFilterWidget:function(){function a(){return b._section.getInfographic().getInnerInfographic()}var b=this;this._filterWidget||(this._filterWidget=new w({areaDetailsFilter:b._stats.areaDetailsSettings&&b._stats.areaDetailsSettings.filter,
chartFilter:b._stats.chartSettings&&b._stats.chartSettings.filter,comparisonFilter:b._stats.comparisonSettings&&b._stats.comparisonSettings.filter,dynamicInfographicFilter:b._stats.dynamicInfographicSettings&&b._stats.dynamicInfographicSettings.filter,locatorFilter:b._stats.locatorSettings&&b._stats.locatorSettings.filter,onChartFilterChanged:function(a){b._section.getChart().setFilterRanges(a.filterRanges);b._setFiltersOnIndicatorVisible(a.hasFiltersOn)},onLocatorFilterChanged:function(c){a().setSearchText(c.searchText);
a().setFilterRanges(c.filterRanges);b._setFiltersOnIndicatorVisible(c.hasFiltersOn)},onAreaDetailsFilterChanged:function(c){a().setSearchText(c.searchText);b._setFiltersOnIndicatorVisible(c.hasFiltersOn)},onComparisonFilterChanged:function(c){a().setFilterRanges(c.filterRanges);b._setFiltersOnIndicatorVisible(c.hasFiltersOn)},onDynamicInfographicFilterChanged:function(c){a().setFilterRanges(c.filterRanges);b._setFiltersOnIndicatorVisible(c.hasFiltersOn)},onClosePopup:function(){b._closePopup()}}),
this.own(this._filterWidget),this._filterWidget.setVisualState(this._section.getVisualState()));return this._filterWidget},_setFiltersOnIndicatorVisible:function(a){this._filtersOnIndicator&&d.destroy(this._filtersOnIndicator);this._filtersOnIndicator=a&&d.create("div",{"class":"sectionDynamicSettings_filtersOnIndicator",innerHTML:h.on},this._filterButton)},setVisualState:function(a){this._settingsWidget&&this._settingsWidget.setVisualState(a);this._filterWidget&&this._filterWidget.setVisualState(a)},
notifyShown:function(){this._adjustToolbarPosition()},_panelScale:null,setPanelScale:function(a){this._panelScale=a;this._adjustToolbarPosition()},_adjustToolbarPosition:function(){this._stats&&(this._stats.locatorSettings&&!this._stats.locatorSettings.hasTitle||this._stats.areaDetailsSettings&&!this._stats.areaDetailsSettings.hasTitle||this._stats.comparisonSettings)&&m.add(this._settingsToolbar,"needsTopOffset");this._buttonBar&&1<this._buttonBar.children.length&&m.add(this._buttonBar,"hasMultipleButtons");
x.adjustToolbarPosition({toolbar:this._settingsToolbar,section:this._section,panelScale:this._panelScale})},isMouseOver:function(a){return e.isMouseOver(this._section.domNode,{event:a})||e.isMouseOver(this._settingsToolbar,{event:a})||this._settingsWidget&&(e.isMouseOver(this._settingsWidget.domNode,{event:a})||e.isMouseOver(this._settingsWidget.domNode.parentNode,{event:a}))||this._filterWidget&&(e.isMouseOver(this._filterWidget.domNode,{event:a})||e.isMouseOver(this._filterWidget.domNode.parentNode,
{event:a}))},onButtonsCreated:function(){},destroy:function(){d.destroy(this._settingsToolbar)}})});