// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/dataDrilling/DataDrillingLibrary","dojo/_base/lang dojo/promise/all ./_FieldInfoBuilder ../../../supportClasses/tableJson/TableJsonUtil ../../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoNameUtil ../../../../dataProvider/supportClasses/dataCollections/DataCollectionsLoader ./_config ./EnrichUtil".split(" "),function(k,t,u,v,w,p,g,q){function r(a){return"string"===typeof a?a.split(",").map(function(a){return a+
"/"}):a}var f={};q.ddLibrary=f;f.getDrillingOptions=function(a,b,c){if(b){var d=function(){function n(a,b){return f&&-1!==f.indexOf(a)?!0:d&&d.some(function(e){return-1!==e.indexOf(a)||-1!==e.indexOf(b)})}if("string"===typeof b){var e=g.getById(a+"."+b);return e?[e]:null}var d=b.usedFields||c&&c(b),d=d&&d.map(function(a){return a.toUpperCase()});if(!b.variableID&&!d)return null;var f=b.variableID&&b.variableID.toUpperCase(),e=g.LIBRARY[a],l;for(l in e){var k=l.toUpperCase(),h=w.createFieldNameFromVariable(l).toUpperCase();
if(n(k,h))return e[l]}return null}();d&&d.forEach(function(a){f._provideStateData(a)});return d}};f.getDrillingOptionByStandardId=function(a,b){};f.getDrillingOptionInfo=function(a,b,c,d,n,e,g){a=(a=f.getDrillingOptions(a,b,g))&&a.filter(function(a){return a.name===c})[0];if(!a)return null;!e&&a.defaultState&&(e=a.defaultState);e=e&&e.charAt(0)||"n";var h;a.calcGroup&&(h=k.clone(a.calcGroup),h.value=e+"/");d=v.createSingleCellTable({fieldInfo:a.stateData[e].fieldInfo,width:d,height:n});return{calculationStatesGroup:h,
tableJson:k.clone(d),enrichInfos:q._getStandardEnrichInfosForTableInfo(a,!0)}};f._provideStateData=function(a){if(!a.stateData){var b=a.states?k.clone(a.fieldInfo):a.fieldInfo;a.stateData={n:{fieldInfo:a.fieldInfo}};a.fieldInfo.isChart&&f._updateChartJsonForState(a.fieldInfo.chartJson,"n",a.stateSettings&&a.stateSettings.n);a.states&&(a.states=r(a.states),a.states.forEach(function(c){c=c.charAt(0);if("n"!==c){var e=k.clone(b);a.stateData[c]={fieldInfo:e};e.isChart&&f._updateChartJsonForState(e.chartJson,
c,a.stateSettings&&a.stateSettings[c])}}),a.calcGroup=f.createCalculationStatesGroup(a.states));for(var c in a.stateData){var d=a.stateData[c];d.fieldInfo.isChart&&d.fieldInfo.chartJson.seriesItems.forEach(function(a){a.points.forEach(function(b){u.provideFieldInfoForChartPoint(b,a,1===d.fieldInfo.chartJson.seriesItems.length,c,d.fieldInfo.chartJson.comparisonInfo&&d.fieldInfo.chartJson.comparisonInfo.calculatorName)})})}delete a.states;delete a.stateSettings;delete a.fieldInfo}};f._updateChartJsonForState=
function(a,b,c){c&&c.title?a.visualProperties.title.text=c&&c.title:"n"!==b&&(a.visualProperties.title.text+=" ("+g.STATE_LOCALIZATION_MAP_SHORT[b]+")");a.visualProperties.yAxis&&(a.visualProperties.yAxis.title=c&&c.yAxisTitle||("n"===b?"":g.STATE_LOCALIZATION_MAP[b]),"i"===b&&(a.visualProperties.yAxis.baseLineValue=100));"n"!==b&&(a.visualProperties.dataLabelsDecimals="p"===b?1:0);"p"===b&&(a.visualProperties.dataLabelsShowValuePercentSymbol=!0,a.visualProperties.yAxis&&(a.visualProperties.yAxis.showPercentSymbol=
!0,a.visualProperties.yAxis.showSymbolForAllLabels=!0));c&&c.isCurrency&&(a.visualProperties.dataLabelsShowValueCurrencySymbol=!0,a.visualProperties.yAxis&&(a.visualProperties.yAxis.showCurrencySymbol=!0,a.visualProperties.yAxis.showSymbolForAllLabels=!0));k.mixin(a.visualProperties,c&&c.visualProps)};f.createCalculationStatesGroup=function(a){if(a)return a=r(a),{states:{ids:a,names:a.slice(),labels:a.map(function(a){return g.STATE_LOCALIZATION_MAP_SHORT[a.charAt(0)]})},value:a[0]}};var h,m;f.init=
function(a){if(h)return h;var b=m=m||g.collectSubstitutionVariables(),c={};if(p.canLoad())return h=t(Object.keys(b).map(function(a){var e=b[a].fields,d=b[a].variables;return p.loadVariables({countryID:a,hierarchy:"census",outFields:e,forceLowerCase:!0}).then(function(b){var f={fields:e,variables:[]};d.forEach(function(a){var c=b.fullNameToVariableCache[a];c.fullName=a;f.variables.push(c)});c[a]=f})})).then(function(){g.replaceSubstitutionVariables(c)});if(a&&a.variableProvider&&a.countryID&&b[a.countryID]){var d=
{fields:b[a.countryID].fields,variables:[]};c[a.countryID]=d;b[a.countryID].variables.forEach(function(b){var c=a.variableProvider.getVariableVintage(b);d.variables.push({fullName:b,vintage:c||"N/A"})});g.replaceSubstitutionVariables(c)}h=!0};f.getSubstitutionVariables=function(a,b){return(a=(m=m||g.collectSubstitutionVariables())[a])&&a.variables};return f});