// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/_ClusteredColumnsBase","dojo/_base/lang dojo/_base/array dojo/_base/declare dojox/charting/plot2d/CartesianBase dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/lang/functional dojox/lang/functional/reversed dojox/lang/utils ./labelsRendering/_ColumnsLabelRenderingFix ./animation/_ClusteredColumnsAnimation ./_MinVisibleColumn".split(" "),function(t,y,B,C,D,u,E,F,x,G,H,I){var J=F.lambda("item.purgeGroup()");return B("dojox.charting.plot2d.Columns",
[C,D,G,H,I],{_mainShapes:null,_animationInfos:null,defaultParams:{gap:0,animate:null},optionalParams:{minBarSize:1,maxBarSize:1},constructor:function(a,b){this.opt=t.clone(t.mixin(this.opt,this.defaultParams));x.updateWithObject(this.opt,b);x.updateWithPattern(this.opt,b,this.optionalParams);this.animate=this.opt.animate;this.renderingOptions={"shape-rendering":"crispEdges"}},getSeriesStats:function(){var a=u.collectSimpleStats(this.series,function(a){return null==a});a.hmin-=.5;a.hmax+=.5;return a},
render:function(a,b){if(!this.chart.isPreRenderMode){this.resetEvents();this.dirty=this.isDirty();var e;this.dirty&&(y.forEach(this.series,J),this._eventSeries={},this.cleanGroup(),e=this.getGroup(),E.forEachRev(this.series,function(a){a.cleanGroup(e)}));var d=this.chart.theme,l=this._hScaler.scaler.getTransformerFromModel(this._hScaler),c=this._vScaler.scaler.getTransformerFromModel(this._vScaler),g=c(Math.max(d.series.baseLineValue||0,this._vScaler.bounds.lower)),m=this.events(),n=this.getBarProperties();
this._mainShapes=[];this._animationInfos=[];for(var z=this.extractValues(this._hScaler),z=this.rearrangeValues(z,c,g),c=this.series.length-1;0<=c;--c){var f=this.series[c];if(this.dirty||f.dirty){f.cleanGroup();var t=d.next("column",[this.opt,f]),u=Array(f.data.length);e=f.group;for(var v=y.some(f.data,function(a){return"number"===typeof a||a&&!a.hasOwnProperty("x")}),x=v?Math.min(f.data.length,Math.ceil(this._hScaler.bounds.to)):f.data.length,h=v?Math.max(0,Math.floor(this._hScaler.bounds.from-1)):
0;h<x;++h){var k=f.data[h];if(null!=k){var q=this.getValue(k,h,c,v),A=z[c][h],p;this.opt.styleFunc||"number"!==typeof k?(p="number"!==typeof k?[k]:[],this.opt.styleFunc&&p.push(this.opt.styleFunc(k)),p=d.addMixin(t,"column",p,!0)):p=d.post(t,"column");if(1<=n.width){var r={x:b.l+l(q.x+.5)+n.gap+n.thickness*this._getXShift(c,d),y:a.height-b.b-g-Math.max(A,0),width:n.width,height:Math.abs(A)},r=this._drawColumn(e,k,r,p,a,b,f,g,h),w=r.shape;d.series.isEditMode&&(w.rawNode.style.cursor="pointer");w.value=
k;this._mainShapes.push(w);r=r.rect;m&&(q={element:"column",index:h,run:f,shape:w,cx:q.x+.5,cy:q.y,x:v?h:f.data[h].x,y:v?f.data[h]:f.data[h].y},this._connectEvents(q),u[h]=q);this.createLabel(e,k,r,p,a,b);this.animate&&(k={shape:w,voffset:a.height-b.b-g,vsize:A},this._animationInfos.push(k),this._animateColumn(k))}}}this._eventSeries[f.name]=u;f.dirty=!1}else d.skip(),this._reconnectEvents(f.name)}this._renderLabels(p,a,b,e);this.dirty=!1;return this}},getMainShapes:function(){return this._mainShapes},
_drawColumn:function(a,b,e,d,l,c,g,m,n){},getValue:function(a,b,e,d){d?(e="number"===typeof a?a:a.y,a=b):(e=a.y,a=a.x-1);return{x:a,y:e}},extractValues:function(a){for(var b=[],e=this.series.length-1;0<=e;--e){var d=this.series[e];if(this.dirty||d.dirty){var l=y.some(d.data,function(a){return"number"==typeof a||a&&!a.hasOwnProperty("x")}),c=l?Math.max(0,Math.floor(a.bounds.from-1)):0,l=l?Math.min(d.data.length,Math.ceil(a.bounds.to)):d.data.length,g=b[e]=[];g.min=c;for(g.max=l;c<l;++c){var m=d.data[c];
g[c]=this.isNullValue(m)?0:"number"==typeof m?m:m.y}}}return b},rearrangeValues:function(a,b,e){for(var d=0,l=a.length;d<l;++d){var c=a[d];if(c)for(var g=c.min,m=c.max;g<m;++g){var n=c[g];c[g]=this.isNullValue(n)?0:b(n)-e}}return a},getBarProperties:function(){var a=this._getClusterSize(),b=u.calculateBarSize(this._hScaler.bounds.scale,this.opt,a);return{gap:b.gap,width:b.size,thickness:b.size,clusterSize:a}},_getClusterSize:function(){var a=this.series.length;return this.chart.theme.series.renderColumnBarsInOppositeDirections?
Math.round(a/2):a},_getXShift:function(a,b){return b.series.renderColumnBarsInOppositeDirections?a>=this.series.length/2?a-this.series.length/2:a:a}})});