// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/plots/Ring","dojo/_base/lang dojo/_base/declare dojox/charting/plot2d/Base dojox/charting/plot2d/_PlotEvents dojox/charting/plot2d/common dojox/gfx/matrix dojox/lang/functional dojox/lang/utils ./animation/_RingAnimation ./labelsRendering/LabelsUtil".split(" "),function(t,w,B,C,D,E,k,u,F,x){var G={createPath:function(a,b,h,l,d,g,e,k,n){var q=function(k){var f={cx:h.cx,cy:h.cy,r:b},n=a.createCircle(f).setStroke({color:e.series.ringBackgroundColor||
"#DDDDDD",width:g}),m=l+2*k*Math.PI,p=h.cx+b*Math.cos(l),r=h.cy+b*Math.sin(l),q=h.cx+b*Math.cos(m),v=h.cy+b*Math.sin(m);return{shape:a.createPath().moveTo(p,r).arcTo(b,b,0,.5<k,!0,q,v).setStroke({color:d,width:g}),bgShape:n,end:m,ac:f}};n.push({sliceIndex:k,func:q});return q}};return w([B,C,F],{_animationInfos:null,defaultParams:{labels:!0,ticks:!1,fixed:!0,precision:1,labelOffset:20,labelStyle:"default",radGrad:"native",fanSize:5,startAngle:0,animate:null},optionalParams:{radius:0,omitLabels:!1,
labelFunc:null,stroke:{},outline:{},shadow:{},fill:{},filter:{},styleFunc:null,font:"",fontColor:"",labelWiring:{}},_lastRenderResults:null,constructor:function(a,b){this.opt=t.clone(this.defaultParams);u.updateWithObject(this.opt,b);u.updateWithPattern(this.opt,b,this.optionalParams);this.axes=[];this.run=null;this.dyn=[];this.runFilter=[]},clear:function(){this.inherited(arguments);this.dyn=[];this.run=null;return this},setAxis:function(a){return this},addSeries:function(a){this.run=a;return this},
getSeriesStats:function(){return t.delegate(D.defaultStats)},getRequiredColors:function(){return this.run?this.run.data.length:0},getRenderResults:function(){return this._lastRenderResults},render:function(a,b){if(!this.dirty)return this;this.resetEvents();this.dirty=!1;this._eventSeries={};this.cleanGroup();var h=this.group,l=this.chart.theme;if(!this.run||!this.run.data.length)return this;var d=(a.width-b.l-b.r)/2,g=(a.height-b.t-b.b)/2,e=Math.min(d,g),t=E._degToRad(90),n,q=this.events(),p=this.run.data.map(function(c,
a){"number"!==typeof c&&c.hidden&&(this.runFilter.push(a),c.hidden=!1);return this.runFilter.some(function(c){return c===a})?"number"===typeof c?0:{y:0,text:c.text}:c},this);this.dyn=[];"radius"in this.opt&&(e=this.opt.radius);var f={cx:b.l+d,cy:b.t+g,r:e},d=k.map(p,"x ? Math.max(x.y, 0) : 0");if(k.every(d,"\x3c\x3d 0"))return h.createCircle(f).setStroke(l.series.stroke),this.dyn=d.map(function(){return{}}),this;d=k.map(d,"/this",k.foldl(d,"+",0));this.opt.labels&&(n=d.map(function(c,a){return x.getLabelInfo(this,
p[a],l,{forceOneLine:!0,minSpace:20})},this));var u=k.map(p,function(c,a){a=[this.opt,this.run];null!=c&&"number"!==typeof c&&a.push(c);this.opt.styleFunc&&a.push(this.opt.styleFunc(c));return l.next("slice",a,!0)},this),m=0;this.opt.labels&&(n.forEach(function(a){m=Math.max(m,a.box.w)}),g=f.cx+e+m+b.r-a.width,0<g&&(b=f.cx-e,b>g?f.cx-=g:(g=(g-b)/2,f.cx-=b+g,e-=g)));f.cx-=f.cx-e-(a.width-(2*e+m))/2;var y=Array(d.length),r=Math.min(e/10,.5*e/d.length),z=e,e=e-r/2,v=[],A=[];this._animationInfos=[];d.some(function(a,
b){a=Math.max(a,.001);var c=p[b],d=u[b],g;g=d.series.fill;a=G.createPath(h,e,f,t,g,r,d,b,this._animationInfos)(a);shape=a.shape;l.series.isEditMode&&(shape.rawNode.style.cursor="pointer");A.push(a.ac);this.dyn.push({fill:g,stroke:d.series.stroke});q&&(c={element:"slice",index:b,run:this.run,shape:shape,x:b,y:"number"===typeof c?c:c.y,cx:f.cx,cy:f.cy,cr:e},this._connectEvents(c),y[b]=c);v.push({x:f.cx,y:f.cy+e});e-=r+3;return!1},this);this.opt.labels&&(v.forEach(function(a,b){b=n[b];h.createPath().moveTo(a.x-
5,a.y).lineTo(a.x+z-5,a.y).setStroke(l.series.labelWiring);this.renderLabel({x:a.x+z,y:a.y-b.box.h/2,text:b.getText({forceOneLine:!0,spaceToWidth:m})})},this),l.series.show100PercentLabel&&this._show100PercentLabel(l,e,f));var w=0;this._eventSeries[this.run.name]=k.map(p,function(a){return 0>=a?null:y[w++]});this._lastRenderResults={labels:this.opt.labels,slicePies:A,maxLabelWidth:m};this.opt.animate&&this._renderAnimation(h,d);return this},_show100PercentLabel:function(a,b,h){a=x.getSimpleLabelInfo({text:"100%",
font:a.series.dataLabelsFont,fontSize:Math.min(50,.6*b),fontColor:a.series.dataLabelsColor});this.renderLabel({x:h.cx-a.box.w/2,y:h.cy-a.box.h/2,text:a.text}).style.opacity="0.5"},renderLabel:function(a){a=x.renderHTMLLabel(this.chart,a.x,a.y,a.text);this.htmlElements.push(a);return a}})});