// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/ChartJsonUtil","dojo/_base/lang ./ThemeCalculator ./ChartTypes ./ChartDataLabelsTypes ../legends/ChartLegendPlacements ../legends/ChartLegendTypes ./cleanUp/_ChartJsonCleaner ./cleanUp/_ChartJsonPrettifier ./plots/supportClasses/GaugeLabelPlacement ./plots/supportClasses/WaffleLabelPlacement ./plots/supportClasses/WaffleDirections ../../../dataProvider/supportClasses/AreaDataUtil esri/dijit/geoenrichment/utils/ObjectUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(d,f,k,p,l,q,m,r,t,u,v,n,c,g){g=g.geoenrichment.dijit.ReportPlayer.ChartContainer;var h={getDefaultChartSettings:function(a){a=a||{};var b=d.mixin({},a.font),e=d.mixin({},a.font);delete e.fontSize;return{isChart:!0,type:a.chartType||k.COLUMN,isMultiFeatureChart:!!a.isMultiFeatureChart,seriesItems:a.seriesItems||[],visualProperties:{width:a.width||400,height:a.height||300,barBorders:!1,view3D:!1,origin:0,backgroundColor:void 0,backgroundImageData:void 0,panelBackgroundColor:void 0,title:{text:"",
align:"center",style:d.mixin({},b),verticalShift:0},xAxis:{show:!0,hideLine:!1,showTicks:!0,ticksInside:!1,hideLabels:!1,title:"",titleStyle:d.mixin({},b),style:d.mixin({},b),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,placement:void 0},yAxis:{show:!0,hideLine:!1,showTicks:!0,ticksInside:!1,hideLabels:!1,title:"",titleStyle:d.mixin({},
b),style:d.mixin({},b),labelsAngle:0,lineColor:void 0,gridLines:!1,gridLinesCentered:!1,gridLinesColor:void 0,gridLinesOpacity:1,gridLinesThickness:.5,gridLinesStyle:void 0,gridStripes:!1,gridStripesColor:void 0,gridStripesColorAlt:void 0,hideBaseLine:!1,baseLineColor:void 0,baseLineOpacity:1,baseLineThickness:.5,baseLineStyle:void 0,baseLineValue:0,showPercentSymbol:!1,showCurrencySymbol:!1,showSymbolForAllLabels:!1,showValuesAsWeightsInSeries:!1,placement:void 0},legend:{type:q.SERIES,series:{placement:l.NONE,
placementOffset:10,hasBorder:!0,labelParts:"Label",style:d.mixin({},b),symbol:void 0,hideOthers:!1,showComparison:!1},minMax:{placement:l.NONE,placementOffset:3,titleStyle:d.mixin({},e),minVariableLabelStyle:d.mixin({},e),maxVariableLabelStyle:d.mixin({},e)}},isStacked:!1,columnThickness:f.DEFAULT_COLUMN_THICKNESS,columnBarGap:void 0,columnBarOpacity:1,renderColumnBarsInOppositeDirections:!1,showColumnBarBackground:!1,columnBarBackgroundColor:void 0,columnBarBackgroundOpacity:1,columnBarLineColor:void 0,
columnBarLineOpacity:1,columnBarLineThickness:0,columnBarLineStyle:void 0,lineThickness:f.DEFAULT_LINE_THICKNESS,fillLineArea:!1,lineAreaOpacity:1,donutHolePercent:f.DEFAULT_DONUT_HOLE_PERCENT,donutGap:f.DEFAULT_DONUT_GAP,donutArcPercent:f.DEFAULT_DONUT_ARC_PERCENT,gaugeHolePercent:f.DEFAULT_GAUGE_HOLE_PERCENT,gaugeRangeMin:void 0,gaugeRangeMax:void 0,gaugeGap:f.DEFAULT_GAUGE_GAP,gaugeStartAngle:f.DEFAULT_GAUGE_ANGLE,gaugeArcPercent:f.DEFAULT_GAUGE_ARC_PERCENT,gaugeLabelPlacement:t.INSIDE,gaugeLabelStyle:d.mixin({},
e),gaugeShowArrow:!1,gaugeArrowLineColor:void 0,gaugeArrowFillColor:void 0,gaugeConditionalStylingOthers:!1,gaugeConditionalStylingLabel:!1,gaugeShowFromToLabels:!1,gaugeFromLabelStyle:d.mixin({},e),gaugeToLabelStyle:d.mixin({},e),waffleDirection:v.DOWN,waffleShowWholePictures:!1,waffleRangeMin:void 0,waffleRangeMax:void 0,waffleLabelPlacement:u.BOTTOM,waffleLabelOffset:10,waffleHideValue:!1,waffleHideLabel:!1,waffleShowLabelAbove:!1,waffleValueStyle:d.mixin({},e),waffleLabelStyle:d.mixin({},e),waffleColumnSpace:5,
waffleRowSpace:5,waffleConditionalStylingOthers:!1,waffleConditionalStylingValue:!1,waffleConditionalStylingLabel:!1,waffleNumIcons:void 0,ringBackgroundColor:void 0,columnBarShowWholePictures:!1,dataLabels:p.NONE,dataLabelsShowLabelUnder:!1,dataLabelsDecimals:0,dataLabelsStyle:d.mixin({},b),dataLabelsLabelStyle:null,dataLabelsAltColor:null,dataLabelsEnableAltColor:!1,dataLabelsInside:!1,dataLabelsStackedInColumns:!1,dataLabelsHorizontalAlign:"center",dataLabelsVerticalAlign:"middle",dataLabelsShowValuePercentSymbol:!1,
dataLabelsShowValueCurrencySymbol:!1,dataLabelsAngle:0,dataLabelsMaxWidth:void 0,chartIcons:void 0,floatingIcons:void 0,showAxisIcons:!1,showChartIcons:!1,floatingTexts:void 0,sorting:void 0,conditionalStyling:void 0},comparisonInfo:void 0}},provideDefaultValueForMissing:function(a,b){b=h.getDefaultChartSettings(b);c.populateObject(a,b);return a},cleanUpJson:function(a,b){return m.cleanUpJson(a,b)},prettifyJson:function(a,b){return r.prettifyJson(a,b)},supportsVisualProperty:function(a,b,e){return m.supportsVisualProperty(b,
a,e)},enrichVisualPropertiesWithThemeSettings:function(a,b){a=d.clone(a);a.backgroundColor=a.backgroundColor||b.backgroundColor;c.populateObject(a.title.style,b.titleStyle);a.xAxis&&(c.populateObject(a.xAxis.style,b.xAxis.axisStyle),c.populateObject(a.xAxis.titleStyle,b.xAxis.titleStyle),a.xAxis.lineColor=a.xAxis.lineColor||b.xAxis.lineColor,a.xAxis.gridLinesColor=a.xAxis.gridLinesColor||b.xAxis.gridLinesColor,a.xAxis.gridLinesStyle=a.xAxis.gridLinesStyle||b.xAxis.gridLinesStyle,a.xAxis.gridStripesColor=
a.xAxis.gridStripesColor||b.xAxis.gridStripesColor,a.xAxis.gridStripesColorAlt=a.xAxis.gridStripesColorAlt||b.xAxis.gridStripesColorAlt,c.populateObject(a.yAxis.style,b.yAxis.axisStyle),c.populateObject(a.yAxis.titleStyle,b.yAxis.titleStyle),a.yAxis.lineColor=a.yAxis.lineColor||b.yAxis.lineColor,a.yAxis.gridLinesColor=a.yAxis.gridLinesColor||b.yAxis.gridLinesColor,a.yAxis.gridLinesStyle=a.yAxis.gridLinesStyle||b.yAxis.gridLinesStyle,a.yAxis.gridStripesColor=a.yAxis.gridStripesColor||b.yAxis.gridStripesColor,
a.yAxis.gridStripesColorAlt=a.yAxis.gridStripesColorAlt||b.yAxis.gridStripesColorAlt,a.yAxis.baseLineColor=a.yAxis.baseLineColor||b.yAxis.baseLineColor,a.yAxis.baseLineStyle=a.yAxis.baseLineStyle||b.yAxis.baseLineStyle);a.legend&&(c.populateObject(a.legend.series.style,b.legendStyle),a.legend.minMax&&(c.populateObject(a.legend.minMax.titleStyle,b.minMaxLegend.titleStyle),c.populateObject(a.legend.minMax.minVariableLabelStyle,b.minMaxLegend.minVariableLabelStyle),c.populateObject(a.legend.minMax.maxVariableLabelStyle,
b.minMaxLegend.maxVariableLabelStyle)));c.populateObject(a.dataLabelsStyle,b.dataLabelsStyle);c.populateObject(a.dataLabelsLabelStyle,a.dataLabelsStyle);a.dataLabelsAltColor=a.dataLabelsAltColor||b.dataLabelsAltColor;c.populateObject(a.gaugeLabelStyle,b.gauge&&b.gauge.dataLabelStyle);a.gaugeArrowLineColor=a.gaugeArrowLineColor||b.gauge&&b.gauge.arrowIndicator.lineColor;a.gaugeArrowFillColor=a.gaugeArrowFillColor||b.gauge&&b.gauge.arrowIndicator.backgroundColor;c.populateObject(a.waffleValueStyle,
b.waffle&&b.waffle.dataValueStyle);c.populateObject(a.waffleLabelStyle,b.waffle&&b.waffle.dataLabelStyle);a.ringBackgroundColor=a.ringBackgroundColor||b.ring&&b.ring.ringBackground&&b.ring.ringBackground.backgroundColor;a.columnBarBackgroundColor=a.columnBarBackgroundColor||b.columnBarBackground&&b.columnBarBackground.backgroundColor;return a},createChartPoint:function(a,b,e,d,c){a={color:e||"",label:void 0!==b?b||"":a&&a.alias,fieldInfo:a,iconFieldInfo:d,captionFieldInfo:c};e&&f.setPointColor(a,
e);return a},getGaugeOthersPoint:function(a){return{label:a&&a.label||g.gaugeOthers,color:a&&a.color}},getWaffleOthersPoint:function(a){return{label:a&&a.label||g.waffleOthers,color:a&&a.color,iconFieldInfo:a&&a.iconFieldInfo}}},w=[{headers:{data:{AREA_DESC:g.oneMile}}},{headers:{data:{AREA_DESC:g.threeMiles}}},{headers:{data:{AREA_DESC:g.fiveMiles}}}];h.getSeriesItemsForMultiFeatureChart=function(a,b,e){if(!b)return b;e=e||w;var c=b[0];return k.isLineLike(a)?e.map(function(a){var b=d.clone(c);b.color=
c.points[0].color;b.points.forEach(function(a){delete a.color});b.label=n.getAreaDataValue({areaDataObject:a,fieldName:"AREA_DESC"})||"";return b}):c.points.map(function(a){return{label:a.label,thickness:c.thickness,points:e.map(function(b){return h.createChartPoint(a.fieldInfo,n.getAreaDataValue({areaDataObject:b,fieldName:"AREA_DESC"})||"",a.color||c.color)})}})};h.getOriginalPointByMultiFeatureIndexes=function(a,b,c){return a[0].points[b]};return h});