// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var h=function(c,d){h=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(d,e){d.__proto__=e}||function(d,e){for(var c in e)e.hasOwnProperty(c)&&(d[c]=e[c])};return h(c,d)};return function(c,d){function k(){this.constructor=c}h(c,d);c.prototype=null===d?Object.create(d):(k.prototype=d.prototype,new k)}}();
define("esri/arcade/featureset/support/BigDataFeatureSetIterator","require exports ../../../graphic ./FeatureSetIterator ../../polyfill/promiseUtils ../../../geometry/jsonUtils".split(" "),function(h,c,d,k,e,l){return function(c){function g(b,a){b=c.call(this,b,a)||this;b._currentPage=null;b._iteratorStarted=!1;b._indexInCurrentPage=0;b._noMorePages=!1;b._script=null;b._featuresetMoniker="";return b}__extends(g,c);g.prototype.reset=function(){this._currentPage=null;this._iteratorStarted=!1;this._indexInCurrentPage=
0;this._featuresetMoniker=""};g.prototype.next=function(){var b=this;!1===this._iteratorStarted&&this.requestFirstPage().then(function(){return b.handleFeatureFromPage()});return this.handleFeatureFromPage()};g.prototype.handleFeatureFromPage=function(){var b=this;if(null===this._currentPage)return e.resolve(null);if(this._indexInCurrentPage<this._currentPage.length){this._indexInCurrentPage++;var a=this._currentPage[this._indexInCurrentPage-1];if(null!==a&&!(a instanceof d)){var f=null;null!==a.geometry&&
(f=this._script.spatialReference,f.toJson?f=f.toJson():f.toJson&&(f=f.toJson()),a.geometry.spatialReference=f,f=l.fromJson(a.geometry));a=new d({geometry:f,attributes:a.attributes});this._currentPage[this._indexInCurrentPage-1]=a}return e.resolve(a)}return 0===this._currentPage.length?(this._noMorePages=!0,this._currentPage=null,this._indexInCurrentPage=0,e.resolve(null)):this.requestNextPage().then(function(){return b.handleFeatureFromPage()})};g.prototype.requestFirstPage=function(){var b=this;
this._indexInCurrentPage=0;this._currentPage=[];return this._parent.top(1E3).expressAsArcadeScript().then(function(a){a.script+="\n return "+a.featuresetIdentifier+";\n";b._script=a;a=b._parent.sourceGeoAnalyticsProvider();return null===a?e.reject(Error("No Big Data Provider")):a.executeFeatureSetPageRequest(b._script.script,b._script.globals,b._script.spatialReference,"").then(function(a){b._featuresetMoniker=a.moniker;b._currentPage=a.records;return b._iteratorStarted=!0})})};g.prototype.requestNextPage=
function(){var b=this;this._indexInCurrentPage=0;this._currentPage=[];var a=this._parent.sourceGeoAnalyticsProvider();return null===a?e.reject(Error("No Big Data Provider")):a.executeFeatureSetPageRequest(this._script.script,this._script.globals,this._script.spatialReference,this._featuresetMoniker).then(function(a){b._currentPage=a.records;return!0})};g.prototype.count=function(){var b=this;return-1!==this._parent._totalCount?e.resolve(this._parent._totalCount):this._parent.count().then(function(a){b._parent._totalCount=
a;return b._parent._totalCount})};return g}(k)});