// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/templateJsonUtils/fieldInfo/_FieldInfoPreviewRenderer","dojo/string ./utils ./FieldInfoPreviewSampleUtil ./FieldInfoPreviewAttributeUtil ../../conditionalStyling/ConditionalStyleUtil esri/dijit/geoenrichment/utils/ObjectUtil esri/dijit/geoenrichment/utils/DateUtil esri/dijit/geoenrichment/ReportPlayer/countryConfig dojo/i18n!esri/nls/jsapi ../../../../_devConfig".split(" "),function(l,p,q,r,t,u,v,g,h,w){h=h.geoenrichment.dijit.ReportPlayer.FieldInfoPreview;
var x={percent:[10,15,20,25,33,46,72,90,95],percentSmall:[2,3,4,5,6,7],index:[80,99,105,111,113,118,121,130],number:[1150,2013,5006,10135,20456,36813],numberSep:[1150,2013,5006,10135,20456,36813],numberSmall:[10,5,3,7,15]},y=/^MEDAGE|^AVGHHSZ|^UNEMPRT|ECYHSZAVG|ECYPTAMED/,m={percent:{MP19013a_B:72,MP19014a_B:70,EMP_TO_POP:25,NOHS:10,HSG:20,SC:30,BGPD:40},percentSmall:{UNEMPRT_CY:5},index:{},number:{MEDHINC_CY:55650,TOTPOP_CY:20456,TOTHH_CY:8546,MEDDI_CY:38290,S01_BUS:11256,S01_EMP:60382,PCI_CY:30382,
MEDNW_CY:88548,MEDVAL_CY:352430,X3004_A:5682,ACSMEDCRNT:1227,X5001_A:1762,X1003_A:4073,X4100_A:543,X8001_A:4538,X1130_A:3465,X7001_A:1568,X9008_A:246,X9073_A:158,X9074_A:326,X9045_A:42,POPGRWCYCY:1.05,POPGRWCYFY:1.12,ECYPTAPOP:20456,ECYHNIMED:55650},numberSep:{MEDHINC_CY:55650,TOTPOP_CY:20456,TOTHH_CY:8546,MEDDI_CY:38290,S01_BUS:11256,S01_EMP:60382,PCI_CY:30382,MEDNW_CY:88548,MEDVAL_CY:352430,X3004_A:5682,ACSMEDCRNT:1227,X5001_A:1762,X1003_A:4073,X4100_A:543,X8001_A:4538,X1130_A:3465,X7001_A:1568,
X9008_A:246,X9073_A:158,X9074_A:326,X9045_A:42,ECYPTAPOP:20456,ECYHNIMED:55650},numberSmall:{AVGHHSZ_CY:2,MEDAGE_CY:36,ECYHSZAVG:2,ECYPTAMED:36},string:{TSEGNAME:"Bright Young Professionals",TLIFECODE:"L8",TLIFENAME:"Middle Ground",TSEGCODE:"8A",CONAME:"Coffee",NAICS:"1234",SIC:"5678",ADDR:"380 New York St, Redlands, CA",STATE:"CA",STATE_NAME:"California",ZIP:"92373",ZIP4:"92373",CITY:"Redlands",STREET:"New York st.",DIRECTION:"SW",FRNCOD:"24"}},z={"Employee/ Population Ratio":"EMP_TO_POP","No High School Diploma":"NOHS",
"High School Graduate":"HSG","Some College":"SC","Bachelors/Grad/Prof Degree":"BGPD"},n={};return{getValuePreview:function(b,a){return b.hasVariable||b.script?this._getVariableOrScriptPreview(b,a):this._getNonVariablePreview(b,a)},_getVariableOrScriptPreview:function(b,a){function e(b){return{formattedValue:b,value:b,formatFunction:null,isUnavailableData:!1}}function f(a,c){function d(a){a=0<b.decimals?a+.5432123456789:Math.round(a);return u.formatNumber(a,{places:b.decimals||0,noSeparator:!b.useThousandsSeparator})}
c=a;c=0<b.decimals?Number((c+.5432123456789).toFixed(b.decimals)):Math.round(c);return{formattedValue:d(a),value:c,formatFunction:function(a){return d(a)},isUnavailableData:!1}}var c=this._getSampleCacheType(b);if(w.preview.bigValues&&("number"===c||"numberSep"===c))return f(1E12,c);if(a.getPreviewValueFunction)return"percent"!==c&&(c="number"),a=a.getPreviewValueFunction(),a=a.fields&&a.fields[b.name]||a,f(a[c],c);a=q.findNonEmptySample(b);if("string"===typeof a)return e(a);if("number"===typeof a)return f(a,
c);var k=b.type||b.isSiteAttribute&&b.attribute.type;a=b.isSiteAttribute&&r.getAttributePreviewValue(b.attribute);if("esriFieldTypeDate"===k)return c=new Date,a&&c.setTime(a),e(v.formatDateShort(c));if("esriFieldTypeString"===k)return e(m.string[b.isDataLayerAttribute?b.attribute.name:b.variableID]||a||h.sampleTextValue);if("number"===typeof a)return f(a,c);a=n[c]=n[c]||{};var k=b.name+";"+b.decimals,d=a[k];if(!d){var d=m[c],g;g=b.variableID?b.variableID:b.script&&z[b.script.alias];d=d[g];d||(d=x[c],
d=d[Math.round((d.length-1)*Math.random())]);d=a[k]=d}return f(d,c)},_getSampleCacheType:function(b){var a=b.statefulName?"p"===b.statefulName.charAt(0):b.showPercent,e=b.statefulName&&"i"===b.statefulName.charAt(0),f=b.hasVariable&&y.test(b.variableID);return a?f?"percentSmall":"percent":e?"index":f?"numberSmall":b.useThousandsSeparator?"numberSep":"number"},_getNonVariablePreview:function(b,a){a.getPreviewValueFunction?(a=a.getPreviewValueFunction(),a=a.fields&&a.fields[b.name]||a,b=a.formattedValue||
a.number):"headers.AREA_DESC"===b.name&&-1<a.currentFeatureIndex?(b=1+2*a.currentFeatureIndex,b=1===b?g.getSingleUnits()?"1 "+g.getSingleUnits():l.substitute(h.fieldPreviewAreaDescWithRadiusSingular,{radius:b}):g.getPluralUnits()?b+" "+g.getPluralUnits():l.substitute(h.fieldPreviewAreaDescWithRadiusPlural,{radius:b})):b=p.fields.getPreview(b.name,a.isGraphicReport,a.isMultiFeature)||b.alias;return{formattedValue:b,value:b,formatFunction:null,isUnavailableData:!1}},getConditionalStylePreview:function(b,
a){if(b.triggerJson&&void 0!==a.rowIndex&&(a=b.triggerJson.cases[a.rowIndex%b.triggerJson.cases.length])){b=t.styleFromSetters(a.setters);var e;1===a.compareInfos.length?(e=Number(a.compareInfos[0].value),a=a.compareInfos[0].operator,"\x3e"===a?e++:"\x3c"===a&&e--):2===a.compareInfos.length&&(e=(Number(a.compareInfos[1].value)+Number(a.compareInfos[0].value))/2);return{style:b,value:e}}return null}}});