// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/DataProviderGE","dojo/_base/declare dojo/_base/lang esri/dijit/geoenrichment/promise/all esri/dijit/geoenrichment/when ./dataProvider/_CommandSupport ./dataProvider/_SerializationSupport ./dataProvider/_ServerSerializationSupport ./dataProvider/supportClasses/AnalysisAreaUtil ./dataProvider/supportClasses/AnalysisAreaJsonUtil ./dataProvider/supportClasses/CustomReportsManager ./dataProvider/supportClasses/TemplateJsonLoader ./dataProvider/supportClasses/ReportDataProcessor ./dataProvider/supportClasses/InfographicOptionsProvider ./dataProvider/supportClasses/AreasPreprocessor ./dataProvider/supportClasses/GEUtil ./dataProvider/supportClasses/attachments/DefaultAttachmentsStore ./dataProvider/supportClasses/attachments/CustomAttachmentsStore ./dataProvider/supportClasses/PortalManager ./dataProvider/supportClasses/VariablesUtil ./dataProvider/commands/mapToImage/MapToURLUtil ./core/themes/ThemeLibrary ./core/themes/ReportThemes esri/dijit/geoenrichment/ReportPlayer/countryConfig esri/dijit/geoenrichment/utils/ProjectionUtil".split(" "),
function(u,h,k,l,v,w,x,y,q,f,r,g,z,A,m,B,C,D,E,F,G,t,n,H){return u([v,w,x],{analysisAreasLimit:-1,cacheTemplates:!0,printMapTaskUrl:null,resetReportItemsCache:!0,_infographicOptionsProvider:null,constructor:function(a){h.mixin(this,a);this._infographicOptionsProvider=new z},_getAttachmentsStore:function(a){return(new B(a)).initialize()},getCustomReports:function(a){return f.getCustomReports(a)},_currentContext:null,getReportData:function(a,e){var c=this;e=e||function(){};var b=h.mixin({},a);b.variables&&
(b.hierarchy=b.hierarchy||"census");c.resetReportItemsCache&&f.resetCache();c._currentContext=b;b.analysisAreas=q.areasFromJson(b.analysisAreas);b.combinedAreasInfo=b.combinedAreasInfo&&q.combinedAreasInfoFromJson(b.combinedAreasInfo)||{};y.populateCombinedAreasInfo(b.combinedAreasInfo,b.analysisAreas);b.fieldData={runReportTaskID:null,metadata:{},areaData:[],errors:[]};return k([l(f.tryFindReportIdByAlias(b),function(a){b.reportID=a||b.reportID}),this._discoverPortal(b),function(){return b.variables&&
l(E.preprocessVariables(b.variables,b.portalUrl),function(a){b.variables=a})}()]).then(function(){return l(A.preprocessAreas(b,{analysisAreasLimit:c.analysisAreasLimit}),function(){e(.25);setTimeout(function(){c._onCreateReportStarted()});var a={initGE:m.initialize(),countryInfo:m.getCountryInfo(b.countryID),infographicOptions:c._infographicOptionsProvider.getInfographicOptions(b),attachmentsStore:b.attachmentsProvider?C(b.attachmentsProvider):c._getAttachmentsStore(b.analysisAreas)};b.reportID?(a.reportObject=
f.getCustomReportByID(b),a.templateJsonInfo=r.getTemplateJsonByID(b,c.cacheTemplates),a.runReportResult=g.runReportAndGetData(b)):b.variables&&(a.reportObject=f.getFakeCustomReportByContext(b),a.templateJsonInfo=r.createTemplateJsonFromVariables(b),a.runReportResult=g.runReportFromVariables(b));return k(a).then(function(a){var d=a.reportObject,c=a.infographicOptions,f=a.attachmentsStore,p=a.templateJsonInfo.templateJson,h=a.templateJsonInfo.templateVariableProvider,k=a.runReportResult;e(.75);if(!p||
!d||!b.fieldData)return null;g.applyRunReportAndGetDataResults(k,b);n.setCountry(a.countryInfo.country);n.setHierarchyID(d.hierarchy);n.setGeographiesModel(a.countryInfo.geographiesModels[n.getHierarchyID()]);return l(f&&g.populateReportDataFromAttachmentsStore(b,f),function(){e(1);p.theme||(p.theme=G.getReportThemeById(d.isGraphicReport?t.GRAPHIC:t.CLASSIC));return{isClassic:!d.isGraphicReport,isMultiFeature:d.isMultiFeature&&1<b.analysisAreas.length,reportType:d.type,reportTitle:d.title,templateJson:p,
reportObject:d,fieldData:b.fieldData,analysisAreas:b.analysisAreas,combinedAreasInfo:b.combinedAreasInfo,reverseAnalysisAreasOnMap:b.reverseAnalysisAreasOnMap,infographicOptions:c,attachmentsStore:f,geClient:m.getClient(),templateVariableProvider:h,config:{portalUrl:b.portalUrl,geoenrichmentUrl:b.geoenrichmentUrl,geometryServiceUrl:b.geometryServiceUrl,printMapTaskUrl:b.printMapTaskUrl,countryID:b.countryID,hierarchy:d.hierarchy,reportID:b.reportID,variables:b.variables}}})})})})},_discoverPortal:function(a){var e=
this;return D.getPortalInfo(a.portalUrl).then(function(c){a.geoenrichmentUrl=a.geoenrichmentUrl||c.portal.helperServices.geoenrichment.url;m.setGeoenrichmentUrl(a.geoenrichmentUrl);e._infographicOptionsProvider.setServerUrl(a);a.geometryServiceUrl=a.geometryServiceUrl||c.portal.helperServices.geometry.url;H.setGeometryServiceUrl(a.geometryServiceUrl);a.printMapTaskUrl=a.printMapTaskUrl||c.portal.helperServices.printTask.url;F.setPrintMapTaskUrl(a.printMapTaskUrl)})},reportDataToSingleAreaReportData:function(a,
e){var c=e.currentFeatureIndex||0,b=h.mixin({},a.fieldData);b.areaData=[b.areaData[c]];var f=[a.analysisAreas[c]],g=a.infographicOptions&&this._infographicOptionsProvider.getInfographicOptionsFromJson(a.infographicOptions.toJsonAt(c)),d=a.attachmentsStore;return{isClassic:a.isClassic,isMultiFeature:!1,reportType:a.reportType,reportTitle:e.reportTitle,templateJson:e.templateJson,reportObject:a.reportObject,fieldData:b,analysisAreas:f,combinedAreasInfo:null,reverseAnalysisAreasOnMap:!1,infographicOptions:g,
attachmentsStore:d&&{getAttachments:function(){d.setCurrentAnalysisAreaIndex&&d.setCurrentAnalysisAreaIndex(c);return d.getAttachments()},getAttributes:function(){d.setCurrentAnalysisAreaIndex&&d.setCurrentAnalysisAreaIndex(c);return d.getAttributes()},getNotes:function(){d.setCurrentAnalysisAreaIndex&&d.setCurrentAnalysisAreaIndex(c);return d.getNotes()}},geClient:a.geClient,templateVariableProvider:a.templateVariableProvider,config:a.config}},_getCurrentContext:function(){return this._currentContext},
_onCreateReportStarted:function(){},enrichFieldData:function(a,e){return g.enrichFieldData(a,e)}})});