// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
var __extends=this&&this.__extends||function(){var r=function(h,k){r=Object.setPrototypeOf||{__proto__:[]}instanceof Array&&function(h,k){h.__proto__=k}||function(h,k){for(var l in k)k.hasOwnProperty(l)&&(h[l]=k[l])};return r(h,k)};return function(h,k){function l(){this.constructor=h}r(h,k);h.prototype=null===k?Object.create(k):(l.prototype=k.prototype,new l)}}();
define("esri/arcade/featureSetUtils","require exports ../request ./featureSetCollection ./featureset/sources/FeatureLayerDynamic ./featureset/sources/FeatureLayerDynamicMap ./featureset/sources/FeatureLayerMemoryMap ./featureset/support/cache ./polyfill/promiseUtils ../layers/FeatureLayer".split(" "),function(r,h,k,l,v,w,x,m,n,p){function q(d,c,b,e,a){void 0===b&&(b=null);void 0===e&&(e=!0);void 0===a&&(a=null);null===b&&(b=["*"]);return new v({url:d,outFields:b,spatialReference:c,includeGeometry:e,
lrucache:a})}function t(d,c,b,e,a){void 0===c&&(c=null);void 0===b&&(b=null);void 0===e&&(e=!0);void 0===a&&(a=null);if(!d.getMap())throw Error("FeatureSets can only be used once the layer is added to a Map");if(d.mode===p.MODE_SNAPSHOT&&!d.url)return new x({layer:d,spatialReference:c,outFields:b,includeGeometry:e});if(d.mode===p.MODE_SNAPSHOT||d.mode===p.MODE_ONDEMAND||d.mode===p.MODE_AUTO)return new w({layer:d,spatialReference:c,outFields:b,includeGeometry:e,lrucache:a});throw Error("FeatureSets only support for Snapshot or OnDemand FeatureSet");
}function y(d,c){var b=c.portalUrl+(c.portalUrl.match(/\/$/)?"":"/")+"content/items/"+d;return n.create(function(e,a){return k({url:b,content:{f:"json"},callbackParamName:"callback",load:function(a){e({item:a})},error:function(b){a(b)}})})}Object.defineProperty(h,"__esModule",{value:!0});h.initialiseMetaDataCache=function(){null===m.applicationCache&&(m.applicationCache=new m)};h.constructFeatureSetFromUrl=q;h.constructFeatureSet=t;var z=function(d){function c(b,e,a){void 0===e&&(e=null);void 0===
a&&(a=null);var f=d.call(this)||this;f._map=b;f._overridespref=e;f.lrucache=a;f._instantLayers=[];return f}__extends(c,d);c.prototype.makeAndAddFeatureSet=function(b,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var f=t(b,this._overridespref,null===a?["*"]:a,e,this.lrucache);this._instantLayers.push({featureset:f,opitem:b,includeGeometry:e,outFields:JSON.stringify(a)});return f};c.prototype.makeAndAddFeatureSetTable=function(b,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var f=q(b.url,this._overridespref,
a,e,this.lrucache);this._instantLayers.push({featureset:f,opitem:{name:b.title,id:b.id},includeGeometry:e,outFields:JSON.stringify(a)});return f};c.prototype.featureSetByName=function(b,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var f=JSON.stringify(a),c=0;c<this._instantLayers.length;c++){var d=this._instantLayers[c];if(d.opitem.name===b&&d.includeGeometry===e&&d.outFields===f)return this.resolvePromise(this._instantLayers[c].featureset)}f=null;c=
0;for(d=this._map.graphicsLayerIds;c<d.length;c++){var g=this._map.getLayer(d[c]);if(g instanceof p&&g.name===b){f=g;break}}return f?this.resolvePromise(this.makeAndAddFeatureSet(f,e,a)):this._map.tables&&(f=this._map.tables.find(function(a){return a.title&&a.title===b||a.title&&a.title===b?!0:!1}))?this.resolvePromise(this.makeAndAddFeatureSetTable(f,e,a)):this.resolvePromise(null)};c.prototype.featureSetById=function(b,e,a){void 0===e&&(e=!0);void 0===a&&(a=["*"]);null===a&&(a=["*"]);a=a.slice(0);
a=a.sort();for(var f=JSON.stringify(a),c=0;c<this._instantLayers.length;c++){var d=this._instantLayers[c];if(d.opitem.id===b&&d.includeGeometry===e&&d.outFields===f)return this.resolvePromise(this._instantLayers[c].featureset)}f=null;c=0;for(d=this._map.graphicsLayerIds;c<d.length;c++){var g=this._map.getLayer(d[c]);if(g instanceof p&&g.id===b){f=g;break}}return f?this.resolvePromise(this.makeAndAddFeatureSet(f,e,a)):this._map.tables&&(f=this._map.tables.find(function(a){return a.id&&a.id===b||a.id&&
a.id===b?!0:!1}))?this.resolvePromise(this.makeAndAddFeatureSetTable(f,e,a)):this.resolvePromise(null)};return c}(l);h.createFeatureSetCollectionFromMap=function(d,c,b){void 0===b&&(b=null);return new z(d,c,b)};var A=function(d){function c(b,e,a){void 0===e&&(e=null);void 0===a&&(a=null);var f=d.call(this)||this;f._url=b;f._overridespref=e;f.lrucache=a;f.metadata=null;f._instantLayers=[];return f}__extends(c,d);Object.defineProperty(c.prototype,"url",{get:function(){return this._url},enumerable:!0,
configurable:!0});c.prototype._loadMetaData=function(){var b=this;if(null!==m.applicationCache){var e=m.applicationCache.getLayerInfo(this._url);if(null!==e)return e.then(function(a){b.metadata=a;return n.resolve(b.metadata)})}e=k({url:this._url,content:{f:"json"},callbackParamName:"callback",handleAs:"json"}).then(function(a){if(a)return b.metadata={layers:a.layers?a.layers:[],tables:a.tables?a.tables:[]},n.resolve(b.metadata);b.metadata={layers:[],tables:[]};return n.resolve(b.metadata)},function(a){m.applicationCache&&
m.applicationCache.clearLayerInfo(b._url);return n.reject(a)});null!==m.applicationCache&&m.applicationCache.setLayerInfo(this._url,e);return e};c.prototype.makeAndAddFeatureSet=function(b,e,a){void 0===e&&(e=!0);void 0===a&&(a=null);var f=t(b,this._overridespref,null===a?["*"]:a,e,this.lrucache);this._instantLayers.push({featureset:f,opitem:b,includeGeometry:e,outFields:JSON.stringify(a)});return f};c.prototype.load=function(){return this._loadMetaData()};c.prototype.clone=function(){return new c(this._url,
this._overridespref,this.lrucache)};c.prototype.featureSetByName=function(b,e,a){var f=this;void 0===e&&(e=!0);void 0===a&&(a=null);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();for(var c=JSON.stringify(a),d=0;d<this._instantLayers.length;d++){var g=this._instantLayers[d];if(g.opitem.name===b&&g.includeGeometry===e&&g.outFields===c)return this.resolvePromise(this._instantLayers[d].featureset)}return this._loadMetaData().then(function(c){for(var d=null,g=0,h=c.layers?c.layers:[];g<h.length;g++){var k=
h[g];k.name===b&&(d=k)}if(!d)for(g=0,c=c.tables?c.tables:[];g<c.length;g++)k=c[g],k.name===b&&(d=k);return d?f.resolvePromise(q(f._url+"/"+d.id,f._overridespref,a,e,f.lrucache)):f.resolvePromise(null)})};c.prototype.featureSetById=function(b,e,a){var c=this;void 0===e&&(e=!0);void 0===a&&(a=["*"]);null===a&&(a=["*"]);a=a.slice(0);a=a.sort();var d=JSON.stringify(a);b=null!==b&&void 0!==b?b.toString():"";for(var k=0;k<this._instantLayers.length;k++){var g=this._instantLayers[k];if(g.opitem.id===b&&
g.includeGeometry===e&&g.outFields===d)return this.resolvePromise(this._instantLayers[k].featureset)}return this._loadMetaData().then(function(d){for(var f=null,g=0,k=d.layers?d.layers:[];g<k.length;g++){var h=k[g];null!==h.id&&void 0!==h.id&&h.id.toString()===b&&(f=h)}if(!f)for(g=0,d=d.tables?d.tables:[];g<d.length;g++)h=d[g],null!==h.id&&void 0!==h.id&&h.id.toString()===b&&(f=h);return f?c.resolvePromise(q(c._url+"/"+f.id,c._overridespref,a,e,c.lrucache)):c.resolvePromise(null)})};return c}(l);
h.createFeatureSetCollectionFromService=function(d,c,b){void 0===b&&(b=null);return new A(d,c,b)};h.constructFeatureSetFromPortalItem=function(d,c,b,e,a,f,h){return n.create(function(k,g){if(m.applicationCache){var l=m.applicationCache.getLayerInfo(d+":"+f.url);if(l){l.then(function(d){try{var f=q(d.item.url+"/"+c,b,e,a,h);k(f)}catch(u){g(u)}},function(a){g(a)});return}}l=y(d,f);m.applicationCache&&m.applicationCache.setLayerInfo(d+":"+f.url,l);l.then(function(d){try{var f=q(d.item.url+"/"+c,b,e,
a,h);k(f)}catch(u){g(u)}},function(a){m.applicationCache&&m.applicationCache.clearLayerInfo(d+":"+f.url);g(a)})})}});