// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/grid/valueField/_ResizableField","dojo/_base/declare dojo/aspect dojo/on dojo/string dojo/dom-class dojo/dom-construct dojo/dom-style ./supportClasses/ResizeColumnRowTooltipVisualizer ./supportClasses/ResizeEngine esri/dijit/geoenrichment/utils/PageUnitsConverter esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/MouseUtil esri/dijit/geoenrichment/utils/TooltipUtil dojo/i18n!esri/nls/jsapi".split(" "),function(q,r,k,l,d,m,t,g,h,
n,e,u,p,f){f=f.geoenrichment.dijit.ReportPlayer.ValueField;return q(null,{resizable:!0,hasAllSidesSizers:!1,showSizeLabel:!1,showSizeLabelsInAllRelatedCells:!1,showColumnRowSizeTooltip:!1,showSizersOnFocus:!1,createSizersOnDemand:!0,resizeSnapNode:null,resizeRestrictNode:null,allowHorizontalResizing:!0,allowVerticalResizing:!0,sizeLabel:null,_tooltipHandles:null,postCreate:function(){this._tooltipHandles=[];this.inherited(arguments);this.resizable&&this._addCreateSizersTrigger()},_isBeingResized:!1,
_isBeingResizedDelayed:!1,_sizers:null,isBeingResized:function(){return this.resizable&&this._sizers?this._isBeingResized||this._sizers.some(function(a){return u.isMouseOver(a)})||!this.hasAllSidesSizers&&this._sizers.some(function(a){return 0<t.get(a,"opacity")}):!1},wasResizedRecently:function(){return this.isBeingResized()||this._isBeingResizedDelayed},_addCreateSizersTrigger:function(){var a=this;this.createSizersOnDemand||this._updateSizers();k(this.domNode,"mouseover",function(){a._updateSizers()})},
_createSizers:function(){var a=this;this.resizable&&!this._sizers&&(this._sizers=(this.hasAllSidesSizers?h.ALL_DIRECTIONS:[this.allowHorizontalResizing?"e":null,this.allowVerticalResizing?"s":null].filter(function(a){return!!a})).map(function(b){var c=m.create("div",null,a.domNode);a.hasAllSidesSizers?(d.add(c,(a.showSizersOnFocus?"valueField_allSidesSizer_showOnFocus":"valueField_allSidesSizer")+" "+b+"_fieldSizer"),a.fieldCellClass&&d.add(c,"fieldSizer_"+a.fieldCellClass)):"e"===b?(d.add(c,"valueField_widthSizer"),
a._tooltipHandles.push(p.setTooltipToNode(c,f.dragToChangeWidth)),a.fieldCellClass&&d.add(c,"widthSizer_"+a.fieldCellClass)):(d.add(c,"valueField_heightSizer"),a._tooltipHandles.push(p.setTooltipToNode(c,f.dragToChangeHeight)),a.fieldCellClass&&d.add(c,"heightSizer_"+a.fieldCellClass));c._dir=b;return c}),this._addResizeHandlers())},unitTesting_getSizerByDirection:function(a){this._updateSizers();return this._sizers.filter(function(b){return b._dir===a})[0]},_addResizeHandlers:function(){var a=this;
this._sizers.forEach(function(b){k(b,"mousedown",function(c){c.preventDefault();c.stopPropagation();a._setIsBeingResized(!0);a.stopEdit&&a.stopEdit();h.trackSizer({dir:b._dir,w:a.getWidth(),h:a.getHeight(),angle:a.getAngle(),supportsCtrlShift:a.hasAllSidesSizers,getThisBox:function(){return e.noTransformPosition(a.domNode)},getThisFullBox:function(){return a.getBBox({noTransformation:!0})},getSnapNodeBoxes:function(){if(!a.hasAllSidesSizers)return null;var b=a._getResizeSnapElements()||[],b=b.map(function(a){return{box:a.getBBox({noTransformation:!0}),
tolerance:3}});a.resizeSnapNode&&b.push({box:e.noTransformPosition(a.resizeSnapNode),tolerance:7});return b.length?b:null},getRestrictNodeBox:function(){return a.hasAllSidesSizers?a.resizeRestrictNode&&e.noTransformPosition(a.resizeRestrictNode):null},onPreChange:function(){a._onManualSizePreChange()},onSizeChanged:function(){a._onManualSizeChange(b._dir);a.onManualSizeChange();a._updateSizers()},onWidthChanged:function(b){a.onManualWidthChange(b)},onHeightChanged:function(b){a.onManualHeightChange(b)},
setWidth:function(b){a.setWidth(b)},setHeight:function(b){a.setHeight(b)},applyShift:function(b,c){a.onNeedShiftPositionFromResizing(b,c)},onEnd:function(){a._setIsBeingResized(!1)},onSnapped:function(b){a.onResizeSnapped(b)}})})});this.hasAllSidesSizers&&this.own(r.after(this,"onSizeChanged",function(){e.isNodeInLayout(a._sizers[0])&&a._updateSizers()}))},_getResizeSnapElements:function(){},_setIsBeingResized:function(a){a?(this._isBeingResizedDelayed=this._isBeingResized=!0,d.add(this.domNode,"isBeingResized"),
this.parentGrid&&d.add(this.parentGrid.domNode,"isBeingResized")):(this._isBeingResized&&this._onManualSizeChangeEnd(),this._isBeingResized=!1,d.remove(this.domNode,"isBeingResized"),this.parentGrid&&d.remove(this.parentGrid.domNode,"isBeingResized"),e.stealFocus(),setTimeout(function(){this._isBeingResizedDelayed=!1}.bind(this),100));this._tooltipHandles.forEach(function(b){a?b.suspend():b.resume()})},updateSizers:function(){this._updateSizers()},_updateSizers:function(){function a(){var a=b.getAngle();
b._sizers.forEach(function(c){h.positionSizer({sizer:c,dir:c._dir,w:b.getWidth(),h:b.getHeight(),angle:a})})}this._createSizers();if(this._sizers&&this.hasAllSidesSizers){var b=this;5<this.domNode.clientHeight?a():setTimeout(a,100)}},_onManualSizePreChange:function(){this.onManualSizePreChange()},_onManualSizeChange:function(a){this.inherited(arguments);this.showSizeLabel&&this._showAndUpdateSizeLabel();this.showSizeLabelsInAllRelatedCells&&this._showAndUpdateRelatedCellsSizeLabels();this.showColumnRowSizeTooltip&&
("e"===a?g.showColumnTooltip(this):"s"===a&&g.showRowTooltip(this))},_onManualSizeChangeEnd:function(){e.hide(this.sizeLabel);this.showSizeLabelsInAllRelatedCells&&this._hideRelatedCellsSizeLabels();this.showColumnRowSizeTooltip&&g.removeTooltip();this.onManualSizeChangeEnd()},tryUpdateSizeLabel:function(){e.isNodeInLayout(this.sizeLabel)&&(this.showSizeLabel&&this._showAndUpdateSizeLabel(),this.showSizeLabelsInAllRelatedCells&&this._showAndUpdateRelatedCellsSizeLabels())},_showAndUpdateSizeLabel:function(){if(this.domNode){this.sizeLabel=
this.sizeLabel||m.create("div",{"class":"elementSizeLabel"},this.domNode);e.show(this.sizeLabel);var a=this.domNode.clientWidth,b=this.domNode.clientHeight;if(this.viewModel&&this.viewModel.showUnitsInPt){var c=n.pxToPt(a),d=n.pxToPt(b);this.sizeLabel.innerHTML=l.substitute(f.elementSizeFormatPt,{width:Math.round(c),height:Math.round(d)})}else this.sizeLabel.innerHTML=l.substitute(f.elementSizeFormat+" px",{width:Math.round(a),height:Math.round(b)});c=this.sizeLabel.clientHeight;this.sizeLabel.style.left=
Math.round((a-this.sizeLabel.clientWidth)/2)+"px";this.sizeLabel.style.top=Math.round(20<b?(b-c)/2:-c-5)+"px"}},_showAndUpdateRelatedCellsSizeLabels:function(){this._getRelatedCells().forEach(function(a){a._showAndUpdateSizeLabel()})},_hideRelatedCellsSizeLabels:function(){this._getRelatedCells().forEach(function(a){e.hide(a.sizeLabel)})},_getRelatedCells:function(){return this.parentGrid?this.parentGrid.getFieldCells().filter(function(a){return a!==this},this):[]},onManualSizePreChange:function(){},
onManualSizeChangeEnd:function(){},onManualSizeChange:function(){},onManualWidthChange:function(a){},onManualHeightChange:function(a){},onNeedShiftPositionFromResizing:function(a,b){},onResizeSnapped:function(a){}})});