// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/iconRendering/IconRenderer","dojo/_base/declare dojo/dom-construct dojo/dom-style dijit/Destroyable ../utils/ChartTypes ../utils/builder/ChartPlots ../utils/plots/supportClasses/GaugeLabelPlacement ../../supportClasses/templateJsonUtils/fieldInfo/FieldInfoBuilder ../../supportClasses/tableJson/TableJsonUtil ../../infographics/utils/InfographicThemeUtil esri/dijit/geoenrichment/ReportPlayer/core/sections/SectionTypes esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/ReportPlayer/core/supportClasses/ViewModes".split(" "),
function(h,t,l,B,g,m,C,p,D,x,y,z,A){h=h(B,{renderIcons:function(a){this._destroyIcons();var b=this._getRenderFunction(a.chartType);b&&this[b](a);this._renderFloatingIcons(a)},_getRenderFunction:function(a){switch(a){case g.GAUGE:return"_renderDonutIcons";case g.DONUT:return"_renderDonutIcons";case g.RING:return"_renderRingIcons";case g.COLUMN:return"_renderColumnIcons";case g.BAR:return"_renderBarIcons"}return null},_renderDonutIcons:function(a){if(a.visualProperties.showChartIcons){var b=a.chart.getPlot(m.PRIMARY).getRenderResults();
if(b){var d=t.create("div",{"class":"chartContainer_chartIcon"},a.iconNode),e=b.radiusInner,f=0,c=1;a.chartType===g.GAUGE&&(c=Math.max(.6,b.ryMultiplier),a.visualProperties.gaugeLabelPlacement===C.INSIDE&&(f=b.chartIconOffset,e=Math.min(e,b.maxIconSize)));f=(a.chartH/c-e+f)/2+(b.chartShiftY||0);f=Math.min(f,a.chartH-e-10);l.set(d,{width:e+"px",height:e+"px",left:(a.chartW-e)/2+(b.chartShiftX||0)+"px",top:f+"px"});this._createIconSection(a,a.visualProperties.chartIcons&&a.visualProperties.chartIcons[0]||
this._getDefaultIcon(),e,d)}}},_renderRingIcons:function(a){if(a.visualProperties.showChartIcons){var b=a.chart.getPlot(m.PRIMARY).getRenderResults();if(b){b.slicePies.sort(function(a,b){return a.r-b.r});var d=b.slicePies[0],e=b.slicePies[b.slicePies.length-1],f=t.create("div",{"class":"chartContainer_chartIcon"},a.iconNode),c=0;b.labels?(c=Math.max(50,.8*Math.min(2*d.r,Math.min(b.maxLabelWidth,a.chartW-(e.cx+e.r)))),l.set(f,{width:c+"px",height:c+"px",left:Math.max(e.cx+e.r+15,e.cx+e.r+b.maxLabelWidth/
2-c/2)+"px",top:e.cy-c/2+"px"})):(c=1.4*d.r,l.set(f,{width:c+"px",height:c+"px",left:d.cx-c/2+"px",top:d.cy-c/2+"px"}));this._createIconSection(a,a.visualProperties.chartIcons&&a.visualProperties.chartIcons[0]||this._getDefaultIcon(),c,f)}}},_renderColumnIcons:function(a){this._renderAxisIcons(a,!0)},_renderBarIcons:function(a){this._renderAxisIcons(a,!1)},_renderAxisIcons:function(a,b){if(a.visualProperties.showAxisIcons){var d=this,e=a.chart.calculateGeometry(),f=a.chart.getPlot(m.PRIMARY).getMainShapes();
if(f&&f.length){var c={};f.forEach(function(a){(c[a.value.x]=c[a.value.x]||[]).push(a.rawNode)});f=Object.keys(c).map(function(a){return Number(a)});f.sort();var g=f.map(function(a){return z.uniteNodeBoxes(c[a])}),q,r;e.series[0].data.forEach(function(a,b){void 0!==a.unsortedIndex&&(q=q||{},q[b]=a.unsortedIndex);r=r||{};r[b]=a.fill});var h=z.noTransformPosition(a.iconNode);g.forEach(function(c,f){var m=q?q[f]:f,w=a.visualProperties.chartIcons&&a.visualProperties.chartIcons[m]||d._getDefaultIcon(),
n=(w.imageJson||w.shapeJson).style.zoom||1,u=t.create("div",{"class":"chartContainer_chartIcon"},a.iconNode),k=Math.min(50,.7*(b?e.plotArea.width:e.plotArea.height)/g.length),n=k*n;l.set(u,{width:n+"px",height:n+"px"});var p=a.visualProperties.xAxis.show?0:k/(b?2:3.5),v=-(n-k)/2;b?l.set(u,{left:c.x-h.x+(1*c.w-k)/2+v+"px",bottom:-k+p+v+"px"}):l.set(u,{top:c.y-h.y+(1*c.h-k)/2+v+"px",left:-k+p+v+"px"});d._createIconSection(a,w,n,u,m,r&&r[f],k)})}}},_floatingIconsSection:null,_renderFloatingIcons:function(a){var b=
a.visualProperties.floatingIcons;if(b&&b.length){b.forEach(function(b){b=b.data.data[0].fieldInfos[b.data.columns[0].field].shapeJson;var d=a.viewModel.getChartDefaultStyles(a.theme);x.applyThemeSettingsToShapeJson(b,d)});var d={"class":"chartContainer_floatingIconSection"};d.initialWidth=a.chartW;d.json={type:y.DETAILS,stack:b};d.viewModel=a.viewModel;d.theme=a.theme;d.tableClass="chartContainerFloatingIconTable";d.parentWidget=a.parentWidget;d.initialViewMode=this._viewMode||A.EDIT;this._provideParamsForFloatingIconSection(d,
a);this._floatingIconsSection=a.viewModel.layoutBuilder.createElement("section",d,a.iconNode);this._floatingIconsSection.setHeight(a.chartH)}},_provideParamsForFloatingIconSection:function(a,b){},_getDefaultIcon:function(){},_iconSections:null,_createIconSection:function(a,b,d,e,f,c,g){if(b&&(b.imageJson||b.shapeJson)){if(b.shapeJson){var h=a.viewModel.getChartDefaultStyles(a.theme);x.applyThemeSettingsToShapeJson(b.shapeJson,h);b.shapeJson.themeStyle&&c&&(b.shapeJson.themeStyle.borderColor=c,b.shapeJson.themeStyle.fillColor=
c)}b=D.createSingleCellTable({width:d,height:d,fieldInfo:b.imageJson?p.createFieldInfoFromImage(b.imageJson):p.createFieldInfoFromShape(b.shapeJson),cellStyle:{backgroundColor:"transparent"}});c={};c.initialWidth=d;c.json={type:y.DETAILS,stack:[b]};c.viewModel=a.viewModel;c.theme=a.theme;c.tableClass="chartContainerIconTable";c.parentWidget=a.parentWidget;c.initialViewMode=this._viewMode||A.EDIT;this._provideParamsForIconSection(c,a);a=a.viewModel.layoutBuilder.createElement("section",c,e);a.setWidth(d);
a.setHeight(d);a.__unsortedIndex=f;a.__noZoomIconSize=g;this._iconSections.push(a)}},_getSectionInitialSettings:function(a){return{unsortedIndex:a&&void 0!==a.__unsortedIndex?a.__unsortedIndex:-1,noZoomIconSize:a&&a.__noZoomIconSize}},_provideParamsForIconSection:function(a,b,d,e){},_viewMode:null,setViewMode:function(a){this._viewMode!==a&&(this._viewMode=a,this._iconSections&&this._iconSections.forEach(function(b){b.setViewMode(a)}),this._floatingIconsSection&&this._floatingIconsSection.setViewMode(a))},
_destroyIcons:function(){this._iconSections=this._iconSections||[];this._iconSections.forEach(function(a){var b=a.domNode&&a.domNode.parentNode;a.destroy();b&&t.destroy(b)});this._iconSections.length=0;this._floatingIconsSection&&this._floatingIconsSection.destroy();this._floatingIconsSection=null},destroy:function(){this._destroyIcons();this.inherited(arguments)}});h.AXIS_ICON_MAX_SIZE=50;return h});