// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_ColumnBarChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartSorting ../../ChartLineStyles ../../../../supportClasses/conditionalStyling/ConditionalStyleUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ./_ComparisonUtil ./_AxisBuilder ./_PointLabelUtil esri/dijit/geoenrichment/utils/ColorUtil".split(" "),function(J,v,C,D,E,x,K,L,F,A,G){var M={calcLineStyle:function(a,e){return{color:G.getColorWithAlpha(e.columnBarLineColor||
a,e.columnBarLineOpacity),width:e.columnBarLineThickness,style:D.toGFXValue(e.columnBarLineStyle||D.SOLID)}}};return{calcSeriesColumnBar:function(a){var e=a.chart,h=a.visualProperties,c=a.seriesItems,q=1===c.length,r=a.seriesItemsWithComparison||c,k=a.chartType,y=a.comparisonInfo,z=a.themeSettings,t=a.viewModel,l=1===r.length&&a.sorting,x=1<r.length&&h.renderColumnBarsInOppositeDirections,m=[],b={minYValue:Infinity,maxYValue:-Infinity,stackedValues:h.isStacked?[]:null};A.createPointToLabelMap(e);
var u={};r.forEach(function(g,c){if(g.points.length){var p={name:g.label,data:[],isComparisonSeries:g.isComparisonSeries,params:{plot:g.isComparisonSeries&&L.getComparisonPlotName(k,y)||void 0}},f=this._collectStatisticsForSeries(a,g,c,b);v.provideMissingIconsForPoints(g.points,k);var H=[];g.points.forEach(function(d,b){var e=f.values[b],I=e||0,m=b+1,n;h.conditionalStyling&&(n=(n=E.getConditionalStyle(I,h.conditionalStyling))&&n.backgroundColor);d.hidden&&(n="transparent");n=n||v.calcColorForPoint({point:d,
seriesItem:g,pointIndex:b,seriesIndex:c,numSeries:q?1:r.length,chartType:k,themeSettings:z,isComparisonSeries:g.isComparisonSeries,comparisonInfo:y,isMultiFeature:a.isMultiFeatureChart});var l=K.getTooltipInfo({yValue:e,pointLabel:A.getPointLabel(d,t),seriesLabel:g.label,minInSeriesValue:f.minInSeries,maxInSeriesValue:f.maxInSeries,sumInSeriesValue:f.valuesSum,absSumInSeriesValue:f.absValuesSum,avgInSeriesValue:f.avgInSeries,minInAreasValue:f.minInSeries,maxInAreasValue:f.maxInSeries,sumInAreasValue:f.valuesSum,
absSumInAreasValue:f.absValuesSum,avgInAreasValue:f.avgInSeries,visualProperties:h,chartType:k,isMultiFeature:a.isMultiFeatureChart,color:n,conditionalStyling:h.conditionalStyling,fieldInfo:d.fieldInfo,isThisAreaSpecific:y&&!a.isMultiFeatureChart?!g.isComparisonSeries:void 0,isThisAreaSingleSeries:q,decimals:d.value&&d.value.decimals}),w=u[m]=u[m]||[];w.push(l);H.push(l);l.getGroup=function(){return a.isMultiFeatureChart?H:w};var B=M.calcLineStyle(n,h);d.hidden&&(B.color="transparent");d={x:m,y:I*
(x&&c>=r.length/2?-1:1),originalValue:e,isUnavailableData:isNaN(e),valueProp:"y",unsortedIndex:b,seriesIndex:c,name:A.getPointLabel(d,t),valuesSumsInSeries:f.absValuesSum,point:d,fill:1>h.columnBarOpacity?G.getColorWithAlpha(n,h.columnBarOpacity):n,tooltip:l,icon:v.calcIconForPoint(d,n,k),bgIcon:v.calcBackgroundIconForPoint(d,k,z,h),stroke:{color:B.color,width:B.width,style:B.style}};h.yAxis.showValuesAsWeightsInSeries&&(d.y/=f.absValuesSum/100);p.data.push(d)});l&&l!==C.NONE&&(p.data.sort(function(a,
b){return(a.y-b.y)*(l===C.DESC?-1:1)}),p.data.forEach(function(a,b){a.x=b+1}));p.data.forEach(function(a){A.updatePointIndexToLabelMap(e,a.x,c,a.point,t)});m.push(p)}},this);b.stackedValues&&(b.stackedValues.sort(function(a,b){return b-a}),b.minYValue=b.stackedValues[b.stackedValues.length-1],b.maxYValue=b.stackedValues[0]);F.prettifyYAxis(b.minYValue,b.maxYValue,e,h,k,z,t,m);a.plotStats&&(J.mixin(a.plotStats,b),a.plotStats.pointIndexToTooltipsHash=u);return m},_collectStatisticsForSeries:function(a,
e,h,c){var q=a.visualProperties,r=a.viewModel,k=a.seriesItems,y=a.currentFeatureIndex,z=a.isMultiFeatureChart,t=a.excludedSeriesHash&&a.excludedSeriesHash[e.label],l=a.comparisonFeatureAttributes,v=a.chartType;a=1<k.length&&q.renderColumnBarsInOppositeDirections;var m=2===k.length&&a?x.CHART_DATA_SMOOTH:null;q.conditionalStyling&&(a=E.getStatistics(q.conditionalStyling))&&k.length&&(m=x.getChartData(a,k[0].points.length,m,!1));var b=[],u=0,g=0,w=1E6,p=-1E6;e.points.forEach(function(a,d){var c=a.hidden?
void 0:x.getPointValue({point:a,index:d,seriesIndex:h,maxValue:!1,chartType:v,visualProperties:q,viewModel:r,currentFeatureIndex:z?d:y,chartData:m,isComparisonSeries:e.isComparisonSeries,comparisonFeatureAttribute:l&&l[0],allowNegativeValuesInPreview:!1}),c=(b[d]=c)||0;t||a.hidden||(u+=c,g+=Math.abs(c),w=Math.min(w,c),p=Math.max(p,c))});var f=0;t||e.points.forEach(function(a,d){a.hidden||(f++,a=b[d],a=q.yAxis.showValuesAsWeightsInSeries?a/g*100:a,c.stackedValues?(c.stackedValues[d]=c.stackedValues[d]||
0,c.stackedValues[d]+=a):(c.minYValue=Math.min(a,c.minYValue),c.maxYValue=Math.max(a,c.maxYValue)))});return{values:b,valuesSum:u,absValuesSum:g,minInSeries:w,maxInSeries:p,avgInSeries:u/f}},prettifyColumnBarYAxis:function(a){F.prettifyYAxis(a.totalStat.minYValue,a.totalStat.maxYValue,a.chart,a.visualProperties,a.chartType,a.themeSettings,a.viewModel,a.chartSeries,!0,a.chartSize);a.chart.dirty=!0}}});