// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/infographics/simpleInfographic/_DataDrillingSupport","dojo/_base/declare dojo/aspect dojo/on esri/dijit/geoenrichment/when dojo/dom-class dojo/dom-construct dojo/dom-style dojo/query ./SimpleInfographicViewModes ../../grid/coreUtils/GridDataUtil ./dataDrilling/DataDrillingLibrary ../utils/InfographicJsonUtil esri/dijit/geoenrichment/utils/DelayUtil esri/dijit/geoenrichment/utils/DeviceUtil esri/dijit/geoenrichment/utils/DnDUtil esri/dijit/geoenrichment/utils/DomUtil esri/dijit/geoenrichment/utils/TooltipUtil esri/dijit/geoenrichment/utils/WaitingUtil ../../sections/SectionTypes ../../supportClasses/ViewModes ./DataDrillingBackgroundUtil ./DataDrillingExportUtil dojo/i18n!esri/nls/jsapi".split(" "),
function(C,D,k,l,E,m,x,y,u,F,v,z,q,r,A,n,w,B,G,H,I,t,p){p=p.geoenrichment.dijit.ReportPlayer.Infographics;return C(null,{_drillingSections:null,_drillingSectionsButtons:null,postCreate:function(){var a=this;this.inherited(arguments);k(this.backToMainViewButton,"click",function(){a._setViewMode(u.VIEW_MAIN,!0)});r.isMobileDevice()&&this.own(k(window,"resize, orientationchange",function(){a._setViewMode(u.VIEW_MAIN,!1)}));n.hide([this.exportButton,this.printButton]);this.viewModel.dynamicReportInfo&&
(t.canExportDataDrilling(this)&&(w.setTooltipToNode(this.exportButton,p.exportInfographic),n.show(this.exportButton),k(this.exportButton,"click",function(){t.exportDataDrilling(a)})),t.canPrintDataDrilling(this)&&(w.setTooltipToNode(this.printButton,p.printInfographic),n.show(this.printButton),k(this.printButton,"click",function(){t.printDataDrilling(a)})))},_getCountryID:function(){return this.viewModel.dynamicReportInfo.infographicOptions.countryID},_addDataDrillingHandlers:function(a,c){var e=
this;return B.showProgressPromise(this.domNode,l(v.init({variableProvider:this.viewModel.dynamicReportInfo.templateVariableProvider,countryID:this.viewModel.dynamicReportInfo.countryID,hierarchy:this.viewModel.dynamicReportInfo.hierarchy}),function(){var f=F.getFieldInfo(c.getFirstCell()),b=z.getDataDrilling(e._currentInfographicJson,f.templateName),d=b&&b.sectionJson?b:null,g=(b=b&&b.isStandard&&v.getDrillingOptions(e._getCountryID(),b.standardId||f))&&b[0];if(d||g)a.getTables().forEach(function(a){a.getFieldCells().forEach(function(a){w.setTooltipToNode(a.domNode,
null)})}),e._setUpDataDrillingButton(a,function(a){a=e._setViewMode(u.VIEW_DATA_DRILLING,!0,a);d?e._renderCustomSectionJson({customDDPanelInfo:d,fieldInfo:f,animationPromise:a}):e._loadStandardDataDrillingView({fieldInfo:f,optionName:g.name,calcState:null,sectionVisualState:null,animationPromise:a})})}))},_setUpDataDrillingButton:function(a,c){function e(){var b=m.create("div",{"class":"simpleInfographic_drillDataButton"},a.domNode);m.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonIcon esriGESpaceAfterBig"},
b);var c=m.create("div",{"class":"dijitInline simpleInfographic_drillDataButtonLabel",innerHTML:p.drillForMoreData},b),e=[];a.getTables().forEach(function(a){e.push(a.domNode)});var d=n.uniteNodeBoxes(e,a.domNode);x.set(b,{left:d.x+"px",top:d.y+"px",width:d.w+"px",height:d.h+"px",lineHeight:d.h+"px"});var h=b.clientWidth;h>d.w&&x.set(b,"left",d.x-(h-d.w)/2+"px");c.style.maxWidth=h-50+"px";c.style.whiteSpace="normal";c.style.lineHeight="20px";f._drillingSectionsButtons.push({destroy:function(){m.destroy(b)}});
return b}var f=this,b;if(r.isMobileDevice()){var d=function(a){b.style.opacity=a?1:0;g=a;h&&h.remove()},g=!1,h;A.addNoDragClickHandler(a.domNode,function(){g||(b=b||e(),d(!0),setTimeout(function(){h=A.addNoDragClickHandler(b,function(){d(!1);c(b)});k.once(document.body,"touchend",function(){d(!1)})}))},{detectLongPress:!0,longPressTimeout:750,ignoreReleaseIfLongPressHappened:!0,longPressCallback:function(){b=b||e();d(!0);c(b);setTimeout(function(){d(!1)})}})}else a.own(k.once(this.domNode,"mouseover",
function(){b=b||e();k(b,"click",function(){c(b)})}))},_dataDrillingState:null,_loadStandardDataDrillingView:function(a){var c=a.fieldInfo,e=a.optionName,f=a.calcState,b=a.sectionVisualState,d=a.animationPromise,g=this;this._dataDrillingState={fieldInfo:c,optionName:e,calcState:f,sectionVisualState:b};this._destroyDrillingSections();this._showDDProgress(!0);return l(function(){var a=g._getDataDrillingPanelDimensions(),b=z.getDataDrilling(g._currentInfographicJson,c.templateName),d=v.getDrillingOptionInfo(g._getCountryID(),
b.standardId||c,e,a.w,a.h,f),a=d.enrichInfos;return l(a&&a.length&&g.viewModel.enrichFieldData(a),function(){return d})}(),function(a){return l(g._renderStandardOptionInfo({drillingDataOptionInfo:a,fieldInfo:c,animationPromise:d,optionName:e,calcState:f,sectionVisualState:b}),function(){g._showDDProgress(!1)})})},_renderStandardOptionInfo:function(a){var c=a.drillingDataOptionInfo,e=a.fieldInfo,f=a.animationPromise,b=a.optionName,d=a.sectionVisualState,g=this,h;this._destroyDrillingSections();var k=
this._getDataDrillingPanelSectionParams();k.json={type:G.DETAILS,stack:[c.tableJson]};k.calculationStatesGroup=c.calculationStatesGroup;k.onCalculationStateChanged=function(a){g._loadStandardDataDrillingView({fieldInfo:e,optionName:b,calcState:a,sectionVisualState:h.getVisualState(),animationPromise:null})};return l(f,function(){return q.delay(function(){h=g._createDataDrillingSection(k);h.fitContentNicely();h.domNode.style.opacity="0.01";return q.delay(function(){h.setVisualState(d);h.domNode.style.opacity=
"";h.notifyShown()},100)})})},_renderCustomSectionJson:function(a){var c=a.customDDPanelInfo,e=a.animationPromise,f=a.sectionVisualState,b=this;this._destroyDrillingSections();this._dataDrillingState=null;var d,g=this._getDataDrillingPanelSectionParams();g.json=c.sectionJson;this._showDDProgress(!0);return l(e,function(){return q.delay(function(){d=b._createDataDrillingSection(g);d.fitContentNicely();d.domNode.style.opacity="0.01";return q.delay(function(){d.setVisualState(f);d.domNode.style.opacity=
"";d.notifyShown();b._showDDProgress(!1)})})})},_getDataDrillingPanelSectionParams:function(){var a={"class":"infographicContainer_dataDrillingSection"};a.initialWidth=this._getDataDrillingPanelDimensions().w;a.viewModel=this.viewModel;a.theme=this.theme;a.parentWidget=this;a.isDataDrillingView=!0;a.currentFeatureIndex=this.currentFeatureIndex||0;a.initialViewMode=H.PREVIEW_VALUES;m.empty(this.dynamicSettingsToolbarRoot);a.dynamicSettingsToolbarRoot=this.dynamicSettingsToolbarRoot;return a},_createDataDrillingSection:function(a){var c=
this._getDataDrillingPanelDimensions();a=this.viewModel.layoutBuilder.createElement("section",a,this.drilledDataViewDivScaler);this._drillingSections.push(a);a.setHeight(c.h);E[y(".sectionDynamicSettings_settingsButton",this.dataDrillingViewDiv)[0]?"add":"remove"](this.dataDrillingViewDiv,"hasChartSettingsButton");this._setUpDDPanelBackgroundColor();c.scale&&(a.notifyPanelScaleChanged(c.scale),this._applyScaleToDataDrillingToolbarButtons(c.buttonScale||c.scale),D.after(a,"onDynamicSettingsButtonsCreated",
function(){this._applyScaleToDataDrillingToolbarButtons(c.buttonScale||c.scale)}.bind(this)));return a},_applyScaleToDataDrillingToolbarButtons:function(a){var c=1/a;a=[];var e=y(".sectionDynamicSettings_buttonBar",this.dynamicSettingsToolbarRoot)[0];if(e)for(var f=0;f<e.children.length;f++)a.push(e.children[f]);a.push(this.exportButton);a.push(this.printButton);a.push(this.backToMainViewButton);a.forEach(function(a,d){a.style.transformOrigin=this.viewModel.showDataDrillingInsidePanel?"100% 0":"100% 100%";
a.style.transform="scale("+c+")";a.style["webkit-transform"]="scale("+c+")";0<d&&(d=(this.viewModel.showDataDrillingInsidePanel?5:26)*c,d+=32*(c-1),a.style.marginLeft=d+"px")},this)},_setUpDDPanelBackgroundColor:function(){var a=this.viewModel.getDocumentDefaultStyles(this.theme),a=a.backgroundImage&&a.backgroundImage.data;this.viewModel.showDataDrillingInsidePanel&&!a||I.setUpDDPanelBackgroundColor({viewModel:this.viewModel,theme:this.theme,infographicJson:this._currentInfographicJson,node:this.dataDrillingViewDiv})},
_getDataDrillingPanelDimensions:function(){if(this.viewModel.showDataDrillingInsidePanel){var a=1/this.parentWidget.parentWidget.parentWidget.parentWidget.getPanelScale(),c=this.width/a,e=this.height/a,f=400>c,b=500>e;this.dataDrillingViewDiv.style.overflowX=f?"auto":"hidden";this.dataDrillingViewDiv.style.overflowY=b?"auto":"hidden";return{scale:a,buttonScale:1/a,w:Math.max(c,400)-(b?n.getScrollbarSize().w/a:0),h:Math.max(e,500)-(f?n.getScrollbarSize().h/a:0)}}c=document.body.clientWidth-(r.isLandscape()?
80:40);e=document.body.clientHeight-80;a=Math.max(.7,Math.min(1,c/400,e/500));return r.isMobileDevice()?{w:c/a,h:e/a,scale:a,yOffset:10,animateFromCenter:!0}:{w:Math.min(c/a,700),h:Math.min(e/a,600),scale:a,yOffset:600<e-30?0:15}},_showDDProgress:function(a){B[a?"showProgress":"removeProgress"](this.viewModel.showDataDrillingInsidePanel?this.domNode:this.dataDrillingViewDiv)},_getDataDrillingState:function(){return this._dataDrillingState},_setDataDrillingState:function(a){a&&this._loadStandardDataDrillingView({fieldInfo:a.fieldInfo,
optionName:a.optionName,calcState:a.calcState,sectionVisualState:a.sectionVisualState,animationPromise:null})},_destroyDrillingSections:function(){this._drillingSections=this._drillingSections||[];this._drillingSections.forEach(function(a){a.destroy()});this._drillingSections.length=0;this.domNode&&m.empty(this.drilledDataViewDivScaler)},_destroyDrillingSectionsButtons:function(){this._drillingSectionsButtons=this._drillingSectionsButtons||[];this._drillingSectionsButtons.forEach(function(a){a.destroy()});
this._drillingSectionsButtons.length=0}})});