// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.28/esri/copyright.txt for details.
//>>built
define("esri/dijit/geoenrichment/ReportPlayer/core/charts/utils/builder/columnBarLine/_LineChartSeriesCalculator","dojo/_base/lang ../../ThemeCalculator ../../ChartTypes ../../ChartLineStyles ../../ChartLineMarkers ../../AxisUtil ../utils/ChartDataUtil ../utils/TooltipInfoBuilder ../ChartPlots esri/dijit/geoenrichment/utils/ColorUtil ./_AxisBuilder ./_PointLabelUtil".split(" "),function(G,C,D,v,H,I,E,J,K,L,M,B){var N={calcLineStyle:function(a,h,m,c){var b=c.comparisonInfo,k=c.visualProperties;h=C.calcColorForPoint({point:null,
seriesItem:a,pointIndex:0,seriesIndex:h,numSeries:m.length,chartType:D.LINE,themeSettings:c.themeSettings,isComparisonSeries:a.isComparisonSeries,comparisonInfo:b,isMultiFeature:c.isMultiFeatureChart});m=k.lineThickness||1;k=k.fillLineArea?k.lineAreaOpacity:1;c=v.SOLID;var e=void 0;a.isComparisonSeries&&b&&(b.lineThickness&&(m=b.lineThickness),b.lineStyle&&(c=b.lineStyle),e=b.lineMarker?H.getMarkerPath(b.lineMarker):C.getComparisonSymbol());1>k&&h&&(h=L.toColor(h),h.a=k);return{color:h,width:m,style:v.toGFXValue(c),
marker:e}}};return{calcSeriesLine:function(a){var h=a.chart,m=a.chartType,c=a.visualProperties,b=a.seriesItems,k=1===b.length,e=a.seriesItemsWithComparison||b,q=a.isSecondaryPlot,y=a.reverseXY||m===D.VERTICAL_LINE,O=a.comparisonInfo,b=a.themeSettings,r=a.viewModel,n=[],f={minYValue:Infinity,maxYValue:-Infinity,stackedValues:c.isStacked?[]:null,crossSeriesStats:null},z=a.primaryPlotStat&&a.primaryPlotStat.pointIndexToTooltipsHash||{},p=e.map(function(c,g){return this._collectStatisticsForSeries(a,
c,q?2*g+1:g,f)},this);f.crossSeriesStats=a.isMultiFeatureChart&&this._collectCrossSeriesStats(p);e.forEach(function(w,g){if(w.points.length){var b=N.calcLineStyle(w,q?2*g+1:g,e,a),u={name:w.label,data:[],isComparisonSeries:w.isComparisonSeries,params:{plot:q?K.SECONDARY:void 0,stroke:{color:b.color,width:b.width,style:b.style},fill:b.color,outline:!1}},t=p[g];w.points.forEach(function(d,e){function n(){return q&&!a.oppositeDirections&&2===a.primarySeries.length?0===g?-.15:.15:0}if(!d.hidden){var p=
t.values[e],F=p||0,A=e+1;B.updatePointIndexToLabelMap(h,A,g,d,r);var l=a.isMultiFeatureChart&&f.crossSeriesStats[e],l=J.getTooltipInfo({yValue:p,pointLabel:B.getPointLabel(d,r),seriesLabel:w.label,minInSeriesValue:t.minInSeries,maxInSeriesValue:t.maxInSeries,sumInSeriesValue:t.valuesSum,absSumInSeriesValue:t.absValuesSum,avgInSeriesValue:t.avgInSeries,minInAreasValue:l&&l.min,maxInAreasValue:l&&l.max,sumInAreasValue:l&&l.sum,absSumInAreasValue:l&&l.absSum,avgInAreasValue:l&&l.avg,visualProperties:c,
chartType:m,isMultiFeature:a.isMultiFeatureChart,color:b.color,conditionalStyling:null,fieldInfo:d.fieldInfo,isThisAreaSpecific:O&&!a.isMultiFeatureChart?!w.isComparisonSeries:void 0,isThisAreaSingleSeries:k,decimals:d.value&&d.value.decimals}),x=z[A]=z[A]||[];x.push(l);l.getGroup=function(){return x};d={originalValue:p,isUnavailableData:isNaN(p),unsortedIndex:e,seriesIndex:g,name:B.getPointLabel(d,r),valuesSumsInSeries:t.absValuesSum,point:d,fill:"#FFFFFF",stroke:{color:b.color,width:1,style:v.toGFXValue(v.SOLID)},
outline:!1,tooltip:l};r.isGraphicStyle?b.marker&&(d.marker=b.marker):d.marker=void 0;y?(d.x=F*(q&&a.oppositeDirections&&1===g?-1:1),d.y=A+n(),d.valueProp="x"):(d.x=A+n(),d.y=F*(q&&a.oppositeDirections&&1===g?-1:1),d.valueProp="y");c.yAxis.showValuesAsWeightsInSeries&&(d[y?"x":"y"]/=t.absValuesSum/100);u.data.push(d)}});n.push(u)}},this);f.stackedValues&&(f.stackedValues.sort(function(a,b){return b-a}),f.minYValue=f.stackedValues[f.stackedValues.length-1],f.maxYValue=f.stackedValues[0]);if(q){if(a.primaryPlotStat&&
(a.primaryPlotStat.minYValue=Math.min(f.minYValue,a.primaryPlotStat.minYValue),a.primaryPlotStat.maxYValue=Math.max(f.maxYValue,a.primaryPlotStat.maxYValue),b=I.getPrettifyYAxisParameters(a.primaryPlotStat.minYValue,a.primaryPlotStat.maxYValue,{baseLineValue:c.yAxis.baseLineValue,renderColumnBarsInOppositeDirections:a.oppositeDirections,previewBelowZero:!r.dynamicReportInfo}),G.mixin(h.axes.y.opt,{majorTickStep:b.majorTickStep,minorTickStep:b.minorTickStep,min:b.min,max:b.max})),1===a.primarySeries.length){var u=
y?"y":"x",x=[];a.primarySeries[0].data.forEach(function(a){var b=n[0].data[a.unsortedIndex];b[u]=a.x;x.push(b)});n[0].data=x}}else M.prettifyYAxis(f.minYValue,f.maxYValue,h,c,m,b,r);return n},_collectStatisticsForSeries:function(a,h,m,c){var b=a.chartType,k=a.viewModel,e=a.visualProperties,q=a.currentFeatureIndex,y=a.isMultiFeatureChart,v=a.comparisonFeatureAttributes,r=a.isSecondaryPlot,n=[],f=0,z=0,p=1E6,u=-1E6,x=2===a.seriesItems.length&&a.oppositeDirections&&r?E.CHART_DATA_SMOOTH:null;h.points.forEach(function(a,
c){var g=a.hidden?void 0:E.getPointValue({point:a,index:c,seriesIndex:m,maxValue:!1,chartType:b,visualProperties:e,viewModel:k,currentFeatureIndex:y?m:q,chartData:x,isComparisonSeries:h.isComparisonSeries,comparisonFeatureAttribute:v&&v[0],allowNegativeValuesInPreview:!1}),g=(n[c]=g)||0;a.hidden||(f+=g,z+=Math.abs(g),p=Math.min(p,g),u=Math.max(u,g))});h.points.forEach(function(a,b){a.hidden||(a=n[b],a=e.yAxis.showValuesAsWeightsInSeries?a/z*100:a,c.stackedValues?(c.stackedValues[b]=c.stackedValues[b]||
0,c.stackedValues[b]+=a):(c.minYValue=Math.min(a,c.minYValue),c.maxYValue=Math.max(a,c.maxYValue)))});return{values:n,valuesSum:f,absValuesSum:z,minInSeries:p,maxInSeries:u,avgInSeries:f/h.points.length}},_collectCrossSeriesStats:function(a){return a.length?a[0].values.map(function(h,m){var c=0,b=0,k=1E6,e=-1E6;a.forEach(function(a){a=a.values[m]||0;c+=a;b+=Math.abs(a);k=Math.min(k,a);e=Math.max(e,a)});return{sum:c,absSum:b,min:k,max:e,avg:c/a.length}}):[]}}});